### ISSUE TITLE
Image processing options analysis

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#1]
Analyze options for a 3rd party image processing solution.  Come up with a recommendation.  

Also include the option of rolling our own with an estimate of how long that would take.  Dan is open to that option, especially if it can integrate with [SVG Autocrop](https://github.com/cncf/svg-autocrop) which was developed by CNCF.

**Comment by thetwopct** [comment]
I'm going to be finalising my thoughts on this later today, I've been waiting to pull some performance data from a few test sites.

As part of my research, I read on the Pantheon website that they offer image optimisation as part of their Professional Services.

https://pantheon.io/docs/professional-services#advanced-cdn

Pantheon runs via Fastly CDN, so is most likely providing the following optimisations:

https://docs.fastly.com/en/guides/configuration#_image-optimization 
https://docs.fastly.com/en/guides/setting-up-image-optimization

I would think its worth having a chat with them to see what additional costs (if any) are involved. Their service isn't amazing compared with some dedicated image processing services, but it may be efficient to use them for part of the optimisation and then provide others (Lazy loading, cropping etc) via WordPress.

**Comment by cjyabraham** [comment]
Sounds good.  I reached out to Pantheon and they created [a ticket](https://dashboard.pantheon.io/sites/f74d847c-e689-4631-a91b-24b7f897139b#support/ticket/277737) for me.  Maybe we can get a call with them this week for us all to discuss.

It does seem, however, that having an Advanced CDN requires a manual onboarding process and ongoing maintenance, judging by [the description](https://pantheon.io/docs/professional-services#advanced-cdn).  I'm doubtful whether that will be better than us just implementing our own solution, however, we can have a call to find out.

**Comment by cjyabraham** [comment]
[done](https://docs.google.com/document/d/1ZKAu_fGAGOJvukZyEW57IagLlJVFIumTVNlIbcL0ZGA/edit#heading=h.x096qjxlrr15)
