### ISSUE TITLE
Move KubeWeekly into cncf.io

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#107]
We want to move [KubeWeekly](https://kubeweekly.io/) into a page on cncf.io and then redirect kubeweekly.io to that page.  There is automation built into the site that will need to be duplicated. 

Kristi Tan and Taylor should be consulted for decisions on this project.  There is currently a branding change going on to change the name to "Cloud Native Weekly".

A list of open questions:

1. What is the reason for wanting to move KubeWeekly under cncf.io?
2. What automation processes exist?  
3. To what degree do we need to preserve the design?  
4. What is the current editorial process?  
5. What are the pain points?
6. Who are the key players?  
7. Do people consume the content mostly through the website or via the newsletter?  What are the analytics?
8. Where should we display it in cncf.io?  Under "Blog & news"?
9. I assume all posts need to be migrated over?

**Comment by KTan1226** [comment]
Hi @cjyabraham ! Answering your questions in line below:

- What is the reason for wanting to move KubeWeekly under cncf.io? _I think it will help to give us better tracking for analytics and internal team access._
- What automation processes exist? _Each week, when the newsletter is sent out, it publishes to KubeWeekly.io immediately. Diego can likely give more context but that is the only automation I'm aware of._
- To what degree do we need to preserve the design? _No strong opinions on this one._
- What is the current editorial process? _Each week, I work with the editors to curate content from the following week. I then review the content, finalize, build and send it out via MailChimp._
- What are the pain points? _We don't currently have edit access and are also working to move away from MailChimp, and add KubeWeekly into HubSpot._
- Who are the key players? _Alex Contini, Diego and I._
- Do people consume the content mostly through the website or via the newsletter? What are the analytics? _Not sure on this one as I don't have access. Diego might be able to._
- Where should we display it in cncf.io? Under "Blog & news"? _Yes, I think that makes sense._
- I assume all posts need to be migrated over? _If possible, yes! _

**Comment by cjyabraham** [comment]
Thanks.  Here are some additional questions:
1. Would a simple embedded iframe be adequate, similar to how we embed our newsletters on the events site?
2. Do the newsletters need to be searchable via the cncf.io search?
3. What kind of analytics do you need?  Is Google analytics adequate?
4. What kind of edits would you need to do after submission of a newsletter?
5. How many subscribers are there currently?
6. Is there still a brand change happening to Cloud Native Weekly?
7. What’s the plural of “kubeweekly”?  “Kubeweeklys”?

**Comment by KTan1226** [comment]
Hi Chris! Answers inline:

1. Would a simple embedded iframe be adequate, similar to how we embed our newsletters on the events site? _I think this sounds right but I'll let Diego confirm._
2. Do the newsletters need to be searchable via the cncf.io search? _If possible, that would be nice. _
3. What kind of analytics do you need? Is Google analytics adequate? _Google Analytics is perfect. We're really just interested in pageviews._
4. What kind of edits would you need to do after submission of a newsletter? _We rarely need to make edits but if so, it is because of a broken link._
5. How many subscribers are there currently? _15,659_
6. Is there still a brand change happening to Cloud Native Weekly? _Not at this time._
7. What’s the plural of “kubeweekly”? “Kubeweeklys”? _I think so but that doesn't sound totally right. I think we can just title it KubeWeekly and use the issue number to differentiate each week._

**Comment by cjyabraham** [comment]
FYI there have been just 1,353 users visit https://kubeweekly.io/ in the past 30 days, in comparison with the 15659 subscribers to the email.

**Comment by cjyabraham** [comment]
If you’d like to keep the archive intact, there are a few ways I can integrate the existing archive items:

1. [HTML full style integration](https://pr-396-cncfci.pantheonsite.io/kubeweekly/kubeweekly-255/) - this is what you have on https://kubeweekly.io/.  As you can see in my example, a lot of the rendering is currently broken when added to the cncf.io site.  Although it’s possible, it would take some work to get the HTML/CSS to render correctly within cncf.io.
2. [Text-only integration](https://pr-396-cncfci.pantheonsite.io/kubeweekly/kubeweekly-252/) - we could preserve just the text-only version of the KubeWeekly email.  This is easier to integrate wrt styles but we lose the formatting and images.

And for future HubSpot versions of KubeWeekly, here are the integration options:

1. HTML full style integration (as above)
2. [iFrame integration](https://pr-396-cncfci.pantheonsite.io/kubeweekly/kubeweekly-253/) - this option is only possible for future HubSpot editions of KubeWeekly.  As you can see, it renders the email perfectly, however, the email isn’t searchable in the cncf.io search.  Also, it relies on us keeping our HubSpot account active.
3. [Link to the email](https://email.linuxfoundation.org/linux-foundation-events-snapshot-march-2021?ecid=ACsprvvkCGhXxPIR3DHAT3ckxXDwAxiulH0ERI94wow65XhJmRzQDG-nutwv94nyaGiKxFLwL_2y&utm_medium=email&_hsmi=116251578&_hsenc=p2ANqtz--6u6QalDziO00ykMkc0fl1v6bO6tYXEgG6Ao3ffrA10DJTTUI9dfILLFP7vuRivXj5uK-igT-luTqUQ5kfo-iou7K9PQ&utm_content=116251578&utm_source=hs_email) - rather than hosting the email on cncf.io, we could just link from the KubeWeekly page directly to the HubSpot browser version.  This is similar to 2 but might be a better experience for the user.

One final option is we could not have an archive at all and could just embed the latest issue of KubeWeekly in an iframe on [the main KubeWeekly page](https://pr-396-cncfci.pantheonsite.io/kubeweekly).  That would give anyone who is interested in signing up a sense of what they would get in future issues which is perhaps all the archive was for anyway.

Do you have a sense of which options would best meet your goals for KubeWeekly?

**Comment by KTan1226** [comment]
Hi Chris! Thanks for sharing this. My thoughts:
- Move forward with the text-only integration for the previous versions
- Move forward with the Link to email option for future versions

My only question is that can we make edits to the "link to email" option for future versions once they go live on cncf.io? We sometimes run into broken links so having the ability to make a quick edit might be helpful.

**Comment by cjyabraham** [comment]
To your question, [it does not look like you can edit the web version of an email](https://community.hubspot.com/t5/HubSpot-Ideas/Editing-Web-Version-of-Published-E-mail/idi-p/259068) in HubSpot after it is sent, since the web version needs to accurately reflect the version that was sent.  It essentially gets locked when you send the emails.

One alternative, if there really is something wrong with the email after sending, we can remove the web version, duplicate the email and create a new edited web version that we link to.  This is a bit cumbersome but doable if something really needs to be fixed.

Of course, since more than 10 times the people get the email than visit the web version, it would be in our interest to really make sure there are no broken links before the email gets sent.

**Comment by KTan1226** [comment]
Ah ok, totally makes sense. That works for me. Thanks!

**Comment by cjyabraham** [comment]
This is done.
