### ISSUE TITLE
Instead of Events We'll Be At, show Upcoming CNCF Events on homepage

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#109]
As requested by Kim in [this doc](https://docs.google.com/document/d/1XWkk3Z9tZLXWBxccec07kXIwE7qo0CHO9Tc-3V4pPJ0/edit#heading=h.wzpm8cq4i2yp)

**Comment by thetwopct** [comment]
OK, the event block is setup to show all events, or filtered by taxonomy (CNCF, LF, 3rd party). So super simple for editors or us to change at anytime.
