### ISSUE TITLE
Spotlight listing on homepage

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#110]
Does it make sense to omit the title and spotlight type on the Spotlight listing on the home page and just have the social media images?  They contain all the same info.  We may still want to keep these on the [spotlight listing page](https://dev-cncfci.pantheonsite.io/spotlights/) so that people can CTRL-F to search for a name possibly.  I think keeping the date is good in either case.

**Comment by thetwopct** [comment]
I am of the belief that any text that users need to read should not only be inside an image; an image is an accompaniment to text not a replacement. Its not accessible, you cannot translate it, you cannot copy and paste it, text in an image is sometimes hard to read, doesn't work responsively, etc etc. So I don't think it makes sense.

**Comment by cjyabraham** [comment]
I think, then, we should not use the social image for these spotlights but should instead use the profile image of the person or logo of the project.  Any thoughts?

**Comment by thetwopct** [comment]
Well I don't see an issue with using the social image and text together. It's a common layout for blogs, Pinterest, social platforms etc, so the potential doubling of information doesn't phase me.

I guess it bothers me that the creation of other promotional images across the site have been automated now (case study box, event box etc), so Spotlight will be the only section reliant on a manually created image. But maybe that will change, for now, I would say leave as is?

**Comment by cjyabraham** [comment]
Ok, leave for now and perhaps we can find a way to automate the images in the future.
