### ISSUE TITLE
Improve quality of CNCF logo on blog listing

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#113]
I'm not sure where you found [this logo](https://dev-cncfci.pantheonsite.io/wp-content/themes/cncf-theme/images/thumbnail-default.svg) that shows up on [blog listings](https://dev-cncfci.pantheonsite.io/news/page/2/) but the quality doesn't look so good and it looks cropped at the bottom.  Can you [use this one instead](https://raw.githubusercontent.com/cncf/artwork/master/other/cncf/stacked/color/cncf-stacked-color.svg?sanitize=true)?

Similarly, if we're going to continue to use [this one](https://dev-cncfci.pantheonsite.io/wp-content/uploads/2020/05/test-image-520x320.jpg) I wonder if we can recreate it with [the proper SVG](https://raw.githubusercontent.com/cncf/artwork/master/other/cncf/horizontal/color/cncf-color.svg?sanitize=true)?

**Comment by cjyabraham** [comment]
I've fixed the [news logo](https://dev-cncfci.pantheonsite.io/wp-content/themes/cncf-theme/images/thumbnail-default.svg).  How about just using that one for blog items without a featured post?

**Comment by thetwopct** [comment]
The SVG is a bit too flush to the edges and doesn't work at some breakpoints

![20200601191810-Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/83440330-a915e980-a43c-11ea-8a36-c92555c72943.jpg)

I've used a custom PNG with some padding around it instead

![20200601192025-Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/83440500-f3976600-a43c-11ea-8860-3dc00ef022c1.jpg)

**Comment by cjyabraham** [comment]
Could I create an SVG with some whitespace padding for you to use here instead?  Do you think that would work?

**Comment by thetwopct** [comment]
Go ahead, you can replace it in the Global Settings, and put it in the /images/ folder too.

**Comment by cjyabraham** [comment]
[done](https://dev-cncfci.pantheonsite.io/blog/)
