### ISSUE TITLE
Make dates a consistent format

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#114]
On [events](https://dev-cncfci.pantheonsite.io/events/) you have "August 17, 2020" while on webinars you have "15 May 2020".  Judging from [other](https://events.linuxfoundation.org/) [LF sites](https://www.cncf.io/newsroom/blog/) they seem to favor the "August 17, 2020" format with the month before the day.  Could we standardize around that for all dates?  I'm not sure if I favor full month "August" or three-letter form "Aug".  The events site uses both.  @dankohn any preference?

**Comment by dankohn** [comment]
I like RFC 3339 date format, but I think we should go with "August 17, 2020".
