### ISSUE TITLE
Twitter embed

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#116]
I've setup a custom Gutenberg block to embed the CNCF twitter timeline using the official [docs](https://developer.twitter.com/en/docs/twitter-for-websites/timelines/overview). However the height of the block is quite erratic - sometimes a tweet is just text, but other times a large imager a video. So aligning the block with other blocks and getting it to look uniform is quite difficult. 

I'd like to use this [plugin](https://wordpress.org/plugins/custom-twitter-feeds/) to pull in and style the tweets. This will allow me to hide data cards (like image and video) and only include the tweet text, as well as arrange the tweets horizontally. This would allow us to align the tweets on the home page with other blocks and make it look consistent.

If this sounds OK, are you able to install it and set it up? To use the plugin, an access token needs to be generated from the Twitter account, so you'll need the Twitter login details.

**Comment by cjyabraham** [comment]
the plugin is installed... just waiting to configure the account...

**Comment by cjyabraham** [comment]
Now connected.
