### ISSUE TITLE
Menu colors

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#117]
I think all submenus and sub-submenus should be one shade.  Right now I think there are too many colors going on in the menu:
<img width="827" alt="Screen Shot 2020-06-05 at 1 49 26 PM" src="https://user-images.githubusercontent.com/463160/83841512-900a8280-a733-11ea-950e-a966c34b07e4.png">

Same for mobile.  Can we have all submenus as the same shade?

**Comment by thetwopct** [comment]
Not in love with the sub-sub-menu being same colour, let me know your thoughts.git

**Comment by cjyabraham** [comment]
True, it needs some kind of line to separate the submenu from the sub-submenu.  What about using [the colors here](https://dev-5-19-cncfci.pantheonsite.io/) for the submenu and sub-submenu.  I feel those looked better for some reason.

**Comment by thetwopct** [comment]
I'm pretty happy with the menu colours currently, so unless issues let's close this.
