### ISSUE TITLE
Add border to webinar tiles on homepage

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#119]
I feel these need some sort of border:
<img width="957" alt="Screen Shot 2020-06-05 at 2 04 24 PM" src="https://user-images.githubusercontent.com/463160/83842444-8bdf6480-a735-11ea-87de-fe56bd252e94.png">

**Comment by thetwopct** [comment]
The webinars for home are currently set to have a padding around them on a white background so they stand out on the blue background. As we're working on the layout, order and the cohesion these have been nudged out of that blue background section.
I'm going to close this for now as this is an issue I'm aware of this and will fix as part of home page design changes https://github.com/cncf/cncf.io/issues/45
