### ISSUE TITLE
Chrome autocomplete problem on newsletter form

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#121]
Can you remove the background coloring here the same way you did for lfph?  It occurs when I use chrome autocomplete for field values:
<img width="1156" alt="Screen Shot 2020-06-05 at 2 18 46 PM" src="https://user-images.githubusercontent.com/463160/83843429-85ea8300-a737-11ea-9358-cefdec8bc300.png">

**Comment by thetwopct** [comment]
Should I do this just for the newsletter where it looks a bit odd due to the styling, or should I also override for autofill for other forms, such as https://dev-cncfci.pantheonsite.io/about/contact/

**Comment by cjyabraham** [comment]
I think just for the newsletter.  I'm fine with how the contact form autocomplete looks.
