### ISSUE TITLE
More consistent font sizing

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#124]
I feel there are too many fonts in this section.  For the para that starts "Jeff Brewer..." can you use the same font as the previous paragraph?
<img width="675" alt="Screen Shot 2020-06-05 at 2 43 20 PM" src="https://user-images.githubusercontent.com/463160/83845241-0c549400-a73b-11ea-8129-6498589bbedd.png">

**Comment by thetwopct** [comment]
I've updated the typography of this particular section, and have improved the fonts generally to play nicer together. If you see other issues relating to this, they may be where Block Editor needs updating, or they need a specific fix, so would be best opened as individual issues.
