### ISSUE TITLE
The wordwrap on mobile here doesn't look right

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#126]
<img width="392" alt="Screen Shot 2020-06-05 at 2 54 44 PM" src="https://user-images.githubusercontent.com/463160/83846045-8afe0100-a73c-11ea-8204-874e39e29aca.png">

**Comment by thetwopct** [comment]
Just a line break added in the block editor 👍

**Comment by cjyabraham** [comment]
I know that, but what I'm saying is that way of making something deliberately wrap on desktop won't scale well to mobile so we should consider another way.

**Comment by thetwopct** [comment]
I mean, it was just a line break, that I removed, so the wrap is now natural based on max-width?

This is the another way.
