### ISSUE TITLE
Style Search results page

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#127]
See [this search](https://dev-cncfci.pantheonsite.io/?s=test).  The SiliconANGLE entry is a news item and should look and behave the same as in [the news listing](https://dev-cncfci.pantheonsite.io/news/): external link icon, link to 3rd party, no byline, etc.

**Comment by thetwopct** [comment]
I hadn't thought of the results much until now, this is just pulling in a default post template based on the first results type.

I think the scope is bigger than just News items, as the search pulls in most content of the site - events, posts, pages, webinars. 

My original plan was to make the search results more text based, and less like each individual element of the site (an event or webinar box won't look good next to a blog post). I didn't think we would need the images as many posts and pages may not have an image attached to it.

Any thoughts?

**Comment by cjyabraham** [comment]
Text based sounds good.  It just needs to be functional, not necessarily look impressive.

**Comment by thetwopct** [comment]
This should look better now. I've added some different meta based on different post types. I also looked at the top search queries over the last 6 months - "landscape" is the 2nd most searched for term, and it's result wasn't amazing as I presume most people are just looking for the landscape link - so I made a custom search result for that query to link to the landscape sub-domain.
https://dev-cncfci.pantheonsite.io/?s=landscape

**Comment by cjyabraham** [comment]
Looks really nice.  I wonder if we should not have the "Blog Post" tag and only show the "CNCF MEMBER BLOG POST" tag in cases [like this](https://dev-cncfci.pantheonsite.io/?s=test):
<img width="542" alt="Screen Shot 2020-06-08 at 8 55 02 AM" src="https://user-images.githubusercontent.com/463160/83984108-e0692680-a965-11ea-8c3c-5985b542e946.png">

Same goes for webinars.  Having both tags seems redundant.  Alternatively, we could just omit the "CNCF MEMBER BLOG POST" but keep "Blog post".  Perhaps this is a broader question for @KimMcMahon wrt how much we should be surfacing these author types throughout the site?

**Comment by thetwopct** [comment]
I considered removing it, but I really like the consistency of being able to scan down that first entry and quickly see what the search result is. I figured that would be more useful to users, and knowing the author category was secondary information, and maybe on the search results page the author category could be removed.

**Comment by KimMcMahon** [comment]
I agree with both of you. I like the consistency, but it also looks redundant.

What if the "CNCF Member Blog Post" was a different color - maybe a gray?

Thanks!

**Comment by cjyabraham** [comment]
Gray might help but you'd still have "blog post" repeated twice right next to each other.  I think my vote would just be to omit the "CNCF Member Blog Post" tag here as, for someone scanning search results, it's likely unnecessary information and just creates noise in addition to redundancy.  You're call, however, @KimMcMahon :)

**Comment by KimMcMahon** [comment]
Julie - can you work on this with James and @cjyabraham 

Chris - Julie's GH is @jkld11

**Comment by jkld11** [comment]
Would it work to make the second tag "CNCF Member"?

**Comment by cjyabraham** [comment]
@jkld11 I think that could leave things ambiguous.  These tags indicate the category for the author of the post.  If we just had "CNCF Member", its meaning is no longer clear.  It might mislead people into thinking that it's a blog post about a member.

**Comment by thetwopct** [comment]
All, I've implemented CNCF Member Content boxes, you can see an example here 

https://dev-cncfci.pantheonsite.io/?s=test

**Comment by cjyabraham** [comment]
I don't know about this.  I don't like how we now have "CNCF Member Content" on search results but have "CNCF Member Blog Post" on the [blog listings](https://dev-cncfci.pantheonsite.io/blog/).  I think we should be consistent in the way we designate something as authored by or on behalf of a member, project, etc. so that people learn to recognize the designation.

It might be worth asking around to see if "CNCF Member Content" is clear to other people.  I'm afraid people may think it means content about a CNCF Member, which it's not.  

I think my take would still be to just drop the tag completely on search results but I'll defer to you @jkld11.

**Comment by KimMcMahon** [comment]
Agree we need to be consistent on the terms.

We started using "CNCF Member Blog Post" as guidance from the TOC that we note member posts. They actually wanted to call them 'sponsored' posts since members pay a fee to join CNCF, which I did not want to do. Using 'member' as well as project, ambassador, etc for the type of the blog post was the resolution.

What search page is this? A general search page where we can get any kind of content? If so, I think both "Blog post" and "CNCF Member Blog Post" should both stay. 

I'll go back to the suggestion that "CNCF Member Blog Post" or whatever the second item is in the search be a different color and not use 2 hues of blue.

Maybe the 4 of us get on a call and look at the pages and discuss to get to a solution?

**Comment by cjyabraham** [comment]
Yes, it's [the general free-text search results](https://dev-cncfci.pantheonsite.io/?s=test) where various types of content are listed side-by-side.

I'm fine with having both stay.  James has turned the "CNCF Member Blog Post" tag grey now to differentiate from the blue.  Maybe that's the best solution if we want to really emphasize member-generated content.
