### ISSUE TITLE
Change KubeCon events

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/cncf.io#13]
To enable easy edits and automation, change the KubeCon + CloudNativeCon events on this [page](url).
https://www.cncf.io/community/kubecon-cloudnativecon-events/

- [ ] Image is created for each event

- [ ] Add date functionality that can be applied to each event block so events automatically are removed from the page when the event is over

- [ ] Keep the link to the external event page. Update so that link can be updated to each event block

Ideally, I would like the image blocks blank, with just the branding for the event. We would add the date and location about the event on the event page and it would be added to the image.

**Comment by cjyabraham** [comment]
The events on that page are just [the same as these right](https://www.cncf.io/events-well-be-at/?_host=cncf-organized)?  I think we should be able to just pull from that event listing.

**Comment by cjyabraham** [comment]
I've captured this in our requirements
