### ISSUE TITLE
Text sizes are too similar to each other

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#131]
The text in these two paragraphs on [the join page](https://dev-cncfci.pantheonsite.io/about/join/) seems hardly but slightly different.  Could you either make them the same size or make the difference greater between them?  I think the way you did it [on this page](https://dev-cncfci.pantheonsite.io/telecom-user-group/) looks better.
<img width="476" alt="Screen Shot 2020-06-05 at 3 24 10 PM" src="https://user-images.githubusercontent.com/463160/83848653-c5699d00-a740-11ea-8370-aa66d85b0d89.png">

**Comment by thetwopct** [comment]
Luke has advised we use the following pattern for the pages:

H1 Title / Hero
H3 Introductory (1st) Paragraph
P Text + onwards

The above were different experiments around that i.e. H1, H3, H4, P to stagger the intro of pages.

For now I've updated the pages you highlighted, but any others we notice we can update as we go.
