### ISSUE TITLE
TOC placement on the join page

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#132]
What about putting the TOC after the "Take an active role in Cloud Native" block on the join page.  That block is different in style than all the other links in the TOC.  Maybe omit it from the TOC and place the TOC after?

**Comment by thetwopct** [comment]
Editors can change the position of the ToC in the Editor if they want to move it.

It makes sense to me the way it is. Yes it's a different style, but we want to inject different styles where possible to make it engaging. The block on its own doesn't explain much, only as a complete document are the benefits of joining fully explained.

**Comment by cjyabraham** [comment]
Did you consider using the sidebar TOC format, like in the FAQ?  I know that takes up some width so you'd need to reformat some of your blocks but it's a more effective navigation tool.  Just a thought...

**Comment by thetwopct** [comment]
I did consider it, but I felt like the different aspects of the page (it needs the width in some places for the revised design to work, vertical spacing in others) and the importance of the page within the website meant that this custom layout would be more appropriate. Nothing stops an Editor transitioning the page to the Tab Container layout if they want to try it.

**Comment by cjyabraham** [comment]
Cool.  Let's leave it as an exercise for the editor then :)
