### ISSUE TITLE
Paragraph spacing inconsistencies

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#133]
There's often more space below a title than before it.  Shouldn't it be the opposite?  I notice this in a few places but here's are 2 example:
<img width="222" alt="Screen Shot 2020-06-05 at 3 30 18 PM" src="https://user-images.githubusercontent.com/463160/83849157-90117f00-a741-11ea-8de6-a36007141d09.png">
<img width="300" alt="Screen Shot 2020-06-05 at 3 31 46 PM" src="https://user-images.githubusercontent.com/463160/83849252-b46d5b80-a741-11ea-886b-518463b26e31.png">

**Comment by thetwopct** [comment]
Heading and Paragraph spacing + styles should now be more consistent. 

There is a Style that can be applied to Headings and Paragraph for no margins too, so that is something an editor can override. If there are other needs, we can add it.
