### ISSUE TITLE
Content margin too narrow on some pages

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#134]
It looks like you recently made the content margin more narrow than the tile displays [on](https://dev-cncfci.pantheonsite.io/speakers/) [these](https://dev-cncfci.pantheonsite.io/case-studies/) [pages](https://dev-cncfci.pantheonsite.io/webinars/).  I think I preferred it where the opening blurb and search dropdowns spanned the full width of the page.

**Comment by thetwopct** [comment]
Ah yeah not a [deliberate](https://github.com/cncf/cncf.io/blob/238d3abdb03f4d0050d2e50e3c5998aee4ad54e0/web/wp-content/themes/cncf-theme/source/scss/core/_entry-content.scss#L91) choice. Trying to limit the widths of <ul> from content generated in the block editor.

**Comment by cjyabraham** [comment]
The [opening blurbs](https://dev-cncfci.pantheonsite.io/case-studies/) are [still constrained](https://dev-cncfci.pantheonsite.io/webinars/).  It looks odd to me.  I think it'll look better just allowing them to go full-width?

**Comment by thetwopct** [comment]
Got it. In these places where the layout of the page is suited to a 100% width text, there is now a block style to pick that will do that. The pages you mentioned are fixed, if any more, can be updated in block editor.
