### ISSUE TITLE
Fire nav JS based on window resize

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#135]
When I click on the menu items with my mouse, nothing happens.

**Comment by thetwopct** [comment]
Did you resize your window from desktop to mobile? I have a todo to rewrite the JS so it fires on resize. Desktop and mobile menus work quite differently.

**Comment by cjyabraham** [comment]
Ah, yes, you're right.  It works fine if I set the browser size prior to page load.  Demoting as a nice-to-have.

**Comment by thetwopct** [comment]
Fixed as part of LFPH improvements 👍
