### ISSUE TITLE
Embedded tweets

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#141]
Example:
https://www.cncf.io/blog/2018/05/15/a-look-back-at-kubecon-cloudnativecon-europe-2018/

Once imported in to new site the embedded tweets aren't picked up, and once converted to blocks, not all of the tweets are converted to embeds.

https://dev-cncfci.pantheonsite.io/blog/2019/05/31/a-look-back-at-kubecon-cloudnativecon-barcelona-2019/
https://dev-cncfci.pantheonsite.io/blog/2018/05/15/a-look-back-at-kubecon-cloudnativecon-europe-2018/

May require a manual task of editing, I believe this search term should highlight all of the posts that contain twitter embeds

https://dev-cncfci.pantheonsite.io/?s=twitter-tweet

**Comment by cjyabraham** [comment]
`<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>` is getting stripped out...

**Comment by cjyabraham** [comment]
It looks like there are about 15 problem posts that are missing the widgets.js.  It's not clear to me why these posts are losing the widgets.js scrips and others aren't, however, I'll put this as [a step for manual checking after final import](https://docs.google.com/spreadsheets/d/1ufJUHCkt4cT_Ovdm3T7y8oRTvj69IEMI9cqJHDYSM6w/edit#gid=48867274).
