### ISSUE TITLE
Style new Twitter timeline block

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#142]
Horizontal alignment

**Comment by cjyabraham** [comment]
Are you sure we want this horizontal?  Is that more work than just vertical?

**Comment by thetwopct** [comment]
Not 100% sure yet, need to see it in the page. I feel like 2 tweets vertical next to 2 rows of Media could align nicely. Depends on the ability to fully control card content.

**Comment by thetwopct** [comment]
I've implemented two tweets in a column in line with the amount of In the News items. Let me know what you think, the columns at some resolutions don't look amazing, but the column styles are very opinionated so take a bit of work to override.

**Comment by cjyabraham** [comment]
looks great!
