### ISSUE TITLE
Fix responsive column spacing

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#143]
Column structure needs spacing between columns when on mobile 

![20200609121858-CNCF pages](https://user-images.githubusercontent.com/10615884/84141640-657a3b80-aa4b-11ea-8d6f-821daaa9b6d9.jpg)

**Comment by cjyabraham** [comment]
I think we may need a bit more space between the first column and second.  Here is an example of that:
![Screenshot_20200610-134532_Chrome](https://user-images.githubusercontent.com/463160/84231572-0ab31380-ab21-11ea-812e-164f82563ad2.jpg)

"End User Supporter" is at the top of the second column and seems too close to the text preceding it here.
