### ISSUE TITLE
Custom blocks don't use default values correctly

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#144]
1. Create a new Columns block with 2 columns
2. Add an image into the first one and a paragraph of text into the second
3. You'll see the content looks fine, side-by-side in the editor:
<img width="875" alt="Screen Shot 2020-06-09 at 9 48 25 PM" src="https://user-images.githubusercontent.com/463160/84155500-f6c4ce80-aa9a-11ea-899b-68786cbea7b3.png">
However on the front-end the second column content starts after the first column finishes:
<img width="999" alt="Screen Shot 2020-06-09 at 9 49 00 PM" src="https://user-images.githubusercontent.com/463160/84155562-0ba16200-aa9b-11ea-8460-8237d2e5c1dd.png">
4. Change vertical alignment of the Columns block to be aligned with "top".  You'll notice that this appears to already be set, however, setting it again is needed in order for the setting to really affect the front-end.
5. Save the post and check the front-end.  The columns should be correctly aligned now.

Can we fix this so that the default for the block is set automatically and the user doesn't have to explicitly re-set it?  I'm concerned this problem may be more widespread as I remember we had a similar problem for quote blocks: what appears to be the default value in the editor doesn't actually apply to the front-end unless you explicitly re-choose it.

**Comment by cjyabraham** [comment]
I found another case of a custom block not using the default value.  I added an image hero block on the lfph homepage.  It appears to have a height of 400 set by default, however, when I look at it on the front-end I get:

> Warning: A non-numeric value encountered in /srv/bindings/ab9a3ab4100442a19e52f1346ec4ab09/code/web/wp-content/mu-plugins/lf-blocks/src/image-hero/render-callback.php on line 28

I need to explicitly change the height to something else for it to take.

**Comment by cjyabraham** [comment]
This is true as well for paragraph blocks.  The "Default" style isn't applied until you click off and on it again.

**Comment by thetwopct** [comment]
Closing this, as these are different issues and technically not related to the original issue.
