### ISSUE TITLE
Could we have a ">>" after each "View more..." link?

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#146]
What do you think about a [double chevron pointing right](https://fontawesome.com/icons/angle-double-right?style=solid) (or some similar icon) after each "View more..." link on the homepage?  I think they could use distinguishing a little bit.

We use a similar one on the events site:
<img width="480" alt="Screen Shot 2020-06-10 at 9 25 45 AM" src="https://user-images.githubusercontent.com/463160/84216527-6a4af800-aafc-11ea-8195-9a9469553b21.png">

**Comment by thetwopct** [comment]
I've added this as a style for Paragraph and Header blocks. Currently the chevrons are in the pink link colour as that is the use-case.

https://dev-cncfci.pantheonsite.io

I'm not that keen on it. I think the stroke of the chevron SVG is possibly too thick, it needs to be thinner to match the font weight.

**Comment by cjyabraham** [comment]
There are [a few other options here](https://fontawesome.com/icons?d=gallery&q=angle%20double%20right).  Also, can you make it so that it can be clicked and go to the same url as the preceding text?

**Comment by thetwopct** [comment]
I swapped it out for another file, made it less dominating next to the text, applied it to the A tag instead of the paragraph/heading the Gutenberg style is applied too, so the whole thing is clickable now.
