### ISSUE TITLE
Figure out architecture for Speakers Bureau

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#15]
Consider not using ultimate member and using CPTs for speakers instead.  [See this](https://plugins.trac.wordpress.org/browser/bainternet-posts-creation-limits/trunk/bapl.php).

**Comment by dankohn** [comment]
Specifically, people wanting to add themselves to the Speaker's Bureau would create an account using an LFID, at which point they would only have the option of creating one CPT, which would be their profile. CNCF staff would be notified to approve their post, which would get them listed in the directory. The above link has code that could limit them to a single entry per account. Another approach would be https://wordpress.org/plugins/user-submitted-posts/

**Comment by cjyabraham** [comment]
from slack:

> in terms of how much of the ultimate member plugin we use, I reviewed it’s features here https://ultimatemember.com/features/ :
> Registration - we use 80% of this
> Login - we use 100%
> User Profiles - 80%
> User Roles - 80%
> Member Directory - we currently don’t use this, however we may want to reconsider using the default one as it now has AJAX filters and other nice things (see https://ultimatememberdemo.com/members/ and click “more filters” on the right)
> User Accounts - 100%
> Access Controls - 0%
> Custom Fields - 100%
> Form Builder - 100%
> Email - 100%
> Nav Menu Visibility - 0%
> We could, in theory, rebuild all of the above pieces we use, but it would be an enormous amount of work to get to the level of polish on both the front-end user experience and back-end admin experience that the UM plugin currently has.

Additionally, Diego has successfully upgraded the UM plugin.  I think we should stay with UM and launch SB with the rest of the site.
