### ISSUE TITLE
Improve format of single event page

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#152]
For the [single event page](https://dev-cncfci.pantheonsite.io/events/cloud-native-security-day-2020/), would you consider moving the event image to the right of the page and have the text describing the event on the left?

**Comment by cjyabraham** [comment]
I'm not sure I can see the awfulness you describe, lol.  How about just having the text wrap around the aligned-right tile?  I just don't like how you open [an event](https://dev-cncfci.pantheonsite.io/events/cloud-native-security-day-2020/) and only see the tile and then a ton of whitespace filling most of the browser to the right of it.

**Comment by cjyabraham** [comment]
One alternative is to make the tile the [same size at it is on this page](https://cncfci.lndo.site/events/) and then wrap the text around it?  Something like this:
<img width="1254" alt="Screen Shot 2020-07-05 at 12 10 10 PM" src="https://user-images.githubusercontent.com/463160/86525335-7ede9e00-beb8-11ea-8a36-b9f00b4b19df.png">

or on narrower screens:
<img width="580" alt="Screen Shot 2020-07-05 at 12 10 43 PM" src="https://user-images.githubusercontent.com/463160/86525343-9ae23f80-beb8-11ea-866c-8ab915f2ba58.png">

**Comment by thetwopct** [comment]
That's not really working for me. I'd rather take a different approach and just not re-use the logo/image on the singular page, just keep it in the style of other item/child pages - I've upload a quick version of my take on that.

**Comment by cjyabraham** [comment]
I can see the argument for keeping it consistent with the other child items.  I suppose the editors can add an image if they want one on the detail page.
