### ISSUE TITLE
Cropping of people on mobile

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#155]
The mobile view of people crops the images on mobile.  Sometimes it doesn't work out so well:
![Screenshot_20200610-135219_Chrome](https://user-images.githubusercontent.com/463160/84231900-c2482580-ab21-11ea-952d-c85cd1958cb1.jpg)

Maybe we shouldn't crop like this?

**Comment by thetwopct** [comment]
A few options @cjyabraham :
- Increase the height of the image container
- Change the position of the image in the container (currently defaults to centre,center - maybe top, centre positioning would be better)
- Remove the image container (although we use it across the site, and then the image will either not be full width which will look ugly, and it's height will be equal to its width - too high to make the page manageable for the user on mobile)
- Reduce the size of the whole block so 2 people fit on 1 row. This then has an issue with the length and size of their names, but can probably be worked around

**Comment by cjyabraham** [comment]
Looks pretty good now.
