### ISSUE TITLE
Closing the people profile popup clicks what's underneath the X

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#156]
If there's a photo under the X of the people profile popup, it gets clicked too when you click the X.  Can we stop that from happening?

**Comment by cjyabraham** [comment]
I just notice that you can also scroll the background content when the modal is up on mobile and desktop.  Not sure if that matters so much though...

**Comment by thetwopct** [comment]
New modal system now being used, both issues should now be resolved
