### ISSUE TITLE
Add favicon in a similar way to how we've done it on events.linuxfoundation.org

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#16]
There we used https://realfavicongenerator.net/

**Comment by cjyabraham** [comment]
Looks like this is done.

**Comment by thetwopct** [comment]
Should be done, but WordPress 5.4 changed favicon detection.

https://make.wordpress.org/core/2020/02/19/enhancements-to-favicon-handling-in-wordpress-5-4/

TLDR: Think what I have done works as long as there is a favicon.ico in the website root.
