### ISSUE TITLE
Show date on passed webinars without recordings

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#164]
I think we should show the date [on past webinars that don't have recordings](https://dev-cncfci.pantheonsite.io/webinars/zero-trust-services-in-kubernetes/).  You show it on the search results as "Broadcast on ...."  Maybe just do the same here?

**Comment by cjyabraham** [comment]
Could you use the calendar icon in [this case](https://dev-cncfci.pantheonsite.io/webinars/zero-trust-services-in-kubernetes/), similar to how you have it when it shows up in a search listing:
<img width="474" alt="Screen Shot 2020-06-12 at 7 56 11 AM" src="https://user-images.githubusercontent.com/463160/84450289-431e3300-ac82-11ea-82ca-7ee12ce3bc45.png">

**Comment by cjyabraham** [comment]
Do you think we still need to say "This webinar has passed."?

**Comment by thetwopct** [comment]
Icon added. 

Think it needs something to make it very obvious to the user the event has passed - otherwise they are looking for a register link, or the recorded video.
