### ISSUE TITLE
Improve speakers profile explanation

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#169]
On most content types you don't use the hero image at the top.  Could we do the same for [speaker profiles](https://dev-cncfci.pantheonsite.io/speaker/puja/)?  So use something closer to [this format](https://dev-cncfci.pantheonsite.io/webinars/pivoting-your-pipeline-from-legacy-to-cloud-native/)?  I think the hero image pushes it all down the page too much.

**Comment by thetwopct** [comment]
I've implemented this via a Template file. I've made the name take the place of page title, with a small link above linking back to Speakers Bureau index. I've hidden the original name output next to the photo. But this does mean on some profiles, where the speaker has no intro or affiliations, the page looks a bit [empty](https://cncfci.lndo.site/speaker/austin/).

**Comment by cjyabraham** [comment]
To be consistent [with the](https://dev-cncfci.pantheonsite.io/case-studies/antfinancial/) [other items](https://dev-cncfci.pantheonsite.io/webinars/pivoting-your-pipeline-from-legacy-to-cloud-native/), shouldn't it say "Speaker" on top instead of "Speakers Bureau"?

**Comment by thetwopct** [comment]
Meh, I guess so, have changed it. 

I feel like the profile page needs more explanation. If you land on that page direct with fresh eyes it isn't overly clear who can use it, or what it's supposed to be doing. A brief explanation near the Contact Form might help? Perhaps could also say something like "See XX others who can speak about XXX at your event"

Stats
Speakers Index - 1500 views of which 570 land on this page first from Google
Speakers Login - 1266 views (90% of visitors to the Speakers Bureau are Speakers?)
Speaker Singular Pages - 3146 views of which 1362 land directly on speakers profiles from Google (40% of users come in fresh to the page)

**Comment by cjyabraham** [comment]
I'll file this as a future content consideration.

**Comment by cjyabraham** [comment]
I've rewritten the remaining idea here cleanly #223.
