### ISSUE TITLE
Case study tiles only list two projects; sometimes there are more

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#172]
If we only have room to list two projects on the case study tiles and have to omit the rest, should we just not list them there at all?

**Comment by thetwopct** [comment]
- Only some studies have multiple projects attached, a majority have 1 projects attached.
- Showing more than 2 isn't practical - some have 10+. 
- All can overridden by the meta `cncf_case_study_type` to focus on one particular project.

I would say thats a robust solution. We should speak to the marketing team to see if it's not, or close this until they say it's not.

**Comment by cjyabraham** [comment]
Sounds good.  Let's remember to explain all this to Julie when the time comes.
