### ISSUE TITLE
"Default" style isn't applied until you click off and on it again.

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#175]
This is true as well for paragraph blocks.  The "Default" style isn't applied until you click off and on it again.

_Originally posted by @cjyabraham in https://github.com/cncf/cncf.io/issues/144#issuecomment-643719606_

**Comment by cjyabraham** [comment]
I think you don't even need to click off it.  You just need to click the "Default" style and then it's good.

**Comment by thetwopct** [comment]
I'm not really sure of the issue here. Could you add some more details for me of what you're seeing and what you're expecting?

If I insert a paragraph, the styling doesn't change if I click "Default". I also checked Columns, no difference. The "Default" option is not selected by default, because this is not how Gutenberg works for some reason. I feel like having it there acts more like as a reset button if one of the other Styles is not suitable.

If you are referring to the width of the paragraph when inserted - in the Editor the paragraph currently stretch 100%, and on front end, they automatically wrap at 700px. I don't apply the wrapping in the Editor by default as I felt it was more useful to editors to have their text on screen. If a Style (i.e. 600px max width) is applied, then this is shown in the editor. It's a little inconsistent, but I don't see it being that confusing.

**Comment by cjyabraham** [comment]
I can't reproduce the initial issue now.  The initial style now does indeed match the "Default" style so I think we're good.
