### ISSUE TITLE
Sticky "featured" posts

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#180]
When a post is marked "sticky" it should stay at the top of the blog and top of the homepage listing.   It should have some new way of being tagged "Featured" both on the blog page and on the homepage.

**Comment by cjyabraham** [comment]
Featured tag now showing for [blog posts on homepage](https://dev-cncfci.pantheonsite.io/) and [in the blog listing](https://dev-cncfci.pantheonsite.io/blog/).

Assigning to @thetwopct to check the styling of the "Featured" tags.  Perhaps there's more we can do here?  Currently it doesn't seem to comply with our design language.  Maybe a slash tag in a bright color?

**Comment by thetwopct** [comment]
Yep makes sense. I've added some colour and the skew effect and aligned it to the top of the image inside the padding. Have replicated on the archive.

![20200713151934-Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/87315378-5be96500-c51c-11ea-942d-02d96e976984.jpg)

**Comment by cjyabraham** [comment]
LGTM
