### ISSUE TITLE
Homepage shows only 1 case study even though 3 are set in widget

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#183]
You can set the widget to 2 or 4 and the correct number will show, however, when you set it to 3, only 1 case study shows.  On inspecting the code, the `$attributes` var doesn't seem to be getting set in the case of 3.
<img width="1146" alt="Screen Shot 2020-07-05 at 8 55 53 AM" src="https://user-images.githubusercontent.com/463160/86523330-7167ea80-be9d-11ea-8ac4-c7bc67fde8ae.png">

**Comment by thetwopct** [comment]
This is fixed
