### ISSUE TITLE
China video block styles

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#185]
The [China video block actually styles youtube videos correctly](https://dev-cncfci.pantheonsite.io/case-studies-cn/pinterest/), however, the China qq videos are too small on the page.  Can these be styled the same as the youtube vids?  To create a way to test this, set the parameters for the block both to the qq video.
<img width="1188" alt="Screen Shot 2020-07-06 at 6 09 17 PM" src="https://user-images.githubusercontent.com/463160/86582219-e299c180-bfb3-11ea-9f14-d11d71eac765.png">

**Comment by thetwopct** [comment]
I've make the video/iframe wrapper responsive so it fills 100% width. The demo video didn't quite fit the video dimensions ratio, and I had trouble getting other video URLs to test. If you can test some other QQ videos and let me know it looks better

**Comment by cjyabraham** [comment]
LGTM
