### ISSUE TITLE
Annual report design and migration

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#187]

**Comment by thetwopct** [comment]
[2017](https://dev-cncfci.pantheonsite.io/cncf-annual-report-2017/) is up, I think it looks pretty good!

I ended up having to use a Template file for it in the end, but the HTML is inside the block editor, so content could still be updated or changed to some extent by any Editor.

If you spot any issues, please let me know, otherwise I'll finish up 2018 + 2019.

**Comment by cjyabraham** [comment]
Looks pretty good.  There are some issues on mobile when you go down to a narrow width (360px).  On some devices (Galaxy S6) there is a horizontal scroll bar and on others (Chrome dev tools) just a white column down the right.  Here are some problem spots:
<img width="304" alt="Screen Shot 2020-08-24 at 10 35 43 AM" src="https://user-images.githubusercontent.com/463160/90998276-4d4f9c80-e5f6-11ea-8ece-e27b4bf63543.png">

<img width="335" alt="Screen Shot 2020-08-24 at 10 33 55 AM" src="https://user-images.githubusercontent.com/463160/90998266-47f25200-e5f6-11ea-935d-14b5a6c881ae.png">
<img width="359" alt="Screen Shot 2020-08-24 at 10 34 01 AM" src="https://user-images.githubusercontent.com/463160/90998275-4c1e6f80-e5f6-11ea-90ef-67b6da4a8724.png">

**Comment by thetwopct** [comment]
Those issues above should be done, and the others are built out now

https://dev-cncfci.pantheonsite.io/cncf-annual-report-2017/
https://dev-cncfci.pantheonsite.io/cncf-annual-report-2018/
https://dev-cncfci.pantheonsite.io/cncf-annual-report-2019/

The 2019 was a real pain to integrate, lots of visual composer code and additional divs, had to rebuild lots of it.

Let me know if any feedback

**Comment by cjyabraham** [comment]
Some minor points:

2017
- this title seems to escape its box on mobile:
<img width="329" alt="Screen Shot 2020-08-27 at 10 29 35 AM" src="https://user-images.githubusercontent.com/463160/91376708-4623cb00-e850-11ea-8ef3-4927b4181341.png">


2018
- the big "18" at the top is half-way below the fold on Chrome and, additionally, is too far left in Safari.  Is it possible to make this look more contained like [on the current site](https://www.cncf.io/cncf-annual-report-2018/)?
- I think these boxes could use a bit of padding on mobile:
<img width="343" alt="Screen Shot 2020-08-27 at 10 36 59 AM" src="https://user-images.githubusercontent.com/463160/91377129-47a1c300-e851-11ea-878a-5f94289c00ba.png">
- the color of the footer text seems wrong here:
<img width="349" alt="Screen Shot 2020-08-27 at 10 39 04 AM" src="https://user-images.githubusercontent.com/463160/91377256-93ed0300-e851-11ea-89b0-963382f4d965.png">


2019
- in these headings, is it possible to center the text vertically within the grey box?  Some of them look too low:
<img width="577" alt="Screen Shot 2020-08-27 at 10 16 23 AM" src="https://user-images.githubusercontent.com/463160/91375889-6b173e80-e84e-11ea-9d35-e6eec198da60.png">
- the "back to top" arrow on mobile doesn't appear for this page.  It works fine for 2018 and 2017.

**Comment by thetwopct** [comment]
1. Done
2. Ha "The current site" depends on what browser you use to view it... So I've re-made the whole section to match the PDF instead.
3. 4. 5. 6. Done.

**Comment by cjyabraham** [comment]
I think [these headings](https://dev-cncfci.pantheonsite.io/cncf-annual-report-2019/) are too big:
<img width="1357" alt="Screen Shot 2020-08-28 at 8 14 28 PM" src="https://user-images.githubusercontent.com/463160/91559711-27febd80-e96b-11ea-967c-ee75d317ce63.png">

**Comment by cjyabraham** [comment]
In fact I think something has gone wrong with the 2019 report.  The images are huge:
<img width="1372" alt="Screen Shot 2020-08-28 at 8 16 46 PM" src="https://user-images.githubusercontent.com/463160/91559883-6f854980-e96b-11ea-8257-93881edd8502.png">

**Comment by cjyabraham** [comment]
On the 2018 report, this text isn't readable:
<img width="1134" alt="Screen Shot 2020-08-28 at 8 19 52 PM" src="https://user-images.githubusercontent.com/463160/91560129-e28ec000-e96b-11ea-90a9-6afb365e6ac1.png">

**Comment by thetwopct** [comment]
Fixed images
Fixed text
Should be good now
