### ISSUE TITLE
Project journey design and migration

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#188]

**Comment by thetwopct** [comment]
There are all now moved across and also the PDF downloads are linked.

I've renamed them slightly in the menu - as they are inside a sub-menu calling them Project Journey Reports, I felt repeating the same thing again in full wasn't really needed, and it caused line wrapping, so I removed the word "Report" from the sub-menu to make it look neater.

![20200818155757-Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/90529405-97a2ca80-e16b-11ea-9d79-632eb3b25961.jpg)

**Comment by cjyabraham** [comment]
Do you think the quotes at the bottom of [this one](https://dev-cncfci.pantheonsite.io/cncf-prometheus-project-journey/) should be narrower to match the margins of paragraphs above?

**Comment by thetwopct** [comment]
I didn't think it looked good with the quote being larger as the quote is very long. 

The quotes have 3 different block styles to be applied. If you want to play around with it, feel free, or maybe we let the editors decide. I am happy with the current layouts of all the reports as they are right now.
