### ISSUE TITLE
Assign featured images for News posts

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#201]
The [In the News listing](https://dev-cncfci.pantheonsite.io/news/) has a thumbnail image for the logo of the news source.  Find logos, preferably in SVG format, to assign to the latest 10 or 20 news items.  The logos can be re-used for new items from the same source.  Suffix the name of the file with “-newslogo” so that, in the future, logos can easily be searched and re-used in the Media Library.  Jessie had previously started on this task.  Images can temporarily be stored [here](https://drive.google.com/drive/folders/1gnwEM9DP4XXy7sN-VsiQ6TYwKi6oVOuc) for me to upload to the site on the final migration.

**Comment by thetwopct** [comment]
I've gone back for a few pages and added all the logos. I've add new/revised logos to the drive too so there is a repository of them should it be needed.
