### ISSUE TITLE
What's the best way to style the image at the bottom of this page?

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#202]
https://dev-cncfci.pantheonsite.io/projects/

I can't make it go larger unless I set it full-width.
<img width="1248" alt="Screen Shot 2020-07-12 at 4 26 10 PM" src="https://user-images.githubusercontent.com/463160/87242125-6d6b3800-c45c-11ea-9356-545c37eac0e3.png">

**Comment by thetwopct** [comment]
I think possibly connected to https://github.com/lfph/lfph.io/issues/19 

But short-term, when you insert the SVG in the editor it will appear tiny (100px wide) but if you save the post, it will automatically insert at 100% width of container on the frontend.

**Comment by cjyabraham** [comment]
LGTM
