### ISSUE TITLE
Improve CTA and text on End User Community

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#203]
https://dev-cncfci.pantheonsite.io/people/end-user-community/

**Comment by thetwopct** [comment]
Done. I wonder if the join section of this page needs to update like the [Join](https://dev-cncfci.pantheonsite.io/about/join/) page?

**Comment by cjyabraham** [comment]
I think the CTA section is lacking the clarity of [what we currently have on the site](https://www.cncf.io/people/end-user-community/).  I think it'd be fine to follow the pattern we established for this section in the Join page.  

Also, I think the spacing and design of this section needs improving:
<img width="1204" alt="Screen Shot 2020-07-15 at 11 12 56 AM" src="https://user-images.githubusercontent.com/463160/87499182-2d8a9780-c68c-11ea-9434-f7d7a7283a36.png">

**Comment by thetwopct** [comment]
What design improvements do you want to implement? The current design of the 1,2,3 boxes is pretty poor as it took me a long time to realise the (3) for Supporter was greyed out, so not sure if a user will see that either. But this is an existing graphic. I've tightened the text spacing for each option, it doesn't look good to me.

Regarding CTA:

- There is no clear CTA, as the section from your screenshot is linked to joining details, as is the Join section directly underneath it. This is exactly how the current site is. 
- It's repeating information in two areas and then dumps a user straight in to the sign up forms. 
- The End User Member section doesn't explain anything about the Silver, Gold, Platinum levels or price ranges (this is all on Join page).
- Free tickets to Kubecon is already mentioned in the list of benefits above this section, so why repeat just that in the CTA part?
- It needs overall content improvement and refinement.

**Comment by cjyabraham** [comment]
Refiling as an idea for "content" improvement post-launch.

**Comment by cjyabraham** [comment]
Closing in favor of #224
