### ISSUE TITLE
Contact form field borders look too bold

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#207]
The field borders look too bold now [here](https://dev-cncfci.pantheonsite.io/about/contact/).  Did that change recently?  Could we make them look like those on the [speakers bureau contact form](https://dev-cncfci.pantheonsite.io/speaker/puja/)?

<img width="766" alt="Screen Shot 2020-07-14 at 5 32 23 PM" src="https://user-images.githubusercontent.com/463160/87409879-2c0f8f80-c5f8-11ea-879b-6b9b294e5548.png">

**Comment by thetwopct** [comment]
Yep it changed, iOS was adding some weird styling and turning that off reverted the forms borders to default styling. Fixed now.
