### ISSUE TITLE
Some projects missing external icon in the menu

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#208]
Any idea why these are missing the external icon?
<img width="733" alt="Screen Shot 2020-07-14 at 5 49 33 PM" src="https://user-images.githubusercontent.com/463160/87411528-6aa64980-c5fa-11ea-823f-cb1da19af8ae.png">

**Comment by thetwopct** [comment]
Have reverted some of the code here, the links without the icon are http not https
