### ISSUE TITLE
Write proposal for front-end work

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#21]
Give @dankohn and I a brief outline (2 or 3 paragraphs) of how you are approaching the front-end html/css/js work.  What framework(s) will you use?  How will you compile/minify assets?  Any other technical aspects that are worth pointing out? Fonts?

**Comment by thetwopct** [comment]
Added **CNCF Frontend / WordPress project overview** to CNCF Rebuild folder in shared Google Docs. Will add more things to it as they come up so document can perhaps be utilised for future projects.
