### ISSUE TITLE
Mobile menu close button is sometimes too close to menu

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#212]
Cheryl reported this.  I have asked her what phone she was on:
![File](https://user-images.githubusercontent.com/463160/87619077-e49b1780-c74d-11ea-8403-55ab517e4ebd.jpg)

**Comment by oicheryl** [comment]
The iPhone SE 2020

**Comment by cjyabraham** [comment]
this doesn't seem fixed on dev:
<img width="320" alt="Screen Shot 2020-07-17 at 4 13 46 PM" src="https://user-images.githubusercontent.com/463160/87764178-8c950b80-c848-11ea-823a-8b0af5645aba.png">

**Comment by thetwopct** [comment]
Whoops, looks like I've added in padding but aligned it only to the arrows and not the pop out menu part. Should be fixed now.
