### ISSUE TITLE
Refactor Case Studies tiles

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#213]
With feedback from Julie, we'd like to do the following:
1. Make the date a bit less prominent, perhaps by making it a bit smaller.
2. Remove the industry flags to help reduce the clutter on the tile.
3. Create two new project meta values to designate a primary and a secondary project for the case study.  The editor will choose from a list of projects.  These will be shown on the tile.  If neither are set then none are shown(?).

Something like this:
<img width="676" alt="Screen Shot 2020-07-16 at 1 54 36 PM" src="https://user-images.githubusercontent.com/463160/87632397-eb388780-c76b-11ea-91fd-b994ea4fe455.png">

Julie can you confirm this spec?

**Comment by thetwopct** [comment]
I've refactored these; stripped out industry, removed date from home page (as they are in latest order anyway), and added new field to case study meta so Editor can override with 2 projects if so desired.
