### ISSUE TITLE
Consider other colors for Projects social icons

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#215]
Feedback from @alexcontini :

> [Projects page](https://dev-cncfci.pantheonsite.io/projects/) - I think all the pink text headers and icon buttons in the pink is a bit distracting, my eye goes directly to all the pink on the page instead of the logos, I also think the color doesn’t look great beside some of the logo colors. I know this is because they are links, but is there any way to possibly change to grey, black, or even the navy blue used for headers in other parts of the site? I think the icons could be left pink

**Comment by thetwopct** [comment]
I'm not sure if I agree. There is also the content rule that links are pink, so breaking that just for this page doesn't feel quite right. 

Let's move to a content decision and see if anyone mentions it being an issue?

**Comment by cjyabraham** [comment]
Closing this but can re-open if we hear this feedback from anyone else.

**Comment by thetwopct** [comment]
I still don't agree at all. 

Anyway. 

I've made the project titles black (what other colour can they possibly be?) - hopefully users know they are links (guessing the page objective is for a user to click through and explore the projects? Does this decision align with that objective? No it does not)

I made the icons black - they don't look great and stand out on the page more than the pink IMO.

![20200827220945-Graduated and incubating projects | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/91495153-05f53480-e8b2-11ea-9c4f-e3bc2ded2aec.jpg)

Matching the footer icons just looks weird on a white background IMO, but that's what is live

![20200827221132-Graduated and incubating projects | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/91495290-45bc1c00-e8b2-11ea-8020-2a0260e4ab41.jpg)

**Comment by cjyabraham** [comment]
I don't like the black project titles.  In my comment [I only spoke of muting the social icons](https://github.com/cncf/cncf.io/issues/215#issuecomment-678726338) so they weren't so loud and more consistent with other social icons across the site.  I like what you've done with them here but could we return the headings to pink as they were?

**Comment by cjyabraham** [comment]
On another note, I wonder if it would make sense to list CNCF projects using logos with their names embedded, [as we do on LFPH](https://www.lfph.io/join/projects/).  That would alleviate Alex's initial point that the pink project names do sometimes clash and compete with the project logo colors:
<img width="228" alt="Screen Shot 2020-08-28 at 1 07 55 PM" src="https://user-images.githubusercontent.com/463160/91523514-81e19200-e92f-11ea-8ba2-5f908a006eea.png">

@dankohn any thoughts?

**Comment by thetwopct** [comment]
When the logo + text of the project is included in the image, the logos become unbalanced; I don't think this is an elegant solution. The names underneath as text is easy to read, easy to copy, consistently spaced.

![20200828113614-Photopea | Online Photo Editor](https://user-images.githubusercontent.com/10615884/91551800-b00ca500-e922-11ea-946c-0c91a0c5cc8e.jpg)

**Comment by cjyabraham** [comment]
On the Events site we apply a sizing adjustment index to sponsor logos so that we can fine-tune how large they appear relative to each other and make for a more balanced display.  We could do something similar here if we decide to go this route.  I agree, however, with the other cons @thetwopct mentioned wrt this approach.

**Comment by caniszczyk** [comment]
I'm fine with the black icons

We could also consider having a in depth page with for each project that lists all the social icons and more details

Another idea could be to expand the landscape to include this info and then honestly just embed the landscape to list the projects

**Comment by cjyabraham** [comment]
@caniszczyk as for an in-depth page, we have plans to create [project-specific landing pages](https://github.com/cncf/cncf.io/issues/81) now that we have created so much content that is tagged by project.
