### ISSUE TITLE
X icon starts dim then becomes bold on submenu expansion

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#216]
I'm noticing for the first time that when you open the mobile menu the X icon is rather dim pink:
<img width="28" alt="Screen Shot 2020-07-18 at 8 43 44 AM" src="https://user-images.githubusercontent.com/463160/87840549-d32f4800-c8d2-11ea-96cc-29cf3a850bf6.png">

But after interacting with any of the submenus, it becomes brighter:
<img width="34" alt="Screen Shot 2020-07-18 at 8 43 52 AM" src="https://user-images.githubusercontent.com/463160/87840558-dcb8b000-c8d2-11ea-9e1b-26851a2e2d03.png">

Is this a recent and intentional change?  I'm not sure I understand the reasoning for it.

**Comment by thetwopct** [comment]
It's a hover state

**Comment by cjyabraham** [comment]
I don't understand why we need a hover state on a mobile menu.  Additionally, it doesn't seem to correspond with hovering my mouse, but rather simply changes color when I open a submenu.  I think it'd be better to stay with the bolder pink throughout?

**Comment by thetwopct** [comment]
Not all viewers of the mobile site will be on a touch device. So mobile users will never see the colour change. Desktop users will see it when they scroll over it, like all our buttons change slightly on hover.

If it bothers you that much I will kill it.

**Comment by cjyabraham** [comment]
Ok, I think there's a problem then because on my mobile device I see the color change when I open a submenu.  It's dim to start and then becomes bold when I open a menu.  I think that should be fixed to be bold throughout.  I don't mind keeping a hover state for other users not on a touch device.

**Comment by thetwopct** [comment]
When a user presses they are also hovering over it? Anyway, I removed it, so if you can still reproduce let me know.
