### ISSUE TITLE
Add Speakers to Webinar tile if Company is not present

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#218]
Currently we only show "Presented by" if a company is added to the webinar.

This can lead to empty space

![20200720184740-Webinars | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/87969200-970a0c00-cab9-11ea-9fa8-d3a077b85555.jpg)

So if Company is not present, perhaps we should display webinar speakers. This would help each listing look more consistent.

**Comment by cjyabraham** [comment]
Closing in favor of #229
