### ISSUE TITLE
Create a vscode settings file with code sniffs etc.

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#22]

**Comment by cjyabraham** [comment]
@thetwopct the only settings I have that are relevant are:
```
    "phpcs.standard": "WordPress",
    "phpcs.executablePath": "/Users/cjyabraham/.composer/vendor/bin/phpcs",
```
But just creating a workspace settings file won't be enough.  You'll need to point your phpcs so that it knows where to find the WordPress settings.  

I'm hesitant to create a special workspace settings file for this one setting.  And I'd prefer to keep my vscode running on my global phpcs instance so that I know I'm using the same standard across all WP sites.  Can you just follow [these instructions](https://github.com/tommcfarlin/phpcs-wpcs-vscode) for now?  If, in the future, we have other workspace-specific settings maybe we can revisit setting up a workspace-specific settings file.

**Comment by thetwopct** [comment]
This was bigger than just CS, was to do with linting etc. Let's revisit if our code is being formatted differently and messing up git. But I will add some files to the repo to try and normalise all of that as I go.
