### ISSUE TITLE
Improve join page design

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#221]
From Katelin Ramer:

I have some comments regarding the about join page. https://dev-cncfci.pantheonsite.io/about/join/

1a) There is a lot of white space between each of the programs under Marketing, Thought Leadership, and Community Support. Can you make them smaller? 
1B) and the pictures seem too big for the text, I think they need to be a little smaller.
2A). The table of contents, can you make the numbers match the color of the rest and make it a little bigger? It doesn’t seem to match. 
2B) I also think there should be a picture or something to the right to take up the white space or add something around that section to frame it.
3. In the Why join? can we have the bullets be bold or something to pop from the text around it?
4. For the chart showing the membership levels - what does it look like horizontal? feels like it’s very crowded in vertical style
5. End User Community - I think we should change this to keep the intro paragraph and then cut the rest of the details and redirect people to the https://dev-cncfci.pantheonsite.io/people/end-user-community/ to learn more.
6. Membership pricing - can we put the cncf annual fees and the silver fee scale side by side?
7. Join section at the bottom - please cut the second bullet with the member benefits guide.

**Comment by thetwopct** [comment]
1a) Not done - Spacing matches all other pages, suits the amount of text on the page. Reducing space makes it look cluttered. 

1b) Not done - Images match the height of the text. If they are smaller, it will look consistently strange.

2a) Holding - The table of contents numbers is text, the items are links. Not all ordered lists will be nav elements. I can create a style just for nav lists, but as the sections themselves are not labelled 1) 2) 3) etc, clicking 2) but then not seeing corresponding 2) in the body does not make sense to me. Any thoughts?

2b) Holding - If there is a suitable image to use in the "white space" then lets add it, but I think this needs to be done to various parts of the site to be consistent. Only having it on this page is seeing this page in isolation, and that will not make a cohesive website.

3) Done - added bold to the list.

4) Holding - It doesn't look good horizontally. I am not sure of an elegant solution to make it look less cluttered and still have it be easily comparable by the user - without at least attempting to edit some of the text. The amount of text is the issue.

5) Done - This certainly removes some of the text from this section and make it easier to digest.

6) Not done - They don't fit in the page boundaries.

7) Done.

**Comment by cjyabraham** [comment]
@kwussow Any further thoughts on this before we close it?  For more of the background of our new style patterns, [this doc might be helpful](https://docs.google.com/document/d/1TmjvB4MAFEFtYKLhMPuWl_J1guaXdHZh5d2BTQhe4wE/edit#heading=h.qospxarh9t45).

**Comment by kwussow** [comment]
Could the pink button at the bottom say something like "become a member"
vs. just join CNCF?
Other than this, I don't have any other comments.

*Katelin W Ramer*
Business Development Manager - Cloud Native Computing Foundation
Location & Time-zone: Denver, CO MST
phone:  303-710-5701 <3037105701>
web: https://www.cncf.io/
email:  kramer@linuxfoundation.org
schedule a meeting with me: www.calendly.com/kwramer

**Comment by thetwopct** [comment]
Button has been [updated](https://dev-cncfci.pantheonsite.io/about/join/) 👍
