### ISSUE TITLE
Improve copy on End User Community page

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#224]
Some issues with [the page](https://www.cncf.io/people/end-user-community/) currently:
- users are directed [off the page](https://www.cncf.io/wp-content/uploads/2019/08/cncf-end-user-benefits-2.pdf) to get the full information on benefits
- it refers to Silver, Gold and Platinum levels but there's no further explanation or links to what those mean
- free tickets to Kubecon is mentioned twice
- there are two CTA sections that don't really work together (one that says "Choose your membership level" and the other that says "Become a member"); perhaps they should be consolidated?
- icon 3 is greyed out under "End User Supporter" but it's not clear what that means

**Comment by oicheryl** [comment]
@cjyabraham We've refreshed the benefits and I would like to jettison most of the content in favor of this table layout instead. WDYT?

https://docs.google.com/document/d/12EmKLFTBz8iuVipr5bJEyNPQphBmWHmaYqiYrKBuR70/edit

**Comment by cjyabraham** [comment]
Sounds good.  It's very clear to understand what you get in each level this way.  I wonder if we can style it somewhat so it's a bit more engaging.  In the [new topnav design](https://docs.google.com/spreadsheets/d/1Bg5x7mC0ZsWgKbLZSs5eRJR_mNiEdmQD7X-guGcREKM/edit#gid=2073154919) I've taken out the landscape embed into its own "End User Listing" page so that the "Join as End User" page can be more focused.

**Comment by cjyabraham** [comment]
This is now being worked on as part of the new [end user hub project](https://xd.adobe.com/view/fea38f40-563f-4f36-8bae-e225af7fbbc4-abf0/screen/3485c625-b2d0-4030-99ec-d4b8cb23c529).
