### ISSUE TITLE
Have language choice on newsletter signup

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#225]
Request from Dan:

Have a language option on the [newsletter form](https://dev-cncfci.pantheonsite.io/#newsletter) to allow people to subscribe to the Chinese mailing list (with a description in Chinese).

**Comment by cjyabraham** [comment]
[I've submitted the request to DMO](https://jira.linuxfoundation.org/browse/DMO-352)

**Comment by cjyabraham** [comment]
@thetwopct , there is now a new form handler to capture language for the newsletter.  Can you find a way to implement this into the newsletter form (use field name="language") ?  Then I can test the submissions within SFMC.

**Comment by cjyabraham** [comment]
I've added the language field so that Pratik can start testing.  @thetwopct I leave it for you to style.

**Comment by cjyabraham** [comment]
Can you get the fields on the same line.  The language field looks lower:
<img width="825" alt="Screen Shot 2020-08-14 at 5 36 04 PM" src="https://user-images.githubusercontent.com/463160/90235957-b136d000-de54-11ea-97f4-9b329831647c.png">

**Comment by thetwopct** [comment]
Which browser?

Chrome, Firefox, Safari all look the same to me

![20200814105253-Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/90237539-55505500-de1c-11ea-85fc-683cfb0f0cd6.jpg)
(Chrome)

**Comment by thetwopct** [comment]
Oh, weird. It's on large screens only, resolution related, will fix now.

**Comment by cjyabraham** [comment]
Your screenshot, to me, makes it looks slightly higher.  This is how mine looks as well when my browser width is narrower.  On a wider browser width is shows lower.  This is on Chrome and Safari.

**Comment by cjyabraham** [comment]
Could we get the button on the same line?  Similar to on lfph.io?  We have "Organization" there, which is larger even than "English".

**Comment by thetwopct** [comment]
I do find LFPH a little squashed. But lets give it a go. Lukes original design was always dropping the submit to a new line.
