### ISSUE TITLE
Should Project Journeys have a published date on them?

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#228]
As they are a snapshot in time, it seems strange they don't have a published date visible on them. Should this be added?

**Comment by cjyabraham** [comment]
@KimMcMahon ?

**Comment by KimMcMahon** [comment]
I agree with @thetwopct - they should have a date. Thanks for flagging!

**Comment by thetwopct** [comment]
Have added a month + year to the intro of each 👍
