### ISSUE TITLE
Online Programs box, add Presenter if there is no Host set

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#229]
To make the display of webinars more consistent, we could add the presenters of the webinars if there is no host set.

Current
![20200815002906-Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/90299553-6174fa80-de8e-11ea-86f9-e2b49e7294a6.jpg)

Suggested

![20200815003130-Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/90299623-ab5de080-de8e-11ea-9500-de652f226a7e.jpg)

May also need to refine language used - a webinar can be presented/hosted by a company, or presented/hosted by X person. Need to be consistent.

**Comment by cjyabraham** [comment]
@KimMcMahon any thoughts?

**Comment by KimMcMahon** [comment]
Agree on the Hosted and Presented language as suggested.

All Member webinars should be "hosted". The only webinars "presented by" are the Ambassador webinars.

What do you suggest for Project webinars? Hosted by the Project?

And what is the solution if there are multiple speakers? Only one name will be shown on the tile.

**Comment by cjyabraham** [comment]
This is a good idea for the current redesign effort @thetwopct

**Comment by thetwopct** [comment]
Doesn't look like we pull in the "speaker" values from Bevy (here is a [talk](https://community.cncf.io/events/details/cncf-cncf-online-programs-presents-cncf-on-demand-webinar-data-swirling-to-the-rescue-for-true-observability/), and the imported [post](https://www.cncf.io/wp/wp-admin/post.php?post=71542&action=edit) has no speakers). If its possible to get speaker value imported we can display that if a company/host is not listed.

**Comment by thetwopct** [comment]
Now we have moved to Bevy this is no longer relevant.
