### ISSUE TITLE
svg autocrop failed: Failed to autocrop within 20 seconds

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#230]
Was loading one of the data images in to Project Journey - a 800kb SVG.

Kept getting the error:

`svg autocrop failed: Failed to autocrop within 20 seconds`

Guessing it's a timeout, but I had to deactivate to get the upload working.

**Comment by cjyabraham** [comment]
Yes, we do run into this occasionally for complex SVGs.  I think it would be better if the SVG still uploads even though the processing fails.

**Comment by cjyabraham** [comment]
[I've allow the upload to proceed even when the autocrop operation fails](https://github.com/cncf/wp-svg-autocrop/commit/eb218c3392ea0533ab8de267d181f0171f852993)
