### ISSUE TITLE
Make the description box wider when editing the UM profile

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#236]
[See here](https://cncfci.lndo.site/speaker/puja/?um_action=edit):
<img width="1166" alt="Screen Shot 2020-08-16 at 4 57 13 PM" src="https://user-images.githubusercontent.com/463160/90330733-c3924480-dfe1-11ea-9bd4-609cc3595452.png">

**Comment by thetwopct** [comment]
Fixed 

![20200819011153-Chris Abraham | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/90577497-f8a4bf80-e1b8-11ea-8c01-30ebc763545f.jpg)

**Comment by cjyabraham** [comment]
When I go to [my profile](https://dev-cncfci.pantheonsite.io/speaker/cabraham/?um_action=edit) it's still small for me?

**Comment by thetwopct** [comment]
Cannot reproduce on Chrome or Safari. Have you tried clearing your cache?

Chrome:
![20200819091812-Chris Abraham | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/90610175-f5cbbe00-e1fc-11ea-8317-b1c8e4c96b3c.jpg)

**Comment by thetwopct** [comment]
Fixed for all users
