### ISSUE TITLE
Make button styles consistent on UM edit profile page

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#237]
Can we remove the shadow from the "Cancel" button in order to make the button styles consistent [here](https://cncfci.lndo.site/speaker/puja/?um_action=edit)?  This also needs to be done on the [login page buttons](https://dev-cncfci.pantheonsite.io/speakers/login/).
<img width="674" alt="Screen Shot 2020-08-16 at 4 59 52 PM 1" src="https://user-images.githubusercontent.com/463160/90330778-0ce29400-dfe2-11ea-9046-55d3f2a706c4.png">

**Comment by thetwopct** [comment]
Fixed 

Edit Profile:

![20200819010743-Chris Abraham | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/90577288-63093000-e1b8-11ea-8130-704aadbcdfa3.jpg)

Login:

![20200819010817-CNCF Speakers Bureau: Login | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/90577318-787e5a00-e1b8-11ea-8bec-d97031b2a098.jpg)

Reset password:

![20200819011104-CNCF Speakers Bureau: Password reset | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/90577451-dad75a80-e1b8-11ea-8f32-29ba9ca0bdeb.jpg)

**Comment by cjyabraham** [comment]
Can you stop the secondary buttons from having their text color change on hover?  This makes their animation a lot more noticeable than that of the primary buttons so looks a bit off.
