### ISSUE TITLE
Fix alignment on speakers bureau edit dropdown

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#241]
The dropdown should line up with the cog:
<img width="578" alt="Screen Shot 2020-08-17 at 10 07 06 AM" src="https://user-images.githubusercontent.com/463160/90351013-7e1d5800-e071-11ea-9685-8ba7519c290d.png">

**Comment by thetwopct** [comment]
Fixed

![20200819010709-Chris Abraham | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/90577263-4ff66000-e1b8-11ea-8bee-3ae48b2ea050.jpg)
