### ISSUE TITLE
Hero image not correct size on mobile

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#242]
for [Sandbox projects](https://dev-cncfci.pantheonsite.io/sandbox-projects/).  Maybe thumbnails just need regenerating?
<img width="356" alt="Screen Shot 2020-08-17 at 12 37 16 PM" src="https://user-images.githubusercontent.com/463160/90357708-7b792d80-e086-11ea-8702-9e89c0dae8f4.png">

**Comment by thetwopct** [comment]
Looks like the regenerate fixed it
