### ISSUE TITLE
Logos in the career section are too big on mobile

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#246]
Can we make these smaller on mobile:
<img width="344" alt="Screen Shot 2020-08-17 at 3 01 06 PM" src="https://user-images.githubusercontent.com/463160/90366904-83db6380-e09a-11ea-9b69-d3378bc78155.png">
<img width="341" alt="Screen Shot 2020-08-17 at 3 01 13 PM" src="https://user-images.githubusercontent.com/463160/90366909-86d65400-e09a-11ea-8eca-3e4523fb99e5.png">

**Comment by thetwopct** [comment]
Both sets of logos updated to be one image
