### ISSUE TITLE
Speakers Bureau submit button incorrectly formatted on mobile

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#247]
Speakers bureau contact form submit button doesn't look right on mobile.  The text isn't centered in the button vertically.
<img width="348" alt="Screen Shot 2020-08-17 at 3 06 11 PM" src="https://user-images.githubusercontent.com/463160/90367300-47f4ce00-e09b-11ea-9288-8d36ff50a0f3.png">

**Comment by thetwopct** [comment]
Fixed: 

![20200819010648-Chris Abraham | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/90577243-43720780-e1b8-11ea-97c0-d5c3d5f9ad5b.jpg)
