### ISSUE TITLE
Make spacing consistent throughout main pages of site

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#250]
Some pages, like the homepage, look too cramped, especially on mobile.  Others look fine.  Do a pass through all main pages to make the spacing consistent on desktop and mobile.

Notes:
- I think the project journeys could use some extra space above each large heading

**Comment by thetwopct** [comment]
I've done a pass of the pages, I've added more space to the home page especially. I think the difference between CNCF and LFPH is that LFPH has the stripey effect on the home page which effectively doubles the amount of space used between sections. While this is good for white space and letting elements breath, it does look pretty stripey/weird, so if we can avoid that on CNCF that would be nice!

**Comment by cjyabraham** [comment]
Looks good for now.
