### ISSUE TITLE
Add space around checkbox on contact form

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#252]
The checkbox on the [contact form](https://dev-cncfci.pantheonsite.io/about/contact/) needs some space before the text:
<img width="379" alt="Screen Shot 2020-08-18 at 12 36 54 PM" src="https://user-images.githubusercontent.com/463160/90471034-a1b6d000-e14f-11ea-9f1b-4356cdc0f2f0.png">

**Comment by thetwopct** [comment]
Looks like I haven't copied across the new styles from LFPH
