### ISSUE TITLE
Stretch the speaker images the same way you do for people on mobile

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#253]
On mobile, the [people images](https://dev-cncfci.pantheonsite.io/people/staff/) stretch to fill the width of the box:
<img width="348" alt="Screen Shot 2020-08-19 at 11 30 02 AM" src="https://user-images.githubusercontent.com/463160/90588895-56fc8d00-e20f-11ea-904d-a88f76826cf0.png">

Can we do this for speakers as well?
<img width="344" alt="Screen Shot 2020-08-19 at 11 30 21 AM" src="https://user-images.githubusercontent.com/463160/90588914-624fb880-e20f-11ea-9e6b-44249f01b20c.png">

**Comment by thetwopct** [comment]
UM only allows for a 190px image OR full size image. Full size image can be 1MB+, so sticking with 190px. As it is because of the grid column sizes, this is only an issue around 500px device width, so I think close this for now, and perhaps look at UM replacements.
