### ISSUE TITLE
Add logos or design patterns to homepage "Become a Member" area

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#256]
Consider ways to add sponsor logos or some kind of design pattern to the homepage, especially around the "Become a CNCF member" section.  @thetwopct idea: have a diagonal raining of sponsor logos in the background for this section.

**Comment by thetwopct** [comment]
A few quick mockups

Kubecon imagery

![8*) *](https://user-images.githubusercontent.com/10615884/90649597-d0f23d80-e232-11ea-8a42-d222124605d9.jpg)

![8*) *](https://user-images.githubusercontent.com/10615884/90649347-840e6700-e232-11ea-9a46-01a234158855.jpg)

Platinum Member logos 

![8*) *](https://user-images.githubusercontent.com/10615884/90652277-cb4a2700-e235-11ea-9c97-32d0edcd42c0.jpg)

**Comment by cjyabraham** [comment]
I think these are great.  I like the first option maybe the best.  I'm not sure the implications of showing the logos you've chosen in the 3rd option and not others.  Are these going to work well on mobile?  Or would you just hide that image for small viewports?

@dankohn @KimMcMahon @oicheryl @alexcontini any thoughts on the above options for adding a bit more color to the new CNCF homepage?

**Comment by thetwopct** [comment]
I used Become a Member section as a template for the design mockup, but I would like to add something to both the Become a Member and End-User Community sections to make them consistent.

On mobile, I think they would either disappear, or turn in to thinner strips at bottom/top/both. Would depend on the designs chosen.

**Comment by cjyabraham** [comment]
Not relevant now since we are working on new homepage designs.
