### ISSUE TITLE
Image thumbnails have variable height

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#257]
I thought regenerating thumbnails would fix this but it doesn't seem to have done.  The thumbnails on the homepage are of varying heights:
<img width="750" alt="Screen Shot 2020-08-20 at 1 49 40 PM" src="https://user-images.githubusercontent.com/463160/90721869-4c63f580-e2ec-11ea-9412-d6bb2ff8f48c.png">

**Comment by thetwopct** [comment]
Weird, should be the same as LFPH. Maybe its the default image. I'll investigate.

**Comment by thetwopct** [comment]
Default image needed updating to reflect different image thumbnail ratio

![20200820221815-Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/90826870-172ec600-e333-11ea-8b70-09f822597d47.jpg)
