### ISSUE TITLE
LF | Hero preview doesn't work in block selector

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#259]
The block selector seems to crash every time I hover over "LF | Hero".  There's no way to choose the block using the selector because of this.  [See the vid](https://drive.google.com/file/d/1id0rRMItOU1iX0r-L2GRIJHc6wqqJJGW/view?usp=sharing).

**Comment by thetwopct** [comment]
Can reproduce in Chrome. Cannot reproduce in Safari. Also happens on hovering over Case Study Overview block. Is happening too on LFPH for same blocks. There are warning messages generated in console, but not errors, but these warnings appear for many blocks (when using Chrome).

![post php?post=8050 action=edit](https://user-images.githubusercontent.com/10615884/90990857-a2f75b00-e59c-11ea-89bc-a1b090f2daa0.jpg)

To investigate:
LF | Hero
LF | Case Study Overview

**Comment by thetwopct** [comment]
I've update both blocks and for now turned off their default example/preview. This seems to have fixed it for me locally in Chrome. Can you can confirm?

**Comment by cjyabraham** [comment]
LGTM.  Thanks.  I think we can live without previews.
