### ISSUE TITLE
Consider a different layout for the Projects page

### ISSUE THREAD

**Issue by yurishkuro** [cncf/cncf.io#26]
I understand the desire to explain the "maturity levels", but if feels quite odd that the actual graduated projects are **below the fold** on this page. The page feels more like and ad for Crossing the Chasm book. Below is how it looks on my screen. 

![image](https://user-images.githubusercontent.com/3523016/71786115-16c90100-2fd6-11ea-82e7-041cf1fc6866.png)

**Comment by yurishkuro** [comment]
cc @caniszczyk

**Comment by dankohn** [comment]
Fair point. I think we can at least tighten up the spacing.

**Comment by yurishkuro** [comment]
Maybe those graphics could be stashed into a collapsible [read more...] section.

**Comment by cjyabraham** [comment]
We could possibly put those graphics lower on the page in the "Maturity Levels" section and title the page "Graduated and Incubating Projects" to match the topnav menu title.

cc @thetwopct

**Comment by cjyabraham** [comment]
Closing in favor of #193 which should take care of the concerns presented here.
