### ISSUE TITLE
Show accepted dates for projects

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#261]
@caniszczyk would like us to expose the project "accepted dates" in the projects listings.  It can be subtle, such as a tooltip on hover, or a muted label somewhere.

**Comment by cjyabraham** [comment]
More ideas on the topic:

Kim McMahon  10:11 PM
If I can jump in with one of my last opinions for @caniszczyk consideration. Continuing to leave the projects in order of entrance to CNCF seems to give preference and more awareness to the projects that joined first. It also keeps the CNCF focus on K8s, which isn’t altogether bad, but tends to take away from the diversity of the ecosystem in the area of projects and breadth of technologies.
Changing the projects to alpha order will not only make the community happier because they can find things easier, but it will also give all projects an equal footing.
Can you consider please?


Chris Aniszczyk  10:37 PM
you have a point there @Kim McMahon, I think both options are "fair" but your suggestion is more fair, let's do it

10:37
it's a notable change too and reflects where we are going (edited) 


Kim McMahon  10:38 PM
mic drop (2 MB)
Posted using /giphy

10:38
Thanks @caniszczyk!

Chris Abraham  10:40 PM
Ok.  We can revert back to alpha.  Now that we have the Accepted Dates in the database, is that something we’d ever want to list along with the projects?
10:41
Or should we scrap it altogether?

Kim McMahon  10:41 PM
I like accepted dates. It shows the ‘founding’ projects.
10:41
^^^ My opinion.

Chris Aniszczyk  10:41 PM
I'd love to have a filter in place one day or just have it part of the label
10:42
you can keep it subtle with a hover or list the text somewhere

Kim McMahon  10:42 PM
^^^ like

Chris Abraham  10:42 PM
Ok, we’ll revert back to alpha for now and then prototype integrating the Accepted Date once we’re over the launch.
:+1:
1

**Comment by cjyabraham** [comment]
How about we add to the tooltip, like this:
<img width="1440" alt="Screen Shot 2020-09-21 at 2 46 15 PM" src="https://user-images.githubusercontent.com/463160/93738810-4a59c300-fc19-11ea-90c0-6d68bf2d53ff.png">

**Comment by cjyabraham** [comment]
@caniszczyk has okayed the above tooltip design.

**Comment by thetwopct** [comment]
I've added the dates in numerical American format, but to be consistent with other areas of the site I wonder if it should be in format like "July 16, 2020"?

**Comment by cjyabraham** [comment]
I feel that brevity (since it's a tooltip and sort of a power user feature) might be more important here than consistency, however, don't feel that strongly about it.

**Comment by cjyabraham** [comment]
deployed
