### ISSUE TITLE
Order projects by "accepted" date

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#262]
Projects should be ordered in the same way they are in the current site, by ["accepted" date](https://github.com/cncf/toc/blob/master/docs/projects.md#projects-table).  After launch, we may be creating [a filter ui for this](https://github.com/cncf/cncf.io/issues/261).

**Comment by cjyabraham** [comment]
I've added the meta field to the MU plugin.  I tried making the shortcode sort projects by the new date using this:
```
diff --git a/web/wp-content/themes/lf-theme/includes/shortcode-projects.php b/web/wp-content/themes/lf-theme/includes/shortcode-projects.php
index b1b773d..54a8b76 100644
--- a/web/wp-content/themes/lf-theme/includes/shortcode-projects.php
+++ b/web/wp-content/themes/lf-theme/includes/shortcode-projects.php
@@ -40,7 +40,8 @@ function add_projects_shortcode( $atts ) {
                                'terms'    => $chosen_taxonomy,
                        ),
                ),
-               'orderby'        => 'title',
+               'orderby'        => 'meta_value_datetime',
+               'meta_key'       => 'lf_project_date_accepted',
                'order'          => 'ASC',
        );
```

That did, however, break the rendering of the page.  Can you take a look @thetwopct.  Ideally those without a date set should be listed last.

**Comment by cjyabraham** [comment]
It has been decided to revert this back to alpha for now

**Comment by thetwopct** [comment]
I've reverted this back to alphabetical sorted by title
