### ISSUE TITLE
blog thumbnails are showing with different heights

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#263]
See on [the new-import instance](https://new-import-cncfci.pantheonsite.io/):
<img width="1001" alt="Screen Shot 2020-08-25 at 6 55 18 PM" src="https://user-images.githubusercontent.com/463160/91166239-a4dc2e00-e704-11ea-9a93-9b5b88df820f.png">

**Comment by thetwopct** [comment]
This is because the featured image is too small for the news thumbnail to be generated from it. Featured image should be a decent size, because its embedded in the OG/social posts etc. Social sites require a 1200x630 image. The blog only requires 540x285 minimums (same aspect ratio as 1200x630) which is still small, but this linked posts image is even smaller.

To fix this issue: 
1) I can change the default minimum size for featured image, but this will affect the responsive display of other images / reduce resolution for all other users/posts.
2) Just update small images as part of transfer process

Going forward: 
1) we can install a plugin like https://wordpress.org/plugins/minimum-featured-image-size/ 
2) include image present and size check  as part of pre-publish checklist.
3) I have also created a Photoshop template that blog authors can use to design their featured images - if they don't have Photoshop, they can upload the file to [PhotoPea](https://www.photopea.com) (online Photoshop copy) and export a JPG from there.

**Comment by cjyabraham** [comment]
I've noted the size requirements [here](https://docs.google.com/document/d/1TmjvB4MAFEFtYKLhMPuWl_J1guaXdHZh5d2BTQhe4wE/edit#heading=h.om784akkqwff) and on #200 .

**Comment by cjyabraham** [comment]
Refiling as post-deployment so we can be informed by real-world use.

**Comment by thetwopct** [comment]
I've updated the images after transfer as per https://github.com/cncf/cncf.io/issues/200 and the images are no longer different heights.

The issue may happen again if a small image is set as featured image. Currently the only way I can see to enforce a minimum size is to set minimum size requirements via Pre-publish checklists https://github.com/cncf/cncf.io/issues/277 - as that is the solution that can be easily implemented I am closing this issue now

**Comment by cjyabraham** [comment]
Someone has just uploaded a thumbnail that goes really large on the site.  Can you find a solution to this?
<img width="1158" alt="Screen Shot 2020-09-08 at 11 30 19 PM" src="https://user-images.githubusercontent.com/463160/92497204-9ecd6d80-f22b-11ea-8ebc-96799f8207e1.png">
<img width="1145" alt="Screen Shot 2020-09-08 at 11 30 31 PM" src="https://user-images.githubusercontent.com/463160/92497219-a3922180-f22b-11ea-9067-2516e71170d5.png">

**Comment by thetwopct** [comment]
`The issue may happen again if a small image is set as featured image. Currently the only way I can see to enforce a minimum size is to set minimum size requirements via Pre-publish checklists #277 - as that is the solution that can be easily implemented I am closing this issue now`

As per previous comment, these are the options. As you don’t want to use pre publish checklists for some reason, the only solution will be to make all news image default size much smaller so all image sizes are cropped.

**Comment by thetwopct** [comment]
Yah so in this instance its an SVG image - therefore that is not being cropped. 

The WordPress image editor does not have the ability to crop an SVG, it can only crop the dimensions of a raster (pixel image). A Scalable Vector Graphic is really just a text file describing the math that draws the image. 

Short term, I'm going to make it the right size and then upload as a PNG to fix this.

I can look at the way we handle SVGs as part of the blog image process, but as the chances of them ever being the correct dimensions (1200x630 or a ratio of that) are slim then SVGs are not suitable for blog featured images. Therefore monitoring the incorrect usage of SVGs as featured images would be ideally made part of the pre-publish checklist to check for 1) un-croppable SVGs and 2) incorrect image dimensions.

**Comment by cjyabraham** [comment]
We're trying to encourage editors to use SVGs as thumbnails for news posts.  SVGs will also make a lot of sense for announcements about particular projects.  It would be nice if we could be consistent in allowing SVGs for all posts regardless of category, but maybe this isn't possible.  I can see that the sizing rules of news post thumbnails are quite different and don't handle photos well, for example.  Is the rule we want to enforce then "SVGs, if possible, for news posts, JPG/PNGs of a minimum 1200x630px for every other type of post?"

I'm open to using pre-publish checklists, in general, but have been wanting to make sure we first exhaust technical approaches to solving problems and also make sure they're going to be useful enough to warrant their additional maintenance burden etc.

**Comment by thetwopct** [comment]
> I can see that the sizing rules of news post thumbnails are quite different and don't handle photos well, for example

Yah, so the News page has been made to handle logos (no cropping, constrained by height and width). If photos were used I don't think it will work so well. But it should and does (from what I have seen used to date) handle SVGs, JPGs, PNGs. So if you see issues, let me know what you find.

> I'm open to using pre-publish checklists, in general, but have been wanting to make sure we first exhaust technical approaches to solving problems and also make sure they're going to be useful enough to warrant their additional maintenance burden etc.

I see pre-publish checklists (p-pc) as a technical solution, and for the editor, if they don't agree with the feedback/guidelines given, they can always skip it. I've been working on the p-pc tonight, and I think I've come up with something that should give feedback depending on post category (i.e. accounting for news images) and giving feedback on size and filetype. Take a look and let me know your feedback.

**Comment by thetwopct** [comment]
Blocked - waiting on Pre-publish checklist solution

**Comment by cjyabraham** [comment]
With pre-publish checklists deployed, we're still seeing things like this:
<img width="1241" alt="Screen Shot 2020-10-08 at 8 34 48 AM" src="https://user-images.githubusercontent.com/463160/95402742-04a03880-0943-11eb-81d3-64fa6db8b729.png">

I'll give some more thought to other solutions...

**Comment by cjyabraham** [comment]
First time I'm seeing one that is actually too short:

<img width="1054" alt="Screen Shot 2020-10-27 at 11 25 19 AM" src="https://user-images.githubusercontent.com/463160/97253344-20fb0b00-1847-11eb-93ee-544620ecc427.png">

**Comment by cjyabraham** [comment]
@thetwopct as discussed, let's try to catch some of the most common cases where things look bad, such as when the image appears too tall on the homepage.  Let's also allow SVGs to be used.

**Comment by cjyabraham** [comment]
FYI the team is going to start using canva for thumbnail generation so this issue, while probably still worth doing, is less important since canva images will be sized correctly.

**Comment by cjyabraham** [comment]
Confirmed that this issue is now less important so, unless you've already started on it, we could move back to "Later".
