### ISSUE TITLE
Strange characters in imported blog posts

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#264]
[Example](https://new-import-cncfci.pantheonsite.io/blog/2020/08/20/understandability-what-is-it/)

![20200825141117-Edit Post ‹ Cloud Native Computing Foundation — WordPress](https://user-images.githubusercontent.com/10615884/91178321-e0fb9880-e6dc-11ea-9be5-330b691322b4.jpg)

Occurring on frontend and backend

**Comment by cjyabraham** [comment]
Thanks.  I've been making a list of things for Selly to check for on [this page here](https://docs.google.com/spreadsheets/d/1ufJUHCkt4cT_Ovdm3T7y8oRTvj69IEMI9cqJHDYSM6w/edit#gid=48867274).  I've noted down this url there as well.

**Comment by thetwopct** [comment]
Possibly another issue [here](https://dev-cncfci.pantheonsite.io/blog/2020/08/17/falco-update-whats-new-in-falco-0-25/) ?

`Guest post from Falco project maintainers Kris NÃ³va`

**Comment by cjyabraham** [comment]
Both these instances have been resolved, the first by my better import algo, the second during Selly's manual sweep.
