### ISSUE TITLE
Countup Gutenberg Block

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#27]
Write a Gutenberg block to be used for the countup facts section of the [cncf homepage](https://www.cncf.io/).  Make it configurable the way the current one is.  Also allow for no icon to be set. 
 Don't include the flip-on-hover animation on the icons.
<img width="1191" alt="Screen Shot 2020-01-19 at 11 54 02 AM" src="https://user-images.githubusercontent.com/463160/72675132-687f8a00-3ab2-11ea-87ec-b9224b0dd0f4.png">

Note: ~~Group this with other Gutenberg blocks in the same plugin so we can have all css/js in one file for the plugin and any other performance benefits.~~ Actually, please keep this as a separate plugin.

**Comment by rodmeurer** [comment]
@cjyabraham We created a separate plugin (lf-count-up-block), as requested in the issue. This is the PR link: https://github.com/cncf/cncf.io/pull/31

**Comment by cjyabraham** [comment]
Thanks.  [I setup a demo](https://pr-31-cncfci.pantheonsite.io/count-up-test/).  A few points:
- can you make it so that the count up only starts when the block enters the viewport, similar to how it is done on the [live site](https://www.cncf.io/), rather than it counting up offscreen?
- can you make all numbers start and end at the same time like the [live site](https://www.cncf.io/), rather than one waiting for the others?
- can you format the large numbers with comma separators like the [live site](https://www.cncf.io/)?

**Comment by rodmeurer** [comment]
Fixed @cjyabraham

**Comment by cjyabraham** [comment]
This is merged.  Thanks.
