### ISSUE TITLE
Make external link icons in footer same color as text

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#270]
It looks like they are white while the text is not:
<img width="212" alt="Screen Shot 2020-08-27 at 10 31 44 AM" src="https://user-images.githubusercontent.com/463160/91376821-926f0b00-e850-11ea-9cdd-00f6597ac86c.png">

**Comment by thetwopct** [comment]
Looks like an issue with Annual Reports css conflicting with the rest of the theme
