### ISSUE TITLE
Make sidebar placeholder values lighter grey in admin

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#271]
They look too dark and are too easily mistaken for a real value.
<img width="275" alt="Screen Shot 2020-08-27 at 10 45 06 AM" src="https://user-images.githubusercontent.com/463160/91378176-62c10280-e852-11ea-9934-4b7dff9938d2.png">

**Comment by cjyabraham** [comment]
@thetwopct did you write [this if statement](https://github.com/cncf/wp-mu-plugins/blob/master/lf-mu/admin/class-lf-mu-admin.php#L69)?  It is causing the admin css to no longer load and so [the style I wrote previously](https://github.com/cncf/wp-mu-plugins/blob/master/lf-mu/admin/css/lf-mu-admin.css#L6) isn't getting applied.  There may be other issues as well...

**Comment by thetwopct** [comment]
The if statement has been there since I made the global options page (6 months ago) as it loads the colour picker that is required on that page. The admin CSS referenced is also for that page. If you want to load something in the Editor / Admin you should put it in editor-only stylesheet.
