### ISSUE TITLE
Add featured image template to docs and let Jessie know

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#272]
Can you add that feature image template to the docs [around here](https://docs.google.com/document/d/1TmjvB4MAFEFtYKLhMPuWl_J1guaXdHZh5d2BTQhe4wE/edit#heading=h.om784akkqwff).  Once done, I'll let Jessie know, who is currently working on #200 .

**Comment by thetwopct** [comment]
OK I've added some information and a template file
