### ISSUE TITLE
FOUC on Speakers Bureau profile on mobile

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#274]
I see a pretty bad FOUC on [a SB profile](https://dev-cncfci.pantheonsite.io/speaker/puja/) when viewed on mobile.  The image of the person starts large and then goes small.

**Comment by thetwopct** [comment]
I can’t reproduce, can you take a video? 

I seem to recall the image is loaded/changed via JS via the UM code

**Comment by cjyabraham** [comment]
[Here's a vid](https://drive.google.com/file/d/1xR4AaIpevqktIF0l2sXQ7dqDN_FfhFz7/view?usp=sharing)

This is just a nice-to-have...

**Comment by thetwopct** [comment]
Is this on your phone or computer? What’s the white line down the left side?

**Comment by cjyabraham** [comment]
I captured the recording on my computer.  The white line is just because the recording frame is larger than the mobile frame, so nothing to worry about.  The FOUC was more pronounced on my phone, perhaps because I had a slower connection there.

**Comment by thetwopct** [comment]
I see something similar, it's not really FOUC. 

![Kapture 2020-08-27 at 22 41 43](https://user-images.githubusercontent.com/10615884/91497775-7e5df480-e8b6-11ea-9633-35e687299834.gif)

The image loads at 190px, but is displayed at 120px, and this is the transition. The whole page seems to load at once, some UM JS controlling it. Not sure how deep you want me to go to fix this, as currently we only style UM pages, we don't mess with the code at all.

**Comment by cjyabraham** [comment]
I've moved to Post-deployment and left as nice-to-have.  Perhaps this is better left until we excise Ultimate Member.

**Comment by cjyabraham** [comment]
SB is shutdown
