### ISSUE TITLE
Update page content

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#276]
Inspect what changes have occurred on pages on the live site and make sure we incorporate the relevant ones into our versions.  This was run on the live site db:

```
mysql> select ID, post_modified, guid from wp_posts where post_type='page' order by post_modified DESC;
+-------+---------------------+--------------------------------------------------------------+
| ID    | post_modified       | guid                                                         |
+-------+---------------------+--------------------------------------------------------------+
| 39942 | 2020-08-26 07:00:25 | https://www.cncf.io/?page_id=39942                           |
| 36914 | 2020-08-25 19:32:23 | https://www.cncf.io/?page_id=36914                           |
| 33273 | 2020-08-20 08:07:37 | https://www.cncf.io/?page_id=33273                           |
| 33545 | 2020-08-20 08:06:46 | https://www.cncf.io/?page_id=33545                           |
|  2314 | 2020-08-11 06:24:19 | https://www.cncf.io/?page_id=2314                            |
| 49815 | 2020-07-29 09:00:13 | https://www.cncf.io/?page_id=49815                           |
| 29219 | 2020-07-22 17:42:07 | https://www.cncf.io/?page_id=29219                           |
| 27434 | 2020-07-16 01:20:51 | https://dev-cncf.pantheonsite.io/?page_id=27434              |
| 48564 | 2020-05-28 10:15:05 | https://www.cncf.io/?page_id=48564                           |
| 27672 | 2020-05-28 08:03:29 | https://www.cncf.io/?page_id=27672                           |
|  2138 | 2020-05-28 08:02:10 | https://www.cncf.io/?page_id=2138                            |
|   167 | 2020-05-14 16:46:22 | http://cncf.wpengine.com/?page_id=167                        |
|  2338 | 2020-05-06 09:04:45 | https://www.cncf.io/?page_id=2338                            |
| 38374 | 2020-05-01 09:51:58 | https://www.cncf.io/?page_id=38374                           |
|   361 | 2020-04-24 19:22:08 | http://cncf.wpengine.com/?page_id=361                        |
| 47785 | 2020-04-20 13:41:13 | https://www.cncf.io/?page_id=47785                           |
| 24915 | 2020-04-15 00:10:48 | https://www.cncf.io/?page_id=24915                           |
| 29606 | 2020-04-10 05:36:10 | https://www.cncf.io/?page_id=29606                           |
| 38320 | 2020-04-09 09:59:16 | https://www.cncf.io/?page_id=38320                           |
| 34573 | 2020-03-24 05:47:21 | https://www.cncf.io/?page_id=34573                           |
| 35330 | 2020-03-24 05:46:47 | https://www.cncf.io/?page_id=35330                           |
| 32666 | 2020-03-24 05:46:29 | https://www.cncf.io/?page_id=32666                           |
| 32821 | 2020-03-24 05:46:00 | https://www.cncf.io/?page_id=32821                           |
| 32822 | 2020-03-24 05:45:35 | https://www.cncf.io/?page_id=32822                           |
| 35634 | 2020-03-24 05:44:38 | https://www.cncf.io/?page_id=35634                           |
| 35009 | 2020-03-24 05:43:54 | https://www.cncf.io/?page_id=35009                           |
| 35493 | 2020-03-24 05:43:17 | https://www.cncf.io/?page_id=35493                           |
| 35437 | 2020-03-24 05:42:46 | https://www.cncf.io/?page_id=35437                           |
| 35661 | 2020-03-24 05:39:15 | https://www.cncf.io/?page_id=35661                           |
| 35017 | 2020-03-24 05:38:51 | https://www.cncf.io/?page_id=35017                           |
| 38432 | 2020-03-24 05:38:33 | https://www.cncf.io/?page_id=38432                           |
| 37008 | 2020-03-24 05:38:01 | https://www.cncf.io/?page_id=37008                           |
```

**Comment by thetwopct** [comment]
39942 | 2020-08-26 07:00:25 | https://www.cncf.io/?page_id=39942 ✅ (KubeCon events - this has space at bottom of page about the next major event - I have used the August Kubecon information as a template, but this will need to be updated - or removed as the event listing  above it gives a link to the next events)
| 36914 | 2020-08-25 19:32:23 | https://www.cncf.io/?page_id=36914 ✅ (Services - a lot of small changes, I copied the entire thing again)
| 33273 | 2020-08-20 08:07:37 | https://www.cncf.io/?page_id=33273 ✅ (Projects - updated automatically now, project info seems to match)
| 33545 | 2020-08-20 08:06:46 | https://www.cncf.io/?page_id=33545 ✅ (Projects - updated automatically now, project info seems to match)
|  2314 | 2020-08-11 06:24:19 | https://www.cncf.io/?page_id=2314  ✅ (Training - I added a ToC)
| 49815 | 2020-07-29 09:00:13 | https://www.cncf.io/?page_id=49815 ✅ (New project report - Jaeger + added to menu)
| 29219 | 2020-07-22 17:42:07 | https://www.cncf.io/?page_id=29219 ✅ (Join - minor content changes)
| 27434 | 2020-07-16 01:20:51 | https://dev-cncf.pantheonsite.io/?page_id=27434 🚫 Doesnt exist
| 48564 | 2020-05-28 10:15:05 | https://www.cncf.io/?page_id=48564  ✅ (New project report - Helm + added to menu)
| 27672 | 2020-05-28 08:03:29 | https://www.cncf.io/?page_id=27672 ✅ CKAD
|  2138 | 2020-05-28 08:02:10 | https://www.cncf.io/?page_id=2138 ✅ CKA
|   167 | 2020-05-14 16:46:22 | http://cncf.wpengine.com/?page_id=167 🚫 Doesnt exist (WP Engine?)
|  2338 | 2020-05-06 09:04:45 | https://www.cncf.io/?page_id=2338 ✅ Calendar
| 38374 | 2020-05-01 09:51:58 | https://www.cncf.io/?page_id=38374 ✅ End User Community
|   361 | 2020-04-24 19:22:08 | http://cncf.wpengine.com/?page_id=361  🚫 Doesnt exist (WP Engine?)
| 47785 | 2020-04-20 13:41:13 | https://www.cncf.io/?page_id=47785 ✅ Fluentd project journey
| 24915 | 2020-04-15 00:10:48 | https://www.cncf.io/?page_id=24915 ✅ Software conformance 
| 29606 | 2020-04-10 05:36:10 | https://www.cncf.io/?page_id=29606 🚫 Marketing Committee
| 38320 | 2020-04-09 09:59:16 | https://www.cncf.io/?page_id=38320 ✅ Case Studies index
| 34573 | 2020-03-24 05:47:21 | https://www.cncf.io/?page_id=34573  🚫 Not found
| 35330 | 2020-03-24 05:46:47 | https://www.cncf.io/?page_id=35330 🚫 Not found
| 32666 | 2020-03-24 05:46:29 | https://www.cncf.io/?page_id=32666 🚫 Not found
| 32821 | 2020-03-24 05:46:00 | https://www.cncf.io/?page_id=32821🚫 Not found
| 32822 | 2020-03-24 05:45:35 | https://www.cncf.io/?page_id=32822🚫 Not found
| 35634 | 2020-03-24 05:44:38 | https://www.cncf.io/?page_id=35634🚫 Not found
| 35009 | 2020-03-24 05:43:54 | https://www.cncf.io/?page_id=35009🚫 Not found
| 35493 | 2020-03-24 05:43:17 | https://www.cncf.io/?page_id=35493🚫 Not found
| 35437 | 2020-03-24 05:42:46 | https://www.cncf.io/?page_id=35437🚫 Not found
| 35661 | 2020-03-24 05:39:15 | https://www.cncf.io/?page_id=35661🚫 Not found
| 35017 | 2020-03-24 05:38:51 | https://www.cncf.io/?page_id=35017 🚫 Not found
| 38432 | 2020-03-24 05:38:33 | https://www.cncf.io/?page_id=38432 🚫 Not found
| 37008 | 2020-03-24 05:38:01 | https://www.cncf.io/?page_id=37008  🚫 Not found

**Comment by cjyabraham** [comment]
I just ran the query again on the live site but no new pages have been updated so I think we're good here.  Thanks.
