### ISSUE TITLE
Can't find variable: lf_mu_object

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#278]
This is something I'm seeing more and more recently as I've been testing the site

`[Warning] jQuery.Deferred exception: Can't find variable: lf_mu_object – "https://localhost:3000/wp-content/mu-plugins/wp-mu-plugins/lf-mu/public/js/sfmc-forms.js?ver=1.0.0:18:4…" – undefined (jquery-3.5.1.min.js, line 2)`

```
[Error] ReferenceError: Can't find variable: lf_mu_object
	(anonymous function) (jquery-3.5.1.min.js:2:31678)
```

This may be to do with the order of wp_localize_script and enqueueing smfc_forms. From the codex.

> IMPORTANT! wp_localize_script() MUST be called after the script has been registered using wp_register_script() or wp_enqueue_script().
> 
> Furthermore, the actual output of the JavaScript <script> a tag containing your localization variable occurs at the time that the enqueued script is printed (output/included on the page). This has some significant repercussions if you enqueue your script as you should using the appropriate actions (wp_enqueue_scripts and admin_enqueue_scripts), but wish to localize later using data that is not available at enqueue time.
> 
> In this case, consider enqueueing your script with the in_footer argument set to true, to delay the printing of your script include until much later in the page build (ie: wp_enqueue_script( $slug, $URL, $deps, $ver, true ); ).
> The last chance to localize your script would then be on the 'wp_print_footer_scripts' hook.

May want to switch to `wp_add_inline_script`

**Comment by cjyabraham** [comment]
Do you see this only on your local instance or on dev as well?

**Comment by thetwopct** [comment]
Currently only localhost, I will watch out for it anywhere else

**Comment by thetwopct** [comment]
Just got this on live site 

![20200831225818-Web Inspector — www cncf io](https://user-images.githubusercontent.com/10615884/91772815-816e2300-ebdd-11ea-90cf-69dc128540e0.jpg)

**Comment by thetwopct** [comment]
I haven't been able to reproduce this at all since you fixed the defer issue https://github.com/cncf/cncf.io/issues/302 so I think that fixed it, so closing this for now.
