### ISSUE TITLE
Improve text flow around images on mobile

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#280]
Is there a better way to handle the way the text wraps around the images at different widths on these pages:
- https://dev-cncfci.pantheonsite.io/certification/software-conformance/
- https://dev-cncfci.pantheonsite.io/certification/cka/
- https://dev-cncfci.pantheonsite.io/certification/ckad/

At some widths the text wraps oddly:
<img width="385" alt="Screen Shot 2020-08-28 at 2 22 20 PM" src="https://user-images.githubusercontent.com/463160/91528335-1d780000-e93a-11ea-9818-f19a4c4d8965.png">

At others the image just doesn't seem centered:
<img width="339" alt="Screen Shot 2020-08-28 at 2 22 28 PM" src="https://user-images.githubusercontent.com/463160/91528342-22d54a80-e93a-11ea-8fff-76bdccb5fef2.png">

**Comment by thetwopct** [comment]
I've updated the pages and moved some content around, should flow better generally and look better on mobile

**Comment by cjyabraham** [comment]
Could you do [this one as well](https://dev-cncfci.pantheonsite.io/people/ambassadors/)?  There may be others...

**Comment by thetwopct** [comment]
Done, I also did a similar thing to a few of the People pages. Went through the other top level pages, if you see more let's re-open
