### ISSUE TITLE
Intro text size on pages

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#281]
I like the way you have the first paragraph in large text [on this page](https://dev-cncfci.pantheonsite.io/telecom-user-group/), should we use that format on other pages of the site, like on [these listed here that I set up](https://github.com/cncf/cncf.io/issues/280)?

**Comment by thetwopct** [comment]
The consistency would make sense, not sure how those logos would fit in though. I'll play with it.

**Comment by thetwopct** [comment]
I've had a good, think they look better and a lot more consistent

**Comment by cjyabraham** [comment]
[This page](https://dev-cncfci.pantheonsite.io/telecom-user-group/) has max-width on the opening paragraph set at 800px.  While [this one](https://dev-cncfci.pantheonsite.io/community-infrastructure-lab/) has its opening paragraph set at 900px.  Can you pick one standard and make it consistent across the site?  (FWIW I think I like the 900px one better).

**Comment by thetwopct** [comment]
900px is the rule, unless a word hangs over the line and doesn't look right, so then 700/800/100% is available. 

I performed a content search for "is-style-max-width-800" and updated a couple of pages. Feel free to update if you see any I missed.
