### ISSUE TITLE
Make "Get Involved" section editable on webinars (recorded)

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#285]
[Example](https://dev-cncfci.pantheonsite.io/webinars/local-development-in-the-age-of-kubernetes/) (bottom of page)

**Comment by cjyabraham** [comment]
This needs fixing urgently on the new design because the pink clashes with the new site colors.

**Comment by cjyabraham** [comment]
I've just removed the section.  It was suffering from low engagement: just 1 click on the button in the last 30 days.  Now that the center of gravity of webinars and community has moved to https://community.cncf.io/ we can let that platform promote appropriate ways for people to engage.

**Comment by xmulligan** [comment]
@KTan1226 should we had some content on the online programs chapter in Bevy?
