### ISSUE TITLE
Remove "Tags" dropdown from Block Editor sidebar options

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#288]
![20200830010216-Edit Post ‹ Cloud Native Computing Foundation — WordPress](https://user-images.githubusercontent.com/10615884/91648201-7344c900-ea5c-11ea-8df6-786270a1d741.jpg)

We're not utilising post tags in the site, so leaving this option in the sidebar could be confusing. It can be hidden with JS via block editor scripts.

**Comment by cjyabraham** [comment]
Nice.  Could you do this on LFPH as well (or maybe should be moved into the MU plugin)?  I had to point out to Jenny recently that she doesn't need to set the tags.
