### ISSUE TITLE
Fix anomalous sizing of speakers bureau photos

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#289]
<img width="1077" alt="Screen Shot 2020-08-30 at 10 15 15 AM" src="https://user-images.githubusercontent.com/463160/91649754-c1cc8480-eaa9-11ea-8b0e-790b22880acd.png">
<img width="1134" alt="Screen Shot 2020-08-30 at 10 16 20 AM" src="https://user-images.githubusercontent.com/463160/91649760-df99e980-eaa9-11ea-8657-a3ef84c42de9.png">
<img width="1067" alt="Screen Shot 2020-08-30 at 10 16 39 AM" src="https://user-images.githubusercontent.com/463160/91649763-e9235180-eaa9-11ea-88f1-5cbe03e496fe.png">

**Comment by thetwopct** [comment]
I cannot explain this! Its a PNG profile photo and the name of the file doesn't seem to have 190x190 in it, so perhaps a ShortPixel thing? For now, I will download the picture, convert to JPG, and re-upload.
