### ISSUE TITLE
Sandbox projects menu is going off top of screen

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#291]
<img width="819" alt="Screen Shot 2020-08-30 at 2 38 48 PM" src="https://user-images.githubusercontent.com/463160/91652957-8e502100-eace-11ea-9644-67fc262da7a9.png">

**Comment by thetwopct** [comment]
Wow, that really is a lot of links for one menu. We didn't plan for this many. I wonder what value this offers to a user when the sandbox landing page lists them all in a nicer way. How will this menu work in a few months with another 20+ projects lists?

![20200830140003-Sandbox projects | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/91659667-23e8b200-eac9-11ea-8f71-9da408edeb33.jpg)

With desktop nav (1000px width) and fixed nav (700px height) there just isn't room for these items on the screen.

Options I can see:

1) Remove fly out menu of links for Sandbox projects

2) Reduce font size (13px is the smallest we can use to be accessible) and reduce padding. Still barely fits: 

![20200830140512-Sandbox projects | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/91659759-d751a680-eac9-11ea-8a27-5fde904bcb2e.jpg)

3) Have a scroll overflow on the column, but this would mean some projects are hidden to view unless scroll. Is also not an overly nice experience for user.

Any other options?

**Comment by cjyabraham** [comment]
I vote for option 1.  Checking with the others...

**Comment by cjyabraham** [comment]
@caniszczyk is fine with option 1

**Comment by cjyabraham** [comment]
The full list of sandbox projects has been removed from the topnav.
