### ISSUE TITLE
K3 text is too high in sandbox projects

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#292]
Can we keep the K3 on the same line as the others:
<img width="1183" alt="Screen Shot 2020-08-30 at 2 40 40 PM" src="https://user-images.githubusercontent.com/463160/91652987-d7a07080-eace-11ea-85ac-f17ff6bf0cec.png">

There are other projects, like LitmusChaos, which are mis-aligned as well.

**Comment by thetwopct** [comment]
![20200830142031-Sandbox projects | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/91660091-f7826500-eacb-11ea-80ac-8f34d5136eb4.jpg)

All on a level now
