### ISSUE TITLE
Make TOC style consistent

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#293]
You have TOC on [training](https://dev-cncfci.pantheonsite.io/certification/training/) and [join](https://dev-cncfci.pantheonsite.io/about/join/), one with numbers, one with bullets.  Can we establish a consistent style?  

Is there a reason we don't use a tab container layout for Training?  Maybe the diversity in layouts is good?

**Comment by thetwopct** [comment]
Both TOC are now dashes.

Training was earmarked in functional spec to use tab container, but I think with the length of some of the courses it may not look too good. And the embedded landscape will be a little squished. I'm happy with the way it looks now.
