### ISSUE TITLE
FOUC on recorded webinar

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#294]
[I get this when doing a soft refresh.  Can this be fixed?
](https://drive.google.com/file/d/1FSqJNkNKabKy7Z0BR1khIhynfJkNCOj-/view?usp=sharing)

**Comment by thetwopct** [comment]
I think it can be fixed, to a degree. There is javascript in play here to make sure the YouTube embed is always 100% responsive, so it makes the width/height ratio via JS. I think I can reproduce part way using CSS or height/width values, but I'll need some time to play with it. Let's deal with post-deployment.

**Comment by cjyabraham** [comment]
I can't seem to reproduce this issue now on live

**Comment by thetwopct** [comment]
Closing for now, if you spot it again in the future, let's come back to it
