### ISSUE TITLE
Run a link checker soon after we go live

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#295]

**Comment by thetwopct** [comment]
I've run my broken link checker through the site and fixed a lot of the internal broken links. There's a CSS-related issue for the Annual Reports which I will upload.

I've ran an external broken link check, it would be good to update projects/posts/etc with fixed links (or remove the links) - Google will like the site better and it's a better experience for users. [Here's the export](https://docs.google.com/spreadsheets/d/1219-z93MeFVilPJMsHz-10O8Rxh4xjCH3hEB343gW_I/edit?usp=sharing). It's by link, and by page. Some are pointed to LF Events, should those redirects be handled there too?

**Comment by cjyabraham** [comment]
I couldn't edit your doc so created [my own copy here and started fixing on this tab](https://docs.google.com/spreadsheets/d/17PV3-8-TfzAYp_ut5ourJAzENOC0tMAABLOMmH6L37A/edit#gid=1629057998) (see the left column).

I think we can ignore the "429 client error"s since those are likely caused by your linkchecker hitting github too rapidly.

**Comment by cjyabraham** [comment]
I've made a start at these and set up redirects for the events ones.  I'd like to assign the bulk of these to Selly and I'll finish off the ones she can't resolve.  Then we can run the checker again.  

Is there a way to get more information about the ones that say "2 instances over more than one page"?  It would be helpful to know which are the pages.

**Comment by thetwopct** [comment]
The next sheet lists them out by page so you can cross reference. I also found the site search worked quite well, better than using the admin search per post type.

**Comment by cjyabraham** [comment]
Dan has okayed deleting news posts from our site that point to sites/articles that are no longer there.

**Comment by cjyabraham** [comment]
Selly is working through [this tab here](https://docs.google.com/spreadsheets/d/17PV3-8-TfzAYp_ut5ourJAzENOC0tMAABLOMmH6L37A/edit#gid=554553984) after which we can run the checker again.

**Comment by cjyabraham** [comment]
@thetwopct can you run your link checker again please?  Selly has finished her latest pass through the links.

**Comment by cjyabraham** [comment]
The [final report](https://docs.google.com/spreadsheets/d/1WgszV33wW1-YXzAp90NCeTjenCqyrQ2fai6lbVdPnig/edit#gid=1162852464) produced a bunch of links that work for me but don't seem to work for the link checker.  With that, I think we're good for now on this front.
