### ISSUE TITLE
Kim's last name is not properly capitalized in Speakers Bureau

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#297]
In the directory it doesn't have the second M in CAPS.

**Comment by thetwopct** [comment]
This is not a solution though to the (much larger) problem of Speakers using incorrect capitalisation on their names (i.e ALL CAPS). For now I've manually updated a few of the names so they look consistent and professional. I could only see Kim that had a patronymic byname surname / bicapitalization, whereas several speakers (and a lot of unapproved speakers) have poorly capitalized names.

**Comment by cjyabraham** [comment]
Sounds good.  I think this needs to be part of the regular moderation task in order to keep the data high quality.
