### ISSUE TITLE
Add padding to the top of the End User Member column on mobile

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#299]
What's the correct way to add padding between these two columns when they stack on mobile:
![Screenshot_20200831-141512_Chrome](https://user-images.githubusercontent.com/463160/91688939-b48cc400-eb95-11ea-837b-95a79d177171.jpg)

**Comment by thetwopct** [comment]
It can be done a few ways. In this instance I just added spacer blocks to the bottom of each column, so then when the columns wrap they have space between them. If it's something we need to do a lot of, we can look to make this in to a selectable style.

![20200918135144-Edit Page ‹ Cloud Native Computing Foundation — WordPress](https://user-images.githubusercontent.com/10615884/93594426-19c61f00-f9b6-11ea-9bf8-809a5a9e0372.jpg)

result:

![20200918135004-End User Community | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/93594297-df5c8200-f9b5-11ea-9a2b-a1fcdda33c85.jpg)
