### ISSUE TITLE
Uncaught TypeError: b is undefined (jquery.masonry.min.js?ver=3.1.2b) on Speakers profile page

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#302]
![seungkyua](https://user-images.githubusercontent.com/10615884/91698663-fce2bc80-eb6a-11ea-8edb-eb78706a2173.jpg)

The current UM on WP5.5 seems to be throwing an error on singular speakers profiles. I feel like its probably related to UM loading old scripts and relying on jQuery Migrate. Their support team seem to think that installing [this plugin](https://wordpress.org/plugins/enable-jquery-migrate-helper/) will help although I am highly doubtful. We may also want to review the UM asset dequeue to make sure this is not causing this issue.

Could this be the cause of https://github.com/cncf/cncf.io/issues/235?

**Comment by thetwopct** [comment]
Maybe it's not UM, as weirdly I see the error on Members too https://www.cncf.io/about/members/ (but none of the other pages with landscape embedded 🤔)

**Comment by cjyabraham** [comment]
Could it be scripts are getting loaded in the wrong order on certain pages?

**Comment by cjyabraham** [comment]
It looks like this was a script ordering issue.  The way we were deferring scripts was causing the jquery.masonry.min.js not to be deferred while all other UM scripts are deferred.  I've fixed it to defer it with all the others.
