### ISSUE TITLE
Switch site timezone to PT

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#303]
Switch from UTC to PT so posts can be scheduled and released on PT timezone.

Awaiting fix in 5.5.2

https://core.trac.wordpress.org/ticket/50949

**Comment by thetwopct** [comment]
The timezone issue has apparently been fixed and is now available in WordPress 5.5.2.

[Due to issues with the 5.5.2 update](https://core.trac.wordpress.org/ticket/51679), the latest update is now WordPress 5.5.3.

**Comment by cjyabraham** [comment]
done
