### ISSUE TITLE
Improve discussion icon in project social links

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#304]
Example: [Sandbox Projects](https://www.cncf.io/sandbox-projects/)

**In-toto** - "email" icon - links to https://www.cncf.io/sandbox-projects/in-toto-dev@googlegroups.com (broken) - the email value is being parsed as a URL when submitted in the admin.

All other links for the email icon on this page are for discussion groups.

Recommend:

1. Renaming the label of the meta key from "Mail" to "Discussion Group"
2. Change icon to forum/discussion ([example](https://www.google.com/search?q=forum+icon&client=safari&rls=en&sxsrf=ALeKk02YM2eHtTGrhSQ9H92RaKyAujPcIQ:1598882624892&tbm=isch&source=iu&ictx=1&fir=0rrhcjDnCT0LEM%252CZbPunMR8_DWyZM%252C_&vet=1&usg=AI4_-kQk5qu9yUhouwjc6Alf5aHDmQqCjw&sa=X&ved=2ahUKEwikr5P3zcXrAhUICsAKHfp4BUQQ9QF6BAgKEC8&biw=1440&bih=783#imgrc=0rrhcjDnCT0LEM))
3. Check values of existing projects to make sure they list forums/discussion, not emails

**Comment by thetwopct** [comment]
For now I've removed the "email' for in-toto (in-toto-dev at googlegroups.com) as I cannot find the Google Group address it's connected too

**Comment by cjyabraham** [comment]
I can see how the current icon is ok to match the idea of a "Mailing List" but the icon and label you suggest is more precise.  Prometheus has its mail icon [linking here](https://prometheus.io/community/) which is odd.  I agree with your recommended actions.

**Comment by cjyabraham** [comment]
@thetwopct please choose a better icon for the mailing lists in the redesign. [Your suggestions here](https://www.google.com/search?q=forum+icon&client=safari&rls=en&sxsrf=ALeKk02YM2eHtTGrhSQ9H92RaKyAujPcIQ:1598882624892&tbm=isch&source=iu&ictx=1&fir=0rrhcjDnCT0LEM%252CZbPunMR8_DWyZM%252C_&vet=1&usg=AI4_-kQk5qu9yUhouwjc6Alf5aHDmQqCjw&sa=X&ved=2ahUKEwikr5P3zcXrAhUICsAKHfp4BUQQ9QF6BAgKEC8&biw=1440&bih=783#imgrc=0rrhcjDnCT0LEM) would be better than the mail icon.

**Comment by cjyabraham** [comment]
I've changed the label on the icon. What's left is to update the icon.

**Comment by cjyabraham** [comment]
fixed in #568

**Comment by cjyabraham** [comment]
deployed
