### ISSUE TITLE
At mention of CloudNativeFDN is broken on twitter share

### ISSUE THREAD

**Issue by olearycrew** [cncf/cncf.io#305]
When sharing a post from the CNCF.io blog to Twitter, there are two `@` symbols ahead of `CloudNativeFDN` which breaks the mention of the account.

Steps to reproduce:

1. Go to a [blog post](https://www.cncf.io/blog/2020/08/13/21-cncf-interns-graduate-from-the-q2-2020-linux-foundation-communitybridge-program/)
2. Scroll to the bottom (side note - should we have this at the top?)
3. Click the Twitter icon to share the post
4. Obvserve the issue

<img width="585" alt="image" src="https://user-images.githubusercontent.com/6044920/91728978-dbd19a00-eb71-11ea-8ec3-9917574583d6.png">

**Comment by thetwopct** [comment]
Nice spot, thanks! That's now fixed

![ Twitter](https://user-images.githubusercontent.com/10615884/91737614-320d0000-eba7-11ea-92c7-24c0875e174c.jpg)
