### ISSUE TITLE
Add search box (with search query) to top of search results page?

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#306]
I've been fixing broken links and using the frontend search quite a bit. I feel like it would be useful to include a search box and the search query on the search results, so queries can be edited. Currently the user must click search in the header, then re-enter query to search again.

**Comment by thetwopct** [comment]
Putting the search box in the main body seemed to interrupt the flow of the page. I then thought about hiding the search form in a dropdown section, and then realised we already had that on every page in the header. So I ended up improving the header search and I think this solves the main issue (the need to retype the search term).

![Kapture 2020-09-18 at 13 32 50](https://user-images.githubusercontent.com/10615884/93592970-78d66480-f9b3-11ea-882f-42c731e76ba0.gif)

**Comment by cjyabraham** [comment]
Looks good, however, it doesn't seem to work when the user is logged in.  When [I go here in incognito](https://pr-330-cncfci.pantheonsite.io/?s=test) it has "test" in the dropdown but not when I'm logged in to wp-admin.  [Here's a vid](https://drive.google.com/file/d/1zY-0Arc4rtbIVvZXTwq9hZ4hJqRr2-UZ/view?usp=sharing).

**Comment by thetwopct** [comment]
Well isn't that strange. There's no mention of the `get_search_query()` function not working for logged in users. Possible bug? Possible cache issue? Possible privacy issue?
