### ISSUE TITLE
Strange characters in post (when supposed to be Chinese)

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#307]
https://www.cncf.io/blog/2018/11/14/cncf-survey-china-november-2018

This post is dual English and Chinese, but the Chinese version displays really strangely for me

![20200831223349-CNCF Survey: Cloud Usage in Asia Has Grown 135% Since March 2018 | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/91770966-0b1bf180-ebda-11ea-96b8-521e91d05624.jpg)

Chinese case studies display fine, so I don't think its a system font issue.

**Comment by cjyabraham** [comment]
Selly should be getting to this in the next couple of days.
