### ISSUE TITLE
Fix Google Search Console Mobile Usability issues

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#308]
The following issues were found on your site:

Clickable elements too close together

Content wider than screen

Text too small to read

URLs:

https://www.cncf.io/blog/2018/11/14/cncf-survey-china-november-2018/ (related #307 
https://www.cncf.io/blog/2017/12/06/cloud-native-technologies-scaling-production-applications/ (seems to be fixed for all issues)

**Comment by cjyabraham** [comment]
I'll wait for Selly to finish her work then try validating.

**Comment by thetwopct** [comment]
The Google Sheets embed on [this page](https://www.cncf.io/blog/2017/06/05/30-highest-velocity-open-source-projects/) seems to be causing some issues with Mobile Usability. 
- Text too small
- Clickable links too close together
- Width too wide (✅ fixed by setting max width 100% on iframe)

As it's an older post, we could perhaps switch out the embed for an image that links to the sheet (and this appears to be how the article is written anyway).

**Comment by cjyabraham** [comment]
Could we just not fix it (I think the embed is kinda cool)? Or do you think Google is penalizing us for this?

**Comment by thetwopct** [comment]
If we can get access to the sheet to fix, then great.

For now, it seems Google has allowed it and has zeroed off our mobile issues. Let's keep a monitor of it.

![20200918184828-Mobile Usability](https://user-images.githubusercontent.com/10615884/93623822-9faa9000-f9df-11ea-88be-410b027c79ef.jpg)
