### ISSUE TITLE
Make blog excerpt text small for better alignment

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#321]
I dislike the way that sometimes the height of the text block exceeds the height of the image. This could be solved by dropping down the font size of the excerpt by 1.5em, and I think looks much better. 

Current:

![20200909135648-Category: Blog | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/92595224-500fea00-f2a4-11ea-88a6-7d4bc85655fa.jpg)

Proposed:

![20200909135711-Category: Blog | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/92595261-5d2cd900-f2a4-11ea-9b51-9531df6ffdc3.jpg)

**Comment by cjyabraham** [comment]
This doesn't look quite right on mobile.  On Blog and Announcements listings, the first post has larger excerpt text than all following posts.  I think they should all be the larger size in this case.  The smaller text looks a bit too small IMHO:
<img width="378" alt="Screen Shot 2020-09-11 at 2 10 31 PM" src="https://user-images.githubusercontent.com/463160/92872562-baf22a00-f438-11ea-9e1d-1851ce01f743.png">
