### ISSUE TITLE
Investigate why this url produces an error

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#322]
Try going here: https://www.cncf.io/?s=https%3A%2F%2Fcollabsummit2016.sched.org%2Fevent%2F6ByX%2Fwhich-projects-are-cloud-native-and-could-fit-into-the-cncf-alexis-richardson-weaveworks

Here's another: https://www.cncf.io/?s=http%3A%2F%2Fwww.thenewstack.io%2Ftag%2FCloud-Native-Day-2016

**Comment by thetwopct** [comment]
Must be a redirect issue.

Change the word `tag` or `event` in either URL and it works properly.

Looking at the [redirects](https://www.cncf.io/wp/wp-admin/tools.php?page=redirection.php&filterby%5Burl%5D=%2F%28.%2A%29%24), it seems `people`, `tag` and `event` need `^` in front of them, which I have now added, and the links work.
