### ISSUE TITLE
Old single event pages

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#324]
Should we add anything to singular event pages if an event is passed? [Example](https://www.cncf.io/events/oreilly-software-architecture-conference-2019/).

**Comment by cjyabraham** [comment]
I guess we do that on webinars, so we could do that here as well.  I'll file as nice-to-have, however, as I think it's only through using the search that people could discover these pages after they've passed.

**Comment by thetwopct** [comment]
![20200918111623-O’Reilly Software Architecture Conference 2019 | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/93580699-6ef73600-f9a0-11ea-84b9-b848548fd486.jpg)

Added "This event has passed" in same place and with same styling as we have on singular webinars.

Tested on events that
- Have no date set (displays nothing)
- Have a start date set and is upcoming (displays nothing)
- Have a start date and end date and is current (displays nothing)
- Has a start date and end date in the past (displays message)
