### ISSUE TITLE
Flying Pages preloading 3rd party websites?

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#325]
When running Lighthouse on [Ambassadors](https://www.cncf.io/people/ambassadors/) page, it seems to be loading images from meetup.com. I can't explain this, other than perhaps Flying Pages is preloading this due to the links to meetup.com on the page? If so, can we turn off 3rd party preloading, as this does not benefit us?

![20200911102542-Lighthouse Report](https://user-images.githubusercontent.com/10615884/92892571-288e5e00-f419-11ea-82a8-adf617e3723b.jpg)

**Comment by cjyabraham** [comment]
It looks like this guys profile has images from meetup embedded:
<img width="1031" alt="Screen Shot 2020-09-12 at 4 19 58 PM" src="https://user-images.githubusercontent.com/463160/92991116-e564e580-f513-11ea-8c7d-a06b588aa8bc.png">

I'll close this issue but feel free to reopen if you wanted to do something more here.
