### ISSUE TITLE
Projects in sandbox page not accurate

### ISSUE THREAD

**Issue by jkowall** [cncf/cncf.io#326]
https://www.cncf.io/sandbox-projects/ is listing projects are also on the graduated page. For example Thanos and Cortex. If this isn't the right place to open a content issue please let me know.

**Comment by thetwopct** [comment]
Nice catch. Looks like we had some duplication of projects - affecting SPIRE, SPIFFE plus Cortex and Thanos as you mentioned. We've removed the duplicates now. Thanks.
