### ISSUE TITLE
YouTube thumbnails

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#332]
We import the YouTube thumbnail from the recorded webinar and use this to display on the website as a thumbnail image.

![20200918151605-Webinars | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/93601701-e093ac00-f9c1-11ea-94b2-5ff8cd17d4a5.jpg)

I use a 16:9 cropping technique so the black borders of the YouTube thumbnail are hidden, otherwise it would look like this:

![20200918151730-Webinars | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/93601821-133da480-f9c2-11ea-96d2-c610fb096f00.jpg)

Since around the end of July, almost every webinar uploaded to YouTube has had a strange custom thumbnail uploaded to it. This looks really odd on YouTube and looks really odd when embedded on the site too.

CNCF:
![20200918151843-Webinars | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/93601976-3ff1bc00-f9c2-11ea-95fe-7d3ad293e278.jpg)

YouTube:
![20200918152657-One large cluster or lots of small ones? Pros, cons and when to apply each approach | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/93602793-66fcbd80-f9c3-11ea-933e-90ffac8e1e78.jpg)

I don't know if its possible to ask whoever uploads the thumbnails if we can help them improve the look?

YouTube want a 16:9 image - minimum of 1280x720px but any size in that ratio works. 

The online image creation app [Photopea](https://www.photopea.com) has a YouTube size image available in its templates, so it would be easy for the editor to crop the webinar title slide as they have been doing and then match the background colour etc etc. Or re-create the title slide in the app using a consistent CNCF branded template.

![last image](https://user-images.githubusercontent.com/10615884/93602542-05d4ea00-f9c3-11ea-99fa-552306365170.jpg)

**Comment by cjyabraham** [comment]
Thanks James.  I've alerted @KTan1226 and Gerry who manage these.

**Comment by cjyabraham** [comment]
It looks like most of these have been fixed so will close for now.
