### ISSUE TITLE
Improve process for adding new project logos for case studies

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#334]
The case studies highlights block includes the logos of projects associated with the case study. 

These images are matched via project name and pulled in from the theme - `lf-theme/images/projects`

We need a system in place to make sure this is updated as new projects are added to CNCF, otherwise the correct logos will not display in the case study highlights block.

**Comment by cjyabraham** [comment]
I can think of a few possible solutions:
1. If the image file for the project doesn't exist in the theme it can be displayed from the CNCF GitHub repo following this pattern: `https://raw.githubusercontent.com/cncf/artwork/master/projects/[project]/icon/black/[project]-icon-black.svg`.  [An example](https://raw.githubusercontent.com/cncf/artwork/master/projects/tremor/icon/black/tremor-icon-black.svg).  If these GitHub images were ever to change location it could break the case studies display.
2. We add the black logo in a meta field in its respective [Project](https://www.cncf.io/wp/wp-admin/edit.php?post_type=lf_project) CPT.  To display, a search for the project is first done by matching the project titles and then the image file is grabbed.  This could be a bit slow and inefficient at runtime, however, it is likely the most natural solution for editors.
3. We store all logos in the media library and follow a naming convention based on the name of the project: `[project taxonomy slug]-casestudy-logo.svg`.
4. We leave as is and every time a new project is written about the editor needs to request the new image be added from a developer.  This has been how things have been working so far.

Any thoughts?

**Comment by thetwopct** [comment]
4) has been working well to date. But if we have to clear this issue maybe we should implement 1).

**Comment by cjyabraham** [comment]
I think 4 is fine for now. New projects only need to be added a few times/year. We can re-open if this changes.
