### ISSUE TITLE
Continue to improve the pre-publish checklists

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#340]
- [ ] Add space between points in the checklist
- [ ] Detect "News" category by inspecting the category rather than checking for the external url
- [ ] For "News" posts, check to make sure the external url is filled in
- [ ] Find a way to make the checklist update when the "Publish" button is pressed
- [ ] When you set a date for the webinar, there are no longer any items that show in the pre-publish checklist, however, the header for the list still shows in the sidebar. Either we should hide the header when there are no items or leave the "webinar date" item in the list and mark it as "done", as you've done with other items
- [ ] Respond to any feedback from Jesse and team on whether these are useful
- [ ] Make a check for alt tags in images (see #346)

**Comment by thetwopct** [comment]
Current text in sidebar:

> Save draft, or preview post, to re-run all the below checks.

"Re-run" is potentially confusing. If user writes post, presses Publish, the checks have not run to then re-run.

Suggest changing text if we cannot get some kind of auto-save working:

`Save draft, or preview post, to run all checks before publishing.`

**Comment by cjyabraham** [comment]
No longer relevant as we are now using the PublishPress plugin for this
