### ISSUE TITLE
Continue to improve YouTube Lite implementation

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#341]
- [x] Check a side-by-side comparison of thumbnails and see if the YouTube lite ones can be improved.  From my testing it seems the YouTube lite ones are consistently worse quality than a normal YouTube embed.
- [x] Fix YouTube Lite Gutenberg block so that when you set the YouTube url it immediately shows the video in the editor.  Currently it makes the block almost disappear.

**Comment by thetwopct** [comment]
Given this an update, should now work well on the backend and frontend.

A downside I've found is that if an old YouTube video is embedded (not been edited by uploader in more than a year or so) it may not have a webP image thumbnail, so this will cause an "Error" thumbnail to be displayed. A quick fix for this is to open the video, re-save thumbs and they are regenerated. From a coding perspective, I could check for existence of webP/various thumbs before outputting, or offer a facility to override the default thumbnail via image upload. For now though, this meets any YouTube embed performance/tracking requirements we have.
