### ISSUE TITLE
When no image for blog post don't make it large at top of listing

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#342]
When the top blog post doesn't have a featured image I don't think it makes sense to make the CNCF logo fallback image large.  It's probably best just to keep it the same size as the others.  Any dissenting views?

**Comment by thetwopct** [comment]
I would like to aim towards every blog post having a featured image so I'd rather invest the time in education of editors, pre-publish checks, or building an automated feature image tool / using a plugin.

**Comment by cjyabraham** [comment]
We now enforce that every post needs to have a featured image prior to publishing, so closing this issue.
