### ISSUE TITLE
Incorrect SPIRE link in the navigation bar

### ISSUE THREAD

**Issue by evan2645** [cncf/cncf.io#343]
It was brought to my attention today that the link to the SPIRE project in the navigation bar is incorrect (Projects > Incubating projects > SPIRE). It is currently pointing to https://github.com/cncf/artwork/blob/master/examples/sandbox.md#spire-logos 

Any chance we can get it to point to the SPIRE GitHub page instead?

https://github.com/spiffe/spire

**Comment by thetwopct** [comment]
Apologies for that mistake @evan2645 it has now been updated (in both menu and [projects](https://www.cncf.io/projects/) page)

**Comment by evan2645** [comment]
Thanks @thetwopct , that was fast! ❤️
