### ISSUE TITLE
Author "CNCF" display and related issues

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#345]
Request from Jessie:

> Is it possible to get "CNCF" as an author - i.e. "By CNCF" as author byline

In the backend of WordPress, I can see some posts are attributed to "CNCF" author

![20201005230348-Posts ‹ Cloud Native Computing Foundation — WordPress](https://user-images.githubusercontent.com/10615884/95131818-09a49280-075f-11eb-8be0-6c63825719c1.jpg)

But upon [editing this post](https://www.cncf.io/wp/wp-admin/post.php?post=46466&action=edit), the "CNCF" author disappears, and in its place, the first (alphabetical) WordPress user is selected (in this case, this person is a Speaker, not an editor)

![20201005230650-Edit Post ‹ Cloud Native Computing Foundation — WordPress](https://user-images.githubusercontent.com/10615884/95132072-74ee6480-075f-11eb-984a-f7fce729041c.jpg)

I don't feel this is correct, and I wonder if this is a leftover from the post migration from old website? Perhaps they should be assigned to a member of the current team.

For the request itself, currently we do a [basic PHP match](https://github.com/cncf/cncf.io/blob/ad47538019c96d3f044c79dcb37c37abe16d32b9/web/wp-content/themes/lf-theme/classes/class-lf-utils.php#L210) looking for CNCF or admin usernames.

If we remove the basic match, Editors can then use the Guest Author meta field to allow posts to show as "CNCF" author without requiring the post to be attached to another user account.

**Comment by cjyabraham** [comment]
The "CNCF" disappears in the back-end since it is only a "Subscriber".  I have changed its role to "Contributor" and now you'll see it shown in the Author dropdown.  I'm not sure if we want to keep it this way... waiting on more feedback from Jessie on Slack.

**Comment by cjyabraham** [comment]
The decision was to hide the byline for all posts by Jessie, Eli and Katie.

**Comment by cjyabraham** [comment]
deployed
