### ISSUE TITLE
List block has an inconsistent default width

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#354]
When I create a list in a post, the block defaults to have a width of 700px.  When I create a list in a spotlight item, the block defaults to have a width of 964px.  Can we keep this default consistent across all post types?

**Comment by cjyabraham** [comment]
This still seems problematic with pages.

Additionally, in the editor, the list doesn't wrap at the correct width.  See in this example the list goes full-width in the editor while the paragraph below it wraps at the correct width:
<img width="1019" alt="Screen Shot 2021-03-08 at 2 27 10 PM" src="https://user-images.githubusercontent.com/463160/110283088-7c6dae80-801a-11eb-8c46-0c8f4a143150.png">

Demoting this as a nice-to-have.

**Comment by thetwopct** [comment]
Is the issue default width not correct (and if so, what pages is the issue happening on?) or is the issue dots off of the left of the screen ([which was an issue on LFE](https://github.com/LF-Engineering/lfevents/issues/626))? 

I think this might now be solved by the editor changes I've made on the LFPH PR, if not, can you reproduce there and provide specific posts/pages/viewport size where it's seen.

**Comment by cjyabraham** [comment]
Who knew lists were so complicated!  Agreed we should just leave as is.
