### ISSUE TITLE
Contact Form shows @lfph.io email if there is an error

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#355]
https://github.com/cncf/wp-mu-plugins/blob/80a8198e005ff921e37dba10192641afc03b93ec/lf-mu/public/js/sfmc-forms.js#L131

`$( '#sfmc-message' + form ).html( 'There was an error processing your submission. Please try again or contact us directly at info@lfph.io<br>Error code: (' + errorMessage + ')' ).addClass( 'error' );`

**Comment by cjyabraham** [comment]
this is [fixed](https://github.com/cncf/wp-mu-plugins/commit/aa1a6d83686281ec3829dc63f880fe6bc3f6bf6c)
