### ISSUE TITLE
Events color overlay control doesn't respect "Clear"

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#356]
When you create a new Event the overlay is set to 100% opacity but has no color chosen.  Nevertheless, a dark blue color completely hides the Event background image.  If you press "Clear" it still shows this color.  You have to explicitly choose a color and dial the opacity down in order to see the background image.  Please make it so that the default and "Clear" button correctly do not show an overlay.

**Comment by thetwopct** [comment]
It was made this way as color or background options are not required when publishing, so its likely an event could be published with white text on a white background - effectively hidden. 

When setting up the color picker via Post Meta Controls, I could not get the default color to register ([I've now opened an issue about it](https://github.com/garciaalvaro/post-meta-controls/issues/5)), so the clear effect will not work as there is nothing to clear by default. 

The alpha control, part of Post Meta Controls, defaults to 100 unless set by the default color, which cannot be set.

I can remove the default color (set in PHP), but most photos (I would say 99%) need *some* kind of overlay on them, so having the default color is still advisable.

**Comment by cjyabraham** [comment]
Looks like PMC has released a fix.

**Comment by thetwopct** [comment]
OK 

- When adding new event, a default blue is now selected as background color by default 
- "Clear" button now clears this color from editor
- When no color is selected no color is used on the frontend
- Alpha has not been touched, this is set to 100% (no value control is possible)

I think that makes sense, but let me know if you expect it to work differently.
