### ISSUE TITLE
Some projects with no url assigned float up too high

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#361]
See Kyverno below.  Can we make it align with the others?

<img width="975" alt="Screen Shot 2020-12-03 at 12 34 34 PM" src="https://user-images.githubusercontent.com/463160/100964684-21807300-3564-11eb-8caa-166cdb70e4f2.png">

**Comment by cjyabraham** [comment]
Before you say they should have urls assigned, I talked at length with Amye about this and she is leaving them unlinked for now to incentivize the project to take certain onboarding steps, after which she'll setup all the links on the projects page.

**Comment by thetwopct** [comment]
Do we want to deal with Project titles that overly long?

![2020-12-30-125025@2x](https://user-images.githubusercontent.com/10615884/103352265-aa27fb80-4a9d-11eb-8596-632295409470.jpg)

**Comment by cjyabraham** [comment]
I think at the least we should reduce the line height to make the titles a little more compact.
