### ISSUE TITLE
Add a date filter to cncf.io/case-studies 

### ISSUE THREAD

**Issue by oicheryl** [cncf/cncf.io#363]
By year, so 2017/2018/2019/2020 etc

**Comment by cjyabraham** [comment]
Implementation:
- [ ] store published_year in taxonomy on save and update actions
- [ ] use the published_year as a search/filter dropdown
- [ ] style reset button so it looks good when pushed onto its own line (which seems to be the default layout on desktop)

**Comment by cjyabraham** [comment]
Feedback from Cheryl:
- filters should be listed in alpha order
- remove the "All"
- add text above filters "Filter by:"
- consider dropping "Product types"; see if analytics supports this decision
- user just "Year" for published year filter
- implement on the Chinese page as well

- also, investigate if we can group the case studies listing by date and then sort by alpha within a year

**Comment by cjyabraham** [comment]
of the 3412 people who went to the case studies page, only 5 used the product type dropdown during the last 30 days.  It is the least used filter, though Cloud Type only has 8 and is the second least used.  Anyway, I'll drop Product Type.

**Comment by oicheryl** [comment]
@cjyabraham LGTM, thanks!

**Comment by cjyabraham** [comment]
Added to the [english case studies](https://www.cncf.io/case-studies/).  Waiting for Donald's translation to add it to the Chinese ones.

**Comment by cjyabraham** [comment]
[Chinese translation deployed](https://www.cncf.io/case-studies-cn/).
