### ISSUE TITLE
Create thumbnails for blog posts on an ongoing basis

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#364]
LFPH has a [nice way to create thumbnails for blog posts](https://www.lfph.io/blog).  Jenny Wagner has been creating these using [Canva](canva.com).  She sets up a template then swaps in a title, image and color for each post.  The same image is also used as the snackable (social share image) for the post.

We should do the same on CNCF.  Having the default CNCF logo for posts which could instead have an inspiring photo seems like a missed opportunity to make the site engaging.  For example, this is what the CNCF homepage has right now:
<img width="1231" alt="Screen Shot 2021-01-11 at 9 33 39 AM" src="https://user-images.githubusercontent.com/463160/104141127-1b49a600-53f0-11eb-830e-40323d277067.png">

While LFPH looks like this:
<img width="1184" alt="Screen Shot 2021-01-11 at 9 34 07 AM" src="https://user-images.githubusercontent.com/463160/104141138-2bfa1c00-53f0-11eb-837f-1517baaaac6e.png">

**Comment by cjyabraham** [comment]
One idea for this is to create a plugin which automates the creation of these thumbnails.  We should investigate that option.

**Comment by thetwopct** [comment]
Seems like a slight improvement to this workflow will happen in WP 5.7, [the featured image will be automatically set on first image insert](https://github.com/WordPress/gutenberg/pull/27224). I am not sure if I like the feature in general. For CNCF, many images used on blogs are low quality or technical, but maybe something being set it better than nothing...

**Comment by cjyabraham** [comment]
Blog thumbnails are now happening!
