### ISSUE TITLE
Blog navigation improvements: Search and direct link on top nav

### ISSUE THREAD

**Issue by pritianka** [cncf/cncf.io#365]
* Search in blog
-- Use Case: I often want to find a particular blog post on the CNCF blog. I was searching for any post we may have "foundation of doers" but didn't find a way to do so
* Direct link in top nav
-- Use case: I often go to the CNCF site to access the blog because I don't remember if we are blog.cncf.io or cncf.io/blog. So I wonder if it would be faster if Blog replaced "Newsroom" on the top nav and Newsroom was down below. I am open to any other ways to organize this but essentially would love an ATF link to the blog that wasn't nested. 

cc @cjyabraham @ccraigross

**Comment by cjyabraham** [comment]
1. For Search, we have search up here.  Is there a way we can make this more clear:
<img width="869" alt="Screen Shot 2021-01-03 at 9 49 22 AM" src="https://user-images.githubusercontent.com/463160/103470131-0db96e00-4da9-11eb-8e6c-789a0b0db5ea.png">

The "foundation of doers" search produces [these results](https://www.cncf.io/?s=%22foundation+of+doers%22) for me.

2. As for the direct link, we could put "Blog" right on the top level and also have "Newsroom"?  I'm not sure what you mean by "Newsroom was down below."  Incidentally, I'm working on [a new proposal for the topnav here](https://docs.google.com/spreadsheets/d/1Bg5x7mC0ZsWgKbLZSs5eRJR_mNiEdmQD7X-guGcREKM/edit?usp=sharing).  Let's discuss.  (And what does "ATF" mean :P ?  [I searched.](https://www.abbreviations.com/ATF))

**Comment by pritianka** [comment]
Ah I did not realize the search there was for the blog. Is it for only the blog or anywhere on the site?

**Comment by cjyabraham** [comment]
It searches all content types on the site.  So if you try [this search](https://www.cncf.io/?s=test) you'll see the results tagged with content type: "Webinar", "Media Coverage", "Blog"...

**Comment by thetwopct** [comment]
I wonder if "Search For..." should be "Search site..."?

![2021-01-03-131159@2x](https://user-images.githubusercontent.com/10615884/103479408-55e68980-4dc5-11eb-800a-f704547513e9.jpg)

**Comment by cjyabraham** [comment]
Closing this as the direct link to the blog is now reflected in the [proposed topnav](https://docs.google.com/spreadsheets/d/1Bg5x7mC0ZsWgKbLZSs5eRJR_mNiEdmQD7X-guGcREKM/edit?usp=sharing).  If anyone feels strongly that we should change "search for" to "search site" then please reopen.
