### ISSUE TITLE
Enable credit card payments for CNCF End User Supporter

### ISSUE THREAD

**Issue by oicheryl** [cncf/cncf.io#370]
https://docs.google.com/document/d/12EmKLFTBz8iuVipr5bJEyNPQphBmWHmaYqiYrKBuR70/edit

No strict deadline but this will make it easier to get End User Supporters to sign up, so @cjyabraham  is February feasible?

**Comment by cjyabraham** [comment]
This project [will be proposed as part of the cncf.io UX review](https://docs.google.com/presentation/d/1_FXV27aW4CLXUJfh8pFrgCAnVgc3POHb0b4qfaqx5C0/edit#slide=id.gb4d04de5f7_0_0).

**Comment by oicheryl** [comment]
From @cjyabraham: 

> I had a call today with Priyanka and Craig and we discussed the credit card processing for the End User signup.  Craig says that they already have something like that in LFX profiles and will investigate whether it might be custom-fitted for your use-case.  He will get back to us on that.

**Comment by cjyabraham** [comment]
@ccraigross suggests that we could possibly leverage the existing LFX Autojoin forms for companies that want to sign up and can use something similar to this [OpenJS member enrollment](https://enrollment.lfx.linuxfoundation.org/?project=ojsf&product=01t2M000006sgfaQAA#/enrollment) for individuals who want to signup.

**Comment by kgamanji** [comment]
Amazing! It would be great to enable this for End User Supporters, especially the credit card payments. This will provide consistency in managing memberships for end users.

**Comment by oicheryl** [comment]
@kgamanji I believe Craig's suggestion to keep the existing process (DocuSign + invoice). Individuals cannot sign up for CNCF so we cannot reuse the OpenJS enrollment.

**Comment by cjyabraham** [comment]
Reassigning to Craig who is working with LFIT on this.

**Comment by oicheryl** [comment]
From @pritianka :

>  I clarified with Jim and it seems like we will indeed have a halt in any work needed on the SFDC side for our CC processing for the next month or so

**Comment by oicheryl** [comment]
We will have a call with Mindy White to scope out the requirements on 11 Jun.

**Comment by cjyabraham** [comment]
I will close this issue as it is no longer being actively managed by the CNCF web team and we don't have any visibility into its progress.
