### ISSUE TITLE
Project journeys have cropped images

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#372]
Several of the [project journeys](https://www.cncf.io/cncf-kubernetes-project-journey/) have cropped images like this:
<img width="1055" alt="Screen Shot 2021-01-09 at 10 31 39 AM" src="https://user-images.githubusercontent.com/463160/104091749-61045280-52ba-11eb-82c5-6cc9242681b3.png">

**Comment by thetwopct** [comment]
I couldn't reproduce, until I opened it in Chrome.

**Comment by cjyabraham** [comment]
Here's an [old instance on which it worked properly](https://dev-8-29-cncfci.pantheonsite.io/cncf-kubernetes-project-journey/).  That may be helpful in diagnosing the issue...

**Comment by thetwopct** [comment]
Fixed and deployed. Core styles applied flex box to the gallery caption, part of 5.6.
