### ISSUE TITLE
Implement new homepage design

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#386]
[New design](https://xd.adobe.com/view/cffe944c-a8b5-4fdd-adbd-98ca8e70b0eb-9aad/)

[New design - updated](https://xd.adobe.com/view/0a99d6f0-9961-421a-af09-2a378fc8efef-5fca/)

[XD files](https://files.slack.com/files-pri/T08PSQ7BQ-F01Q1MKDBPE/download/cncf_2021_redesign.xd)

**Comment by thetwopct** [comment]
The "Contributors" link in the section under the hero needs to lead somewhere and currently the only place for it to go is off-site to the Github repo https://github.com/cncf/contribute

[Seems there is already a desire to make a contributors page that is more welcoming and varied](https://github.com/cncf/contribute/issues/38), so perhaps this can be accommodated in our redesign to keep visitors on the cncf site for their first click, much in the same way we are making the EUH.

**Comment by cjyabraham** [comment]
It was decided that going to the github repo is what we'll launch with.  I agree that having an on-site page(s) would be great.  @Charley-Mann [was also thinking along these lines](https://docs.google.com/presentation/d/1N2UbnVza2GE22Ye9L0SM3KZ9U118TQo-_vWExIsMWdY/edit?disco=AAAALu8NO2I).

**Comment by xmulligan** [comment]
I think SIG Contributor Strategy is making a contributing website https://cloud-native.slack.com/archives/CT6CWS1JN
