### ISSUE TITLE
Grammatical mistakes and extra spacing found in README.md file 

### ISSUE THREAD

**Issue by being-vishal** [cncf/cncf.io#400]
I have some grammatical mistakes and extra spacing problems in the Readme.md file of this project. 
For e.g:- on line no. 14 there is the extra spacing that looks something like this "utility / abstraction ".

I want to work on this file, update it and resolve the issue

**Comment by being-vishal** [comment]
With due respect @xmulligan why wasn't I assigned with the issue even though I asked willingly to work on it?

**Comment by xmulligan** [comment]
@cjyabraham runs our website so he will be able to help you get the changes merged. I'll add you too though

**Comment by being-vishal** [comment]
Okay. Thank You for assigning the issue to me also.

**Comment by cjyabraham** [comment]
PR merged.  Thanks for your help @being-vishal .
