### ISSUE TITLE
Determine metrics to present on cncf.io

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#405]
We want to review, consolidate and/or automate the population of the metrics in the section at [the top of the homepage](https://www.cncf.io/) and at the bottom of [the Who We Are page](https://www.cncf.io/about/who-we-are/).  Currently we have two distinct sets of metrics.  Are these the best metrics to be displaying in each place?

At the top of the homepage we have:

1. Number of contributors across all CNCF projects; _can be automated with an API call to [devstats](https://github.com/cncf/devstats/issues/290#issuecomment-817654807) or [LFX](https://metrics.lfanalytics.io/v1/projects/cncf-f/summary)_
2. Number of contributions across all CNCF projects; _can be automated with an API call to [devstats](https://github.com/cncf/devstats/issues/290#issuecomment-817654807) or [LFX](https://metrics.lfanalytics.io/v1/projects/cncf-f/summary)_
3. Number of lines of code in all CNCF projects; _can be automated with an API call to [LFX](https://metrics.lfanalytics.io/v1/projects/cncf-f/summary)_

At the bottom of who we are page we have:

1. Number of contributors across all CNCF projects; _same as 1 above_
2. Number of CNCF members; _Can pull this number [from landscape](https://cloud-native.slack.com/archives/GM09QERF1/p1618476958064600)_
3. Number of certified Kubernetes distributions and platforms; _Can pull this number [from landscape](https://cloud-native.slack.com/archives/GM09QERF1/p1618476958064600)_
4. Number of meetup members; _since we've moved to Bevy and no longer use meetup.com, perhaps we should now be stating the number of members there?_

This [LFX dashboard](https://insights.lfx.linuxfoundation.org/projects/cncf-f) shows all the metrics that could be used.

**Comment by lukaszgryglicki** [comment]
Only note that LFX will be outdated for contributors/contributions compared to DevStats (it is always way behind of DevStats configuration).
While for LOC - you can use LFX because it uses extra tools to get lines of code values, while DevStats only have data that comes from GitHub (which is BOC - bytes of code, not LOC).

**Comment by cjyabraham** [comment]
@lukaszgryglicki how outdated does LFX get?  I thought that it updated once/day?

**Comment by lukaszgryglicki** [comment]
Yes, but adding new CNCF projects to LFX takes weeks while adding them to DevStats takes a day or two.

**Comment by cjyabraham** [comment]
Definition of Contributors
- LFX: ?
- Devstats: all who contributed in GitHub

Definition of Contributions
- LFX: ?
- Devstats: GitHub PR, issue, comment, review, commit

**Comment by cjyabraham** [comment]
All the metrics listed are now automated except for this one:
4. Number of meetup members; _since we've moved to Bevy and no longer use meetup.com, perhaps we should now be stating the number of members there?_

**Comment by Charley-Mann** [comment]
Let's keep the same stats currently displayed on the [homepage](https://www.cncf.io/) -- these are the ones that best reflect the people behind the numbers. 

- Number of contributors across all CNCF projects
- Number of contributions across all CNCF projects
- Number of lines of code in all CNCF projects

Re: [Who we are](https://www.cncf.io/about/who-we-are/) page 
We use the metric Members -- I'd like to dig into why we're using this and not End Users. Shall report back!

**Comment by cjyabraham** [comment]
Closing this but please re-open if there needs to be any further changes with which metrics we show.
