### ISSUE TITLE
Change url structure for post categories

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#41]
We want the following url structure for our posts:
- https://www.cncf.io/announcements/...
- https://www.cncf.io/news/...
- https://www.cncf.io/blog/...

I looked for a way to do this in our SEO plugin but couldn't find one.  You mentioned there is some code you could insert to achieve this instead.

**Comment by thetwopct** [comment]
Should be fixed in https://github.com/cncf/cncf.io/commit/610c243f5ffe7b4491fced7c52f3e7d1968927b3

**Comment by cjyabraham** [comment]
Cool.  I've fixed the menu on [the dev site](https://dev-cncfci.pantheonsite.io/) to explicitly point those menu items to the new urls.  I also changed /announcement to [/announcements](https://dev-cncfci.pantheonsite.io/announcements/) and made a note to do this in the deploy steps?
