### ISSUE TITLE
Accommodate long-running online programs

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#410]
Finish time of webinar seems to be inaccurate on multiple webinars, example:
https://www.cncf.io/webinars/cncf-on-demand-webinar-streaming-versus-batch-metrics-aggregation-with-m3/

```
Date: Thursday June 24th, 2021, 12:00 - 11:30 PM PDT
Date (localized to your timezone): Thursday June 24, 2021, 8:00 - 7:30 AM +0100
```

![2021-04-23-112054@2x](https://user-images.githubusercontent.com/10615884/115857744-fb317600-a425-11eb-84ab-0eeedbad34ad.jpg)

**Comment by cjyabraham** [comment]
According to Libby:

> For the 11.5 hr stretches, those are on-demand webinars that technically last for 7 days but Wordpress won’t allow for multiple day events for the webinars so I’ve made them one full day there. On Bevy they last as 7 day events and stay on the site. Is there a better way to do that in Wordpress?

So we'll need to adapt the webinars infrastructure to properly accommodate these types of programs.

**Comment by cjyabraham** [comment]
I've avoided fixing this by no longer listing times and only listing the multi-day programs on the fist day they start.  That should settle any confusion for now and we can make this more sophisticated later if required.
