### ISSUE TITLE
Expired webinar on home page

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#411]
Now we only display one webinar I would think it's important that when it's clicked on it has not already expired?

At the moment, expired webinars remain on the front page, example: https://cln.sh/TgwWeZ

**Comment by cjyabraham** [comment]
Ways upcoming webinars are determined:
1. Search filter plugin does a MySQL filter lf_webinar_date >= current date
2. home-news.php section does a WP_Query lf_webinar_date >= date_i18n( 'Y-m-d' )
3. webinar-single.php checks using the time and timezone compared with the current time.  This is the most accurate method.
4. webinar-related.php same as 2

So some are more accurate and other less accurate.  If our goal is to just feature a webinar on the homepage that hasn't passed and is soon to be upcoming, I suggest we just change the check to lf_webinar_date > date_i18n( 'Y-m-d' ).

**Comment by cjyabraham** [comment]
deployed
