### ISSUE TITLE
Projects page: update to Flux entry

### ISSUE THREAD

**Issue by dholbach** [cncf/cncf.io#412]
On https://www.cncf.io/projects/ can we add/updated these on the Flux entry:

- GitHub: https://github.com/fluxcd/flux2
- YouTube: https://www.youtube.com/channel/UCoZxt-YMhGHb20ZkvcCc5KA (correct @alisondy?)
- Blog: https://fluxcd.io/blog/
- Twitter: https://twitter.com/fluxcd
- Discussions: https://github.com/fluxcd/flux2/discussions

Anything else @scottrigby and @staceypotter?

**Comment by cjyabraham** [comment]
I've made these updates and will close the issue, however, if there are any further change, please reopen and I'll make them.
