### ISSUE TITLE
Links below "Findings" header to not resolve

### ISSUE THREAD

**Issue by pr3l14t0r** [cncf/cncf.io#419]
From URL: https://www.cncf.io/blog/2019/08/06/open-sourcing-the-kubernetes-security-audit/

Heyho dear team!
It appears that the links below the `<h3>` header "Findings" are broken/ not resolvable as the URLs return a 404.

Example: The URL behind the link "Kubernetes security review" points to `https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/Kubernetes%20Final%20Report.pdf` though the file is located at `https://github.com/kubernetes/community/blob/master/sig-security/security-audit-2019/findings/Kubernetes%20Final%20Report.pdf`. 
Same issue for the items "Attacking and Defending Kubernetes Installations", "Whitepaper" and "Threat Model".

I think you would just need to exchange
`https://github.com/kubernetes/community/blob/master/wg-security-audit/findings/`
with
`https://github.com/kubernetes/community/blob/master/sig-security/security-audit-2019/findings`
for each item. 

I'd kindly ask you to correct the URLs behind the links. 
Thank you! :)

**Comment by cjyabraham** [comment]
This is done.  Thanks.
