### ISSUE TITLE
Style Speakers Bureau form notifications

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#42]
Try submitting the registration form, for example, to see this message:
<img width="1009" alt="Screen Shot 2020-03-24 at 7 51 02 PM" src="https://user-images.githubusercontent.com/463160/77422728-eccef000-6e08-11ea-807b-fc1481ba3503.png">

Other key forms:
- speaker [contact form](https://dev-cncfci.pantheonsite.io/speaker/zparnold/)
- form for updating your profile

**Comment by thetwopct** [comment]
Heres the registration message: 

![20200516213337-CNCF Speakers Bureau - Register | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/82129759-eb90c280-97bc-11ea-86ff-d517c0d9ee35.jpg)

Having trouble viewing an update profile success message - the above CSS may cover it, if you can easily check?

**Comment by cjyabraham** [comment]
It looks like there is no confirmation message when you edit your profile.  I think we can live with that.

**Comment by cjyabraham** [comment]
The other confirmation messages look good.
