### ISSUE TITLE
Links to Phippy source files are broken

### ISSUE THREAD

**Issue by annalisag-spark** [cncf/cncf.io#422]
From URL: https://www.cncf.io/phippy/

Source files have broken links - 404 for The Illustrated Children’s Guide to Kubernetes and Phippy Goes to the Zoo. Is there any chance to get them somehow? I tried to get in touch with Matt Butcher on Twitter, but I wasn't lucky enough :) 

Thank you and sorry for bothering.
a.

**Comment by xmulligan** [comment]
Hi @annalisag-spark thanks for pointing this out. You can find all of the logos here https://github.com/cncf/artwork/blob/master/examples/other.md#phippy--friends-individual-logos

@cjyabraham can you help fix the broken link?

**Comment by cjyabraham** [comment]
It seems the source files have been removed from the drive link where they were.  I've removed the button for now so we don't have any broken links on the site.  @annalisag-spark if you do hear back from Matt wrt where these files are now stored, please do let us know.

**Comment by alexcontini** [comment]
I found the drive folder that we had for Phippy goes to the Zoo before - https://drive.google.com/drive/u/1/folders/1fny25jgQ_EOjhAO7EnDG688LU4t1_3jF - not sure if the folder was moved or why the link wasn't working - so it seems that all we had there was a drive folder link with the PDF before, and the PDF is already linked to, so not sure if we should just remove the buttons altogether as they are repeat files?

**Comment by cjyabraham** [comment]
Cool.  I agree it doesn't make sense to have two links to the same PDF so I'll close this for now.
