### ISSUE TITLE
Add images to homepage user blocks

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#424]
See [this design](https://xd.adobe.com/view/cffe944c-a8b5-4fdd-adbd-98ca8e70b0eb-9aad/screen/5d2cbd44-b6c6-4428-997d-d85b8cca2576/).

@ccraigross can you point us to where you go those first two images?

**Comment by thetwopct** [comment]
Crowd
https://www.flickr.com/photos/143247548@N03/49088427301/in/album-72157711835777083/

Audience
https://www.flickr.com/photos/143247548@N03/49091728398/in/album-72157711835777083/

Phippy
https://www.flickr.com/photos/143247548@N03/32433026808/in/album-72157704599428714/

**Comment by cjyabraham** [comment]
deployed
