### ISSUE TITLE
Accessibility: add a bypass block to the header

### ISSUE THREAD

**Issue by karayim** [cncf/cncf.io#425]
Just saw your blog post for the UX redesign. Awesome! With the accessibility test score displayed, I thought I'd run through some tests and saw there's no bypass block which is one of my favorite accessibility tricks. For power users or users with low visibility, add a bypass block to the header which allows users to skip tabbing through *all* the navigation to get to the main content. The bypass block appears when you tab after the page first loads. See starbucks.com or github.com for examples of how they might appear.
https://www.w3.org/WAI/WCAG21/Techniques/client-side-script/SCR28

**Comment by thetwopct** [comment]
Hey Kara, thanks so much for this feedback! This one is on me, I built it in originally but for some reason its been left out for a while now. Looks like we are even still loading a [helper script](https://github.com/cncf/cncf.io/blob/e9eed5a1dbccf832bc8d90883117164b98ee9f13/web/wp-content/themes/lf-theme/source/js/global/skip-link-focus-fix.js) even though its not being used 😅 Strange that none of the WCAG checkers we used highlighted this, but I will get this implemented as soon as possible. Thanks!

**Comment by karayim** [comment]
That kind of thing happens to me all the time. "I swear this was working..." 😄 
I'm always a little wary of accessibility checkers since there are some things they're always going to miss, but it's good to see they're improving. Thanks for taking a look!

**Comment by thetwopct** [comment]
I've added this to a PR instance ready for deploy 

![2021-06-20-173201@2x](https://user-images.githubusercontent.com/10615884/122670690-78daed80-d1ed-11eb-86fc-4be684a00bee.jpg)

Pressing tab when opening any page opens a Skip Link box, pressing enter on this jumps user past the menu and to the content.
