### ISSUE TITLE
Update display_responsive_images() to include width and height attributes

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#428]
Update `display_responsive_images()` to include width and height attributes to fix minor Cumulative Layout Shift (CLS) issues

**Comment by cjyabraham** [comment]
I'm not sure if it's related, but while you're looking at CLS I see some not great CLS when I go to the [LFAsia Kubecon site](https://www.lfasiallc.com/kubecon-cloudnativecon-open-source-summit-china/).  The background appears to shift twice, getting larger each time, when I load the page.
