### ISSUE TITLE
Make case studies look good when printed

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#429]
Create print CSS if needed or whatever works best.

**Comment by thetwopct** [comment]
I've added some print CSS for all pages (removing header/footer, keeping logo) with additional focus on [single case studies](https://pr-431-cncfci.pantheonsite.io/case-studies/alphasense/). 

Current:

[(Before) AlphaSense | Cloud Native Computing Foundation.pdf](https://github.com/cncf/cncf.io/files/6641767/Before.AlphaSense.Cloud.Native.Computing.Foundation.pdf)

After - I think I scaled back the design too much here

[(After) AlphaSense | Cloud Native Computing Foundation.pdf](https://github.com/cncf/cncf.io/files/6641765/After.AlphaSense.Cloud.Native.Computing.Foundation.pdf)

After v2 - this follows the online design closer but just tidies it up:

[(After v2) AlphaSense | Cloud Native Computing Foundation.pdf](https://github.com/cncf/cncf.io/files/6641988/After.v2.AlphaSense.Cloud.Native.Computing.Foundation.pdf)

Let me know any feedback or changes.

**Comment by cjyabraham** [comment]
I like After v2 the best!!

**Comment by cjyabraham** [comment]
It looks like "After" has been deployed.  Did you explicitly choose that one or was it an accident?  I got the sense we both liked "After v2" better?

**Comment by thetwopct** [comment]
I'll have to look in to it. The code to generate After v1 was deleted to get After v2 so having trouble understanding how that is working... I only checked print styles in Safari so that could also be related (I believe Safari defaults to printing background colours and images and without those it could look like After v1)

**Comment by thetwopct** [comment]
I can't seem to reproduce v1 styling, they all match v2. But v2 is hard to replicate exactly across all systems as different browsers handle background graphics differently. If we want more consistency, the styling should be very basic and just focus on text and images.

[Safari default](https://github.com/cncf/cncf.io/files/6680884/Safari-default-Adform.Cloud.Native.Computing.Foundation.pdf)

[Chrome-without-background-graphics](https://github.com/cncf/cncf.io/files/6680881/Chrome-without-background-graphics-Adform._.Cloud.Native.Computing.Foundation.pdf)

[Chrome-with-background-graphics](https://github.com/cncf/cncf.io/files/6680880/Chrome-with-background-graphics-Adform._.Cloud.Native.Computing.Foundation.pdf)

[Edge](https://github.com/cncf/cncf.io/files/6680886/Edge-Adform._.Cloud.Native.Computing.Foundation.pdf)

[Firefox](https://github.com/cncf/cncf.io/files/6680882/Firefox-Adform.Cloud.Native.Computing.Foundation.pdf)

**Comment by cjyabraham** [comment]
Ah, I see.  I needed to turn on background graphics.  

All seem fine now except for some on Safari have the first page mostly blank:
- [Adforms 1]([Adform | Cloud Native Computing Foundation.pdf](https://github.com/cncf/cncf.io/files/6681501/Adform.Cloud.Native.Computing.Foundation.pdf)
- [Adform2 | Cloud Native Computing Foundation.pdf](https://github.com/cncf/cncf.io/files/6681503/Adform2.Cloud.Native.Computing.Foundation.pdf)
- [adidas | Cloud Native Computing Foundation.pdf](https://github.com/cncf/cncf.io/files/6681504/adidas.Cloud.Native.Computing.Foundation.pdf)
)

Up to you if you want to fix this...

**Comment by thetwopct** [comment]
I thought I had avoided that and I can't seem to find any commands that fix it or control when or if it happens. If it's a deal breaker let's remove the print styles as it never seems to happen when the browser just prints the page.

**Comment by cjyabraham** [comment]
Let's just leave for now... since it doesn't happen in FF or Chrome perhaps it's a bug in Safari that they may fix.
