### ISSUE TITLE
New case study block design on End User page

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#430]
Split from https://github.com/cncf/cncf.io/issues/409

Intent: Change current case study display to new display style.

Current:

![2021-06-12-004031](https://user-images.githubusercontent.com/10615884/121727959-d2b92480-cb16-11eb-881d-268abbe4f216.jpg)

New:

![2021-06-12-004058](https://user-images.githubusercontent.com/10615884/121728013-e19fd700-cb16-11eb-9078-3b739605d521.jpg)

Questions
1. What order should they be displayed? The latest X case studies? Pick case studies by post ID? Random? 
2. How many should be displayed?
3. Does the keynote need to be moved out to the video section or somewhere else on the page?

**Comment by cjyabraham** [comment]
1. Latest 4 case studies
2. 4
3. We can just drop it for now

**Comment by thetwopct** [comment]
I've integrated this on [dev](https://pr-431-cncfci.pantheonsite.io/enduser/).
