### ISSUE TITLE
Add CTA at the bottom of case study single page

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#433]
@Charley-Mann to provide details

**Comment by Charley-Mann** [comment]
https://docs.google.com/document/d/12T7FrhL1v9jx9FyNsH07GARGLDRat5JK8OZHGumQ_Z8/edit?usp=sharing

**Comment by thetwopct** [comment]
![2021-06-20-161815](https://user-images.githubusercontent.com/10615884/122668625-2399de80-d1e3-11eb-8f06-309f7ef920bd.jpg)

I've hard coded this for now in the theme, but once WordPress 5.8 comes out (mid July) it should enable us to have Gutenberg block widgets at which point I can convert it to a case study widget so its fully editable from the admin.

![2021-06-20-161659@2x](https://user-images.githubusercontent.com/10615884/122668608-1846b300-d1e3-11eb-8e4f-64dfd6d2e78f.jpg)
