### ISSUE TITLE
Broken layout of case study on iPad

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#435]
Can you figure out what's going on here?  iPad Pro 12.9 running Safari but it's also a problem on Chrome.  Weirdly it's not a problem on an iPad Pro 11 but is a problem on iPad 8th...

<img width="535" alt="Screen Shot 2021-06-19 at 4 41 37 PM" src="https://user-images.githubusercontent.com/463160/122636727-4e216400-d11d-11eb-82c7-fb4f0c87ace1.png">

**Comment by thetwopct** [comment]
Flexbox growing inside an unrestricted grid row. Not sure why not reflected in other browsers and only on iPad but should be fixed now

![2021-06-20-173026@2x](https://user-images.githubusercontent.com/10615884/122670650-4d580300-d1ed-11eb-927e-0071350fa3bf.jpg)

**Comment by cjyabraham** [comment]
This still seems to be a problem, [try Fidelity for example](https://pr-438-cncfci.pantheonsite.io/case-studies/fidelityinvestments/).

**Comment by thetwopct** [comment]
Dumb iOS. Fixed height it is.

Should be fixed now:

![2021-06-20-174933@2x](https://user-images.githubusercontent.com/10615884/122671239-e5ef8280-d1ef-11eb-87fc-5cf3c8fe7000.jpg)

**Comment by cjyabraham** [comment]
The lines of icons are now spaced out more and unevenly.  See [before](https://www.cncf.io/case-studies/fidelityinvestments/) and [after](https://pr-438-cncfci.pantheonsite.io/case-studies/alphasense/).  The first two lines of icons seem spaced out more while the second and third lines seem the same as they were...
BEFORE
<img width="285" alt="Screen Shot 2021-06-20 at 6 54 06 PM" src="https://user-images.githubusercontent.com/463160/122671419-096afb00-d1f9-11eb-8cef-66af80339ba0.png">
AFTER
<img width="286" alt="Screen Shot 2021-06-20 at 6 54 11 PM" src="https://user-images.githubusercontent.com/463160/122671421-0c65eb80-d1f9-11eb-84ea-fb246e0f28ec.png">

**Comment by thetwopct** [comment]
Consistent rows

![2021-06-20-181335@2x](https://user-images.githubusercontent.com/10615884/122671955-403e1280-d1f3-11eb-92da-31e0ec6dcbd8.jpg)

![2021-06-20-181255@2x](https://user-images.githubusercontent.com/10615884/122671944-2c92ac00-d1f3-11eb-8d13-2a672fed65b6.jpg)

**Comment by cjyabraham** [comment]
The top row of logos are significantly taller than the other two rows.

**Comment by thetwopct** [comment]
Will have to fix Friday.

**Comment by cjyabraham** [comment]
I think I got it [here](https://github.com/cncf/cncf.io/pull/438/commits/8620b4660e27f2476b40c67160a7c64f5299b926).
