### ISSUE TITLE
Weird case study listing on iPhone

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#436]
On the end user page I'm getting this on iPhone 12 Pro Max using Chrome or Safari.  When you scroll down the case study listing page you'll see several have content that is pushed down too far on the tile.
<img width="361" alt="Screen Shot 2021-06-19 at 5 05 43 PM" src="https://user-images.githubusercontent.com/463160/122637338-adcd3e80-d120-11eb-916d-9cf4104e5cd6.png">

**Comment by thetwopct** [comment]
The performance of these "real" devices on BrowserStack seems so poor I don't believe the results it's showing me. 

Their iPhone XR shows the same problem:

![2021-06-19-233056@2x](https://user-images.githubusercontent.com/10615884/122649093-7083a380-d156-11eb-8b30-05e7bf9d735f.jpg)

The snag to that is that my actual real iPhone XR doesn't show me the issue. 

The same weird issue is displayed on the case study overview page, but again, I cannot reproduce it on my real iPhone XR or my real iPhone 8+. Its also not reproducible in the Apple Xcode iOS Simulator for the 12 Pro Max.

![Video](https://user-images.githubusercontent.com/10615884/122648029-64e1ae00-d151-11eb-9f10-7188a60c99e9.mp4)

So I think we should put down to BrowserStack weirdness until we can confirm this is an issue IRL.
