### ISSUE TITLE
Blog thumbnails are getting cropped on mobile widths

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#437]
Tested on iPhone 12 mini with Safari although I think it has to do with screen width and not device.  Blog thumbnails are getting cropped such that the words can't be read.  The blog thumbnails look fine, however, on the end user page so what you did there could be applied to the blog listing thumbnails to fix it?
<img width="354" alt="Screen Shot 2021-06-19 at 5 28 37 PM" src="https://user-images.githubusercontent.com/463160/122637960-e6bae280-d123-11eb-9301-bcb6590b8cea.png">

**Comment by thetwopct** [comment]
OK these are now no longer height restricted. This does mean though that they get pretty big just before 768px breakpoint

![2021-06-20-172715@2x](https://user-images.githubusercontent.com/10615884/122670550-dc185000-d1ec-11eb-8930-fcb76aebb964.jpg)
