### ISSUE TITLE
Chevrons are old shade of pink

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#440]
It looks like these chevrons need updating to be the new brighter shade of pink:
<img width="382" alt="Screen Shot 2021-06-27 at 9 55 33 AM" src="https://user-images.githubusercontent.com/463160/123531335-e2975200-d72d-11eb-9ba6-c24f79fdcf55.png">

**Comment by thetwopct** [comment]
This is an easy fix, but as the home page stopped using chevrons to signify CTA action, these may be better suited to being `is-style-arrow-cta`

**Comment by cjyabraham** [comment]
Sure, ok.  Can you swap those in so they can be applied on the end user page (and anywhere else)?
