### ISSUE TITLE
Get multiple landscape embeds to work on one page

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#441]
I'm inserting multiple landscape embeds on [this page](https://www.cncf.io/?page_id=63418) (you'll need to be logged in).  The height of the embeds doesn't seem to be adjusting appropriately for them.  The first 3 are too short while the last one has a lot of white space below it.

**Comment by cjyabraham** [comment]
This may be a separate problem but I just moved the landscapes into tab containers and now they don't show at all.  See https://www.cncf.io/?page_id=63418

Perhaps there's an easy workaround of just moving them outside of the tab container.

**Comment by thetwopct** [comment]
OK nice find, working on this now
