### ISSUE TITLE
Review and update jobs board SEO

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#442]

**Comment by thetwopct** [comment]
Implemented Tuesday 23rd August:

- Updated Meta Title and Description
- Added text footer with some more keywords and phrases

@cjyabraham I don't have access to Google Analytics property for this site, if you could mark 23/08/22 on the data and we can see if this improves visitors.

Unfortunately it doesn't seem like its possible to edit any more SEO tags for other pages i.e:

1) It would be good to have something like "Jobs at XYZ Company" as meta title for each employer - instead the jobs board just lists company name. On the page itself, it should be "Work at XYZ" and "Job Opening at XYZ"

![2022-08-23-141531@2x](https://user-images.githubusercontent.com/10615884/186095280-ba9986ed-4c6d-48f3-bca4-6359000c2b81.jpg)

2) For the profiles, again the title could be improved, and on the page the text could be automated so "View XX Profiles of XYZ Experts", could also summarise the taxonomy results in paragraph format to be more SEO friendly.

![2022-08-23-141816@2x](https://user-images.githubusercontent.com/10615884/186095850-1df63cd2-8a6d-4577-9b94-6628e5eb8226.jpg)

These could be easy wins to rank higher and attract more inbound, but without movement from the software developers this is probably the most we can do with SEO for that site for now.
