### ISSUE TITLE
Code block not displaying properly (in list?)

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#448]
[See this post](https://www.cncf.io/wp/wp-admin/post.php?post=63974&action=edit)

**Comment by thetwopct** [comment]
False alarm. Code blocks display on white in editor and on white on grey in the frontend. 

![2021-07-29-175627@2x](https://user-images.githubusercontent.com/10615884/127480200-df160c64-579d-4d61-a6f6-d3638b71509f.jpg)

![2021-07-29-175640@2x](https://user-images.githubusercontent.com/10615884/127480235-e9cf175e-d397-458b-9720-a85a7d2cce1e.jpg)

I think this is fine for now.

**Comment by cjyabraham** [comment]
I don't get it. [Why does it still show white text here](https://www.cncf.io/wp/wp-admin/post.php?post=63974&action=edit)?  I thought the white-on-white was the problem?

**Comment by thetwopct** [comment]
Lets check it on WP5.8, probably why I cant reproduce, some changes to the editor (it now loads in an iframe) and specificity should fix it
