### ISSUE TITLE
Convert theme options to theme.json

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#449]
WP5.8 started to use [theme.json](https://developer.wordpress.org/block-editor/how-to-guides/themes/theme-json/) to control block editor options. This should remove much of the Gutenberg options from the theme and allow for granular control of settings per block. 

However the way it works is not compatible with our current design and layout.

- It forces us to set a layout content width, so our width restricted paragraph and headings are misaligned inside it on both frontend and backend
- It breaks align wide and full block options (if content width is not set, those alignment options disappear, even when `add_theme_support( 'align-wide' )` is set)
- It breaks the way groups work (full width groups now align content to the edges instead of in a container, using a new inner layout option restricts width but centres all content)

![2021-07-28-182402@2x](https://user-images.githubusercontent.com/10615884/127314591-5dc6d190-5a49-4b19-84f4-10f02d8377b2.jpg)
_Our group layouts look like this using theme.json_

![2021-07-28-180607@2x](https://user-images.githubusercontent.com/10615884/127313310-cd5d1757-8afc-469c-ac2b-6a9bd7307892.jpg)
_The new group inner layout options_

![2021-07-28-180031@2x](https://user-images.githubusercontent.com/10615884/127311711-3b69818a-7fc6-4614-8f8a-0e4cd6f200c3.jpg)
_Using the default layout option for a group generates inline CSS which centres all content (see Latest news... title)_

To adopt the theme.json option we need to either:
- wait for a fix of `add_theme_support( 'align-wide' )` being recognised when using theme.json and we can continue using our current layout
- we change the website design to be a centered design and forget the content width with left align and restricted content width.

Another approach that fails:
- we change all full width groups to have a normal group inside it that restricts content. This does not work as currently child blocks of a full width block don't have alignment options. 

Related issue on Github
https://github.com/WordPress/gutenberg/issues/33374

Related on Trac
https://core.trac.wordpress.org/ticket/53563
https://core.trac.wordpress.org/ticket/53748

**Comment by thetwopct** [comment]
Here's our WIP theme.json file for any future reference:

```
{
    "version": 1,
    "settings": {
        "layout": {
            "contentSize": "1100px",
            "wideSize": "1200px"
        },
        "color": {
            "custom": false,
            "customDuotone": false,
            "duotone": [],
            "customGradient": false,
            "gradients": [],
            "palette": [
                {
                    "slug": "pink-400",
                    "color": "#ff00aa",
                    "name": "Pink"
                },
                {
                    "slug": "purple-700",
                    "color": "#2a0054",
                    "name": "Purple"
                },
                {
                    "slug": "tertiary-400",
                    "color": "#0088ff",
                    "name": "Blue"
                },
                {
                    "slug": "blue-100",
                    "color": "#f4f4f4",
                    "name": "Blue (Light)"
                },
                {
                    "slug": "white",
                    "color": "#FFFFFF",
                    "name": "White"
                },
                {
                    "slug": "black",
                    "color": "#202020",
                    "name": "Black"
                }
            ]
        },
        "border": {
            "customColor": false,
            "customRadius": false,
            "customStyle": false,
            "customWidth": false
        },
        "typography": {
            "customFontSize": false,
            "customLineHeight": false,
            "dropCap": false,
            "customFontStyle": false,
            "customFontWeight": false,
            "customTextDecorations": false,
            "customTextTransforms": false,
            "fontSizes": [
                {
                    "name": "Smallest",
                    "slug": "smallest",
                    "size": "13px"
                },
                {
                    "name": "small",
                    "slug": "small",
                    "size": "14px"
                },
                {
                    "name": "Normal",
                    "slug": "normal",
                    "size": "16px"
                },
                {
                    "name": "H5 Size",
                    "slug": "header-5",
                    "size": "18px"
                },
                {
                    "name": "H4 Size",
                    "slug": "header-4",
                    "size": "20px"
                },
                {
                    "name": "H3 Size",
                    "slug": "header-3",
                    "size": "24px"
                },
                {
                    "name": "H2 Size",
                    "slug": "header-2",
                    "size": "36px"
                },
                {
                    "name": "Huge",
                    "slug": "huge",
                    "size": "42px"
                }
            ]
        },
        "spacing": {
            "customMargin": false,
            "customPadding": false
        },
        "custom": {
            "font-primary": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif, Roboto, Ubuntu, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'"
        },
        "blocks": {
            "core/group": {
                "color": {},
                "custom": {},
                "layout": {},
                "spacing": {},
                "typography": {}
            }
        }
    },
    "styles": {
        "color": {
            "text": "var(--wp--preset--color--purple-700)"
        },
        "typography": {
            "fontFamily": "-apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif, Roboto, Ubuntu, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'"
        }
    },
    "customTemplates": {},
    "templateParts": {}
}

```

**Comment by thetwopct** [comment]
"its not a bug, it's a feature" is the WP line. So we won't be using theme.json to control the theme until we redesign.

**Comment by cjyabraham** [comment]
Sounds like we are not going this route with our new theme so will close
