### ISSUE TITLE
"to" is said twice

### ISSUE THREAD

**Issue by Apollorion** [cncf/cncf.io#450]
From URL: https://www.cncf.io/archived-projects/

`to` is said twice on this page. 

"Inside CNCF, projects are expected to **to** maintain a number of requirements"

```All open source projects are subject to a lifecycle and can become less active for a number of reasons. Inside CNCF, projects are expected to to maintain a number of requirements, and if these are not met, a proposal can be submitted to the TOC to archive a project.```

**Comment by xmulligan** [comment]
@Apollorion thanks for reporting this! The page has been updated
