### ISSUE TITLE
Strange glitch with Twitter embed

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#451]
See [this post](https://www.cncf.io/blog/2021/07/23/scholarship-spotlight-my-first-kubecon-cloudnativecon-amazing-first-time-experience/)

![2021-07-29-183538@2x](https://user-images.githubusercontent.com/10615884/127485331-cf4094d7-c4dd-459b-a447-d1bed0e649ef.jpg)

I also noticed that the image in this post has not been uploaded to the blog and is instead being pulled from a Google Drive account.

**Comment by cjyabraham** [comment]
I've alerted Jessie.  She may be able to fix although you may want to investigate the twitter embed to see if there's a more fundamental problem.

**Comment by thetwopct** [comment]
The twitter embed was being messed up by some video wrapper stuff I had done, I've fixed that now.
