### ISSUE TITLE
LF Hero should use a real featured image in the edit view

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#452]
The LF Hero block is used on various pages, most commonly the case studies. The editor only displays a placeholder image regardless of whether a featured image is set, this is misleading for editors.

![2021-07-29-185717@2x](https://user-images.githubusercontent.com/10615884/127487784-08f7e972-3758-468d-a211-3a6a3898b406.jpg)

**Comment by cjyabraham** [comment]
I figure this is no longer relevant.
