### ISSUE TITLE
Linkerd is both incubating and graduated

### ISSUE THREAD

**Issue by rsheasby** [cncf/cncf.io#458]
If you take a look at the projects page, linkerd is listed under both headings.
https://www.cncf.io/projects/

**Comment by thetwopct** [comment]
Thanks for reporting @rsheasby 👍

@cjyabraham The issue is not duplicated on the [landscape](https://landscape.cncf.io/card-mode?project=hosted), so I would guess the issue is with how the projects are synced. Have assigned you as you've done all the work on it.

**Comment by cjyabraham** [comment]
This is fixed with [this commit](https://github.com/cncf/wp-mu-plugins/commit/82c2f1418318b1e213907c723bc434f5f3aae5b7).  This is deployed but will take up to 12 hours to update and fix the issue.

**Comment by rsheasby** [comment]
Fix appears to be finished deploying.
