### ISSUE TITLE
Sync People Data

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#464]
Setup a [new People repo](https://github.com/cncf/people) to allow all People on cncf.io to update their listing by submitting PRs.

- [x] Add new metadata to People CPT
- [x] Create json file in new repo cncf/people and populate it with existing data
- [x] Create sync to read in json file and update CPTs
- [x] Figure out who is going to merge PRs
- [x] Deploy
- [x] Add commit check to make sure the json validates when PR is submitted
- [x] Communicate this new feature to all People

On Deploy
- [x] Hide People in admin for CNCF ([see this line](https://github.com/cncf/wp-mu-plugins/blob/people/lf-mu/admin/partials/cpts.php#L160))
- [x] Dump the update database of people into the json file
- [x] Force run sync `lando terminus wp cncfci.live -- cron event run --all`
- [x] Delete Kate Gamanji's duplicate entry

**Comment by cjyabraham** [comment]
Should @caniszczyk , @amye and @idvoretskyi have the ability to merge PRs for [the new People repo](https://github.com/cncf/people)?  Anyone else?

**Comment by idvoretskyi** [comment]
@cjyabraham I think three of us is fine to begin with, we can add other folks later if needed

**Comment by cjyabraham** [comment]
Ambassadors now know about this and are submitting [PRs](https://github.com/cncf/people/pull/6).
