### ISSUE TITLE
Retire Speakers Bureau

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#466]
Due to [underuse](https://docs.google.com/presentation/d/1krW0cLXR7AEgii8Xi3cKfZgNZ7MzyPQBdbjVtj-lBfg/edit#slide=id.ge250eb9a35_0_43), we should shut down Speakers Bureau.  [Approved here](https://cloud-native.slack.com/archives/G01J8HGAVAT/p1629137055033400).

- [x] Deprecate by removing from the menu
- [x] Communicate to all Speakers that the Speakers Bureau is going away? @Charley-Mann @KTan1226 to advise on this? We could setup a dev instance with all profile data so that people could access it once it is removed from the live site.
- [x] Remove Speakers Bureau code and users from system.

**Comment by cjyabraham** [comment]
@KTan1226, we spoke a bit about this at kubecon and I think it's agreed that we should shut this down.  Could you help me with a plan to do this gracefully?  I'd like to do it soon so that we don't need to build the UI again in the new site design.  I think it should go something like this:
1. I'll remove it from the topnav menu
2. Give all published speakers a 2-week notice that it will be shut down.
3. After the two weeks, I'll shut it down.  I can set up a dev instance to keep the profile info available for a limited time.  We can send out another notice at this point to published speakers, pointing them to the dev instance if they need access to their profile data.

Sound ok?  Would you be able to draft emails for steps 2 and 3 and then we can get this started?

**Comment by cjyabraham** [comment]
SB is removed from the site.  @xmulligan you can now send out the final email.

**Comment by xmulligan** [comment]
The final email has been sent. We can close this issue on the 29th if there are no further comments
