### ISSUE TITLE
Allow for more versatility in wide code blocks

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#485]
Sometimes there are code blocks that need to be wide so it'd be great if the block could allow for wide-width setting.  [See this post for example](https://www.cncf.io/?p=65325)
<img width="807" alt="Screen Shot 2021-10-25 at 8 03 57 PM" src="https://user-images.githubusercontent.com/463160/138700352-e8e94fe6-32c6-4520-a679-bc9601aa2014.png">

**Comment by thetwopct** [comment]
As the code block we use is 3rd party, I cannot simply add full width alignment options, so instead I have added a "full width" style which will make the code block reach the site container width rather than content width.

**Comment by cjyabraham** [comment]
Nice idea, however, I think it needs some tweaking since even though the code block appears to go full-width with that style, the code itself is still wrapping at the content edge
<img width="1272" alt="Screen Shot 2022-05-10 at 12 32 15 PM" src="https://user-images.githubusercontent.com/463160/167551683-474d3a4b-eda2-41e8-bafd-2bf8b0d7d471.png">

**Comment by thetwopct** [comment]
This is now updated and I have implemented on a few long line length blocks [in this post](https://www.cncf.io/blog/2022/04/04/learn-opentelemetry-tracing-with-this-lightweight-microservices-demo/?preview_id=70411&preview_nonce=3b9d4dc649&preview=true&_thumbnail_id=70580)
