### ISSUE TITLE
Code syntax block not working

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#486]
The code syntax block is failing to color the code.  See here:
<img width="818" alt="Screen Shot 2021-10-27 at 12 22 27 PM" src="https://user-images.githubusercontent.com/463160/139004712-fc55df45-eec9-4612-b6b9-0acd0bffbc3b.png">

When I switch to a default theme it works properly:
<img width="815" alt="Screen Shot 2021-10-27 at 12 22 37 PM" src="https://user-images.githubusercontent.com/463160/139004727-9f0b24ac-9189-4d4e-ab44-484d1ea4cb5a.png">

On inspection, there's a js bug with the prism library when we use our theme:

```
Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at HTMLScriptElement.s.onload (https://www.cncf.io/wp-content/plugins/code-syntax-block/assets/prism/prism.js?ver=1635221236:10:4453)
```

**Comment by cjyabraham** [comment]
I've left [an issue in the plugin repo](https://github.com/mkaz/code-syntax-block/issues/116).

One weird thing is that if I deliberately cause another js error, such as by changing the `id` of the `cookie-banner-button` so that the cookie banner js can't find it, the syntax blocks work properly and don't throw their js error.

**Comment by cjyabraham** [comment]
@thetwopct It looks like the problematic code is [these lines here](https://github.com/cncf/cncf.io/blob/main/web/wp-content/themes/lf-theme/source/js/global/modal.js#L40-L42).  If you remove those lines then the code works.  What exactly do those lines do and can they be modified or removed?  My guess is that they modify the DOM after prism.js has already parsed it.

**Comment by thetwopct** [comment]
This bit of JS ensures the page content is wrapped in a div in which the modal is then added. For our site, as the modal is loaded on every page (WeChat) we could hard code the class in our template files and then we wouldn't need that JS. 
 
But with the redesigned site I want to drop the JQuery dependency of our JS code, so this modal code will likely completely change - if we can wait to fix this issue until relaunch?

**Comment by cjyabraham** [comment]
Ok, sounds good.

**Comment by cjyabraham** [comment]
This is fixed on the new site
