### ISSUE TITLE
SVG formatting in posts

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#49]
Is it possible to make the [SVGs in this post](https://dev-cncfci.pantheonsite.io/blog/2019/11/07/announcing-the-cncf-prometheus-project-journey-report/) look larger [like it is here](https://www.cncf.io/blog/2019/11/06/announcing-the-cncf-prometheus-project-journey-report/).  In other posts they look fine so this may be an edge-case that will require manual intervention.

**Comment by thetwopct** [comment]
This appears to be an edge-case. Can convert post to blocks, and then apply a width to the SVG images (say 800px) and they will be full-width. Will need this to be done manually and have any posts referencing SVG to be updated. 

Just FYI, looking at those two posts you referenced, I can see some other issues with the dev site posts:

- paragraph spacing/line breaks have disappeared
- dashes have been replaced with **â€“** - maybe related to [encoding](https://www.wpallimport.com/documentation/troubleshooting/encoding/)

**Comment by cjyabraham** [comment]
Ok. I've made a note of this manual fix for SVGs.  Will close out this issue.

Yes, I'm aware of the dashes and I'll be search/replacing them, in addition to several other fancy characters, prior to importing next time.

Paragraph spacing has disappeared on posts that may have used VC elements for spacing.  It's a minority of posts.  Most posts are fine.

**Comment by cjyabraham** [comment]
Actually I've found a way to fix the paragraph spacing.  The issue was the problem posts had all paragraphs wrapped in `<span>` tags for some reason.  I'll strip those out before import.
