### ISSUE TITLE
Moving landscape.css in to SCSS build structure

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#492]
Currently there is a `landscape.css` file in the `/source/` folder of the theme.

```
 * Hides the "View the full interactive landscape" notice on landscape embeds.
 * Can be included on the end of the embed url as css=https://www.cncf.io/wp-content/themes/lf-theme/source/landscape.css
```

Suggest we move this file in to the SCSS folder. Gulp will automatically pick the file up and output its contents to the `/build/` folder. It will also generate a minified version. 

Where the landscape is referenced with the CSS, the URL will need to update to reflect this change:

`css=https://www.cncf.io/wp-content/themes/lf-theme/build/landscape.min.css`

**Comment by cjyabraham** [comment]
We actually no longer need this css file.  It was initial created for the embeds in the landscape guide but we ended up not publishing the landscape guide on the CNCF site. https://github.com/cncf/cncf.io/commit/ce375b6cc3c6808b59899721dfe07fe633faea42

**Comment by thetwopct** [comment]
OK. I will remove the file as part of the 2022 theme revision.
