### ISSUE TITLE
Keylime accepted date and logo are wrong

### ISSUE THREAD

**Issue by axelsimon** [cncf/cncf.io#494]
Hello!
On https://www.cncf.io/projects/keylime/, the Keylime logo is so tiny it is barely recognisable and date for when Keylime was accepted into sandbox is wrong: it is in the future :)
> Keylime was accepted to CNCF on 9/22/2022

This should be 2020.

Furthermore, that date format is highly confusing for any non-US folks, which is at least half the CNCF target audience (if not more).
If we are going to use short dates, could we use the ISO-8601fomat? Ie: 2021-11-30 for today.

Happy to create a separate issue for this last item, if needed.

Thanks!

**Comment by thetwopct** [comment]
I'm having issues reproducing the tiny logo issue. Can you let me know what browser you are using or provide a screenshot? On all browsers I have access to, the logo looks to be displaying at an acceptable size and no smaller/bigger than other project logos:

![2021-12-01-012138@2x](https://user-images.githubusercontent.com/10615884/144105388-f506224f-dd20-4ba5-a0f9-d02fc89c8e06.jpg)

![2021-12-01-011528@2x](https://user-images.githubusercontent.com/10615884/144104443-4ade49d3-28cb-4766-8cf5-e509efbcf4f7.jpg)

The date looks to be a mistake. The data is pulled live from the open source [CNCF Landscape](https://github.com/cncf/landscape) - [you can see the data here](https://github.com/cncf/landscape/blob/master/landscape.yml#L601) and submit a PR to change. Likewise, the logo can be updated in the same [repo](https://github.com/cncf/landscape/tree/master/hosted_logos).

I can submit a PR for the date change tomorrow if you haven't done it by then.

Regarding dates, you could open a request specifically on the [CNCF landscape](https://github.com/cncf/landscape/issues) issues board, or on the upstream [Landscape app](https://github.com/cncf/landscapeapp), which runs the software for all the [Landscapes](https://landscapes.dev/) (which AFAIK all use that date format, so changing it may be a stretch!)

Thanks!

**Comment by axelsimon** [comment]
On Firefox 94.0 on Fedora (with ublock disabled, and no other relevant add-ons), i see this:
![Untitled](https://user-images.githubusercontent.com/1172256/144107650-c8aedd07-eeee-4c1e-85c9-ee0167c288c8.png)

Thanks for the pointers on the Keylime date, i'll submit a PR!

I'll look at opening an issue regarding the date format :) Surely an ISO standard will convince *everyone*, right? :wink:

**Comment by cjyabraham** [comment]
@thetwopct how about we change the date format to "December 1, 2021", which is the same format we use elsewhere on www.cncf.io and likely understandable to people more broadly?

**Comment by thetwopct** [comment]
@cjyabraham OK I've created an issue to update the way the project accepted date is displayed https://github.com/cncf/cncf.io/issues/495

@axelsimon I can reproduce in Firefox, thanks for the help. Looks like **all** logos are affected, so will be fixing this straight away. Tracking here https://github.com/cncf/cncf.io/issues/496 

I also opened a [PR](https://github.com/cncf/landscape/pull/2367) to change the Keylime accepted date on Landscape, so this should be approved within a few days and then feed through to the website shortly after that.

**Comment by cjyabraham** [comment]
Ok, the accepted date format has been updated and the logo fixed in firefox.  Also the Landscape PR has been merged and deployed with the correct accepted date.  @axelsimon can you verify?  Then we can close out this issue.

Thanks @thetwopct for the quick fixes.

**Comment by axelsimon** [comment]
All looks good, thanks for this very fast fix, @cjyabraham & @thetwopct !
