### ISSUE TITLE
Change accepted date format for projects

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#495]
From #494 

Change accepted date format from Americanised to same format used throughout CNCF site (~~1st December 2021~~ December 1, 2021)

<img width="357" alt="CleanShot 2021-12-01 at 11 46 26@2x" src="https://user-images.githubusercontent.com/10615884/144173562-97536f93-aa80-4d45-a4a4-44287a1d00d5.png">

<img width="881" alt="CleanShot 2021-12-01 at 11 47 49@2x" src="https://user-images.githubusercontent.com/10615884/144173699-9adf4783-1e05-4917-a2ab-2d785d406728.png">

**Comment by cjyabraham** [comment]
It should be "December 1, 2021" right?  (not what you have in the description)

**Comment by thetwopct** [comment]
Yes
