### ISSUE TITLE
[Question] how to revise the homepage link of OpenYurt in https://www.cncf.io/projects/openyurt/

### ISSUE THREAD

**Issue by rambohe-ch** [cncf/cncf.io#501]
Hi, I don't know if here is the right place to ask, but I thought I'd like to have a try.  Thank you in advance.

Homepage link of OpenYurt(github.com/openyurtio/openyurt) have changed as following:
https://openyurt.io/en-us --> https://openyurt.io

and the question is: how to revise the homepage link in https://www.cncf.io/projects/openyurt/?

**Comment by cjyabraham** [comment]
You will need to update this line in the landscape config: https://github.com/cncf/landscape/blob/master/landscape.yml#L209

Could you submit a PR or would you like me to?  It will then update the cncf site within 12 hours or so.

**Comment by rambohe-ch** [comment]
> You will need to update this line in the landscape config: https://github.com/cncf/landscape/blob/master/landscape.yml#L209
> 
> Could you submit a PR or would you like me to? It will then update the cncf site within 12 hours or so.

@cjyabraham Thanks for your feedback. I can submit a PR.

**Comment by cjyabraham** [comment]
See these instructions: https://github.com/cncf/landscape#logos

**Comment by rambohe-ch** [comment]
> See these instructions: https://github.com/cncf/landscape#logos

@cjyabraham Thanks for your reply. i will close this issue.

**Comment by rambohe-ch** [comment]
> You will need to update this line in the landscape config: https://github.com/cncf/landscape/blob/master/landscape.yml#L209

@cjyabraham OpenYurt homepage url in landscape has been updated(https://github.com/cncf/landscape/pull/2375), but homepage url in https://www.cncf.io/projects/openyurt/  still keep unchanged. so i reopen this issue.

**Comment by cjyabraham** [comment]
There is a delay in making changes to landscape and when the change is reflected on the cncf.io site.  It looks like it is updated now but I'll let you verify.

**Comment by rambohe-ch** [comment]
> There is a delay in making changes to landscape and when the change is reflected on the cncf.io site. It looks like it is updated now but I'll let you verify.

@cjyabraham Thank you very much. and the homepage url was updated.

/close
