### ISSUE TITLE
Event logos not displaying properly in Safari

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#502]
https://www.cncf.io/events/

![2021-12-07-114835@2x](https://user-images.githubusercontent.com/10615884/144968259-4a002da2-6e0f-4e8e-9da6-6e22ea88b228.jpg)

Seems to be coming from HTML attributes aspect-ratio.

![2021-12-07-114905](https://user-images.githubusercontent.com/10615884/144968322-07f90d61-17bc-41b6-8c8c-33bce5cfa7bd.jpg)

**Comment by cjyabraham** [comment]
deployed
