### ISSUE TITLE
Metrics not being properly displayed

### ISSUE THREAD

**Issue by VaibhavPaliwal0007** [cncf/cncf.io#503]
When you open cncf.io and https://dev-cncfci.pantheonsite.io there is a slight typo on the home page of <strong>0M+ written lines of code</strong>. It can't be zero. Correct me if I am wrong. 

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/78612380/145047495-4a53e5f2-fb90-45eb-9217-e3d755f1dca7.png">

I am also looking forward to working on this issue. Do assign me @cjyabraham.
I first encountered this issue in Safari and rechecked this in Brave and chrome same results.

**Comment by thetwopct** [comment]
Thanks Vaibhav, great spot!

Looks like the [default metrics](https://github.com/cncf/cncf.io/blob/1bbbd83788524590196a78303d65c2ce6c853df7/web/wp-content/themes/lf-theme/classes/class-lf-utils.php#L461) aren't being picked up properly if the call to metrics.lfanalytics.io fails or returns 0.

**Comment by VaibhavPaliwal0007** [comment]
I loved to work on this issue. Kindly tell me how can I get started with this.

**Comment by cjyabraham** [comment]
This was also needed: https://github.com/cncf/cncf.io/commit/08dbb08725f021fe56d5c061ba3a1d1740d7e07c

**Comment by cjyabraham** [comment]
This is deployed and transient cleared.  

@VaibhavPaliwal0007 thanks for finding this.  We needed a quick fix here so not a great first issue to help with but let's keep an eye out for something else for you.

**Comment by VaibhavPaliwal0007** [comment]
Yes, @cjyabraham If there is any suitable work for me, do pin it out. Thanks.
