### ISSUE TITLE
Security risk: plugin version exposed

### ISSUE THREAD

**Issue by dan-redcupit** [cncf/cncf.io#509]
From URL: https://www.cncf.io/

WordPress plugin versions exposed, please see this report
https://www.upguard.com/instant-security-score/report?c=www.cncf.io

DMARC policy is p=none
DNSSEC not enabled

**Comment by thetwopct** [comment]
<img width="363" alt="CleanShot 2022-05-10 at 11 50 28@2x" src="https://user-images.githubusercontent.com/10615884/167544843-571e4e31-e95d-4902-9cdc-c14a185414dd.png">

WordPress version no longer exposed
