### ISSUE TITLE
Please add knative as incubating project on cncf.io

### ISSUE THREAD

**Issue by csantanapr** [cncf/cncf.io#511]
Please add [knative](knative.dev) as incubating project to https://www.cncf.io/projects/
Knative was accepted as incubating project today 2022-03-02 by the CNCF TOC
https://www.cncf.io/blog/2022/03/02/knative-accepted-as-a-cncf-incubating-project/

cc @amye @caniszczyk

**Comment by cjyabraham** [comment]
It is now there: https://www.cncf.io/projects/

FYI the projects listing on cncf.io is pulled a couple times/day from the landscape data.

**Comment by csantanapr** [comment]
Thank you @cjyabraham for looming into the issue
