### ISSUE TITLE
Update link to Kubernetes 2019 audit on the Open Sourcing the Kubernetes Security Audit blog

### ISSUE THREAD

**Issue by reylejano** [cncf/cncf.io#521]
From URL: https://www.cncf.io/blog/2019/08/06/open-sourcing-the-kubernetes-security-audit/

Please update the link to the Kubernetes Security Review to
https://github.com/kubernetes/sig-security/blob/main/sig-security-external-audit/security-audit-2019/findings/Kubernetes%20Final%20Report.pdf

**Comment by reylejano** [comment]
All the links under the Findings header need to be updated to for the appropriate links in the kubernetes/sig-security repo

- Kubernetes Security Review 
https://github.com/kubernetes/sig-security/blob/main/sig-security-external-audit/security-audit-2019/findings/Kubernetes%20Final%20Report.pdf

- Attacking and Defending the Kubernetes Installations
https://github.com/kubernetes/sig-security/blob/main/sig-security-external-audit/security-audit-2019/findings/AtredisPartners_Attacking_Kubernetes-v1.0.pdf

- Whitepaper
https://github.com/kubernetes/sig-security/blob/main/sig-security-external-audit/security-audit-2019/findings/Kubernetes%20White%20Paper.pdf

- Threat Model
https://github.com/kubernetes/sig-security/blob/main/sig-security-external-audit/security-audit-2019/findings/Kubernetes%20Threat%20Model.pdf

**Comment by cjyabraham** [comment]
This is done.
