### ISSUE TITLE
Get Lando environment to access port 3000 BrowserSync

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#523]
As discussed on our call, having the `gulp watch` process running via build on its own proxy site is slow to start, a bit confusing and limiting as it cannot easily be restarted should the process fail without running `lando rebuild -y`. Would be easier - if its possible - to allow devs to simply run `lando npm start` which launches gulp / browsersync and have port 3000 accessible from the browser. Can you see if you can get that working? The readme file in the v2022 branch has my latest lando config.

**Comment by cjyabraham** [comment]
This should work now. Follow [the README](https://github.com/cncf/cncf.io/tree/v2022). Update your .lando.yml. Run `lando rebuild -y` and then you should be good to run `lando npm start` in your theme directory.
