### ISSUE TITLE
Feat: Phippy and his friends need a biography

### ISSUE THREAD

**Issue by the-technat** [cncf/cncf.io#526]
On the Phippy page (https://www.cncf.io/phippy/) I miss a biography / explanation for all of his friends. Would it be possible to add a subpage for all of them that explains what kind of app they are?

**Comment by thetwopct** [comment]
We now have short biographies of each character written - this will be added to the site soon as part of https://github.com/cncf/cncf.io/issues/542 @the-technat thanks for your input here! Will post an update once the page is live, but closing this issue for now 👍

**Comment by the-technat** [comment]
Thank you for the update! That's awesome to hear.

**Comment by Charley-Mann** [comment]
FYI @thetwopct @GarethAcidWorks I updated the bios -- they needed some content love! Here they are: https://docs.google.com/document/d/1IrXSK9Z4D9zZiKAstdXk8DW6tZlbqrxqgetQWtnu0bw/edit?usp=sharing

**Comment by GarethAcidWorks** [comment]
Updated in figma
