### ISSUE TITLE
Project menu dividing lines

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#53]
On the homepage the projects submenu has a line showing at the bottom of the first column.  I think it'd be better not to have that line:
<img width="938" alt="Screen Shot 2020-05-09 at 10 28 55 AM" src="https://user-images.githubusercontent.com/463160/81461731-60be2f80-91e0-11ea-9bc1-0dfde45370b9.png">

Weirdly, this line doesn't show on the [members page](https://dev-cncfci.pantheonsite.io/about/members/):
<img width="950" alt="Screen Shot 2020-05-09 at 10 28 21 AM" src="https://user-images.githubusercontent.com/463160/81461747-7e8b9480-91e0-11ea-9316-c956a5085eb7.png">

**Comment by thetwopct** [comment]
Yeah I messed about with this at the time, can't find an elegant and performant way to do it right now. I really don't want to use JS for something so simple, but it may need to be that. I need to revisit this menu anyway, as now the real data is there, Sandbox items are too long and disappear past the bottom of the screen, but the workaround I've done makes it too long for the top too.

**Comment by cjyabraham** [comment]
I'm going to label this nice-to-have.  I think we can live with it and don't think it's worth using js for.

**Comment by thetwopct** [comment]
I'm going to close this for now. JS is the only way I can see how to do it. We can do it with CSS (I'll move it to using flex box/grid instead of css columns) BUT this would require some modifications every time a new project is added/removed, and that is not what we want.
