### ISSUE TITLE
Mobile site goes back to top when menu is displayed 

### ISSUE THREAD

**Issue by tyron** [cncf/cncf.io#530]
From URL: https://www.cncf.io/blog/2022/05/09/introducing-the-new-cncf-io/

When navigating any page on mobile, if you scroll down and open the mega menu, when you close the menu the page will be back at the top. That affects usability if you accidentally click the menu or just wanted to check something (like opening an item in a new tab)

**Comment by thetwopct** [comment]
Thanks for reporting! Can reproduce here - will implement a fix soon 👍

**Comment by cjyabraham** [comment]
deployed
