### ISSUE TITLE
Improve home page video loading experience

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#537]
This is especially noticeable on iOS

**Comment by cjyabraham** [comment]
I had an idea for the grey flash: what about changing the grey to black, then any flashing won't be as noticeable since the first frame is mostly black?

**Comment by cjyabraham** [comment]
I tried a bunch of stuff with this but didn't get anywhere :(

**Comment by thetwopct** [comment]
## Safari Browser on MacOS
https://user-images.githubusercontent.com/10615884/177248220-22fe4aa0-cd4a-40db-8398-be537b72e9dd.mp4
00:00 Grey background on load (should be black) (Issue A)
00:04 Video doesn't load at correct size / jumps to fit (Issue B)

## Safari/Chrome on iOS**

https://user-images.githubusercontent.com/10615884/177248857-8e07579e-06e4-4c06-ac4a-e378ea6c3dad.mov

00:00 Grey background on load (should be black) (Issue A)

## Chrome on Mac (Throttled to fast 3G)

https://user-images.githubusercontent.com/10615884/177249199-e1ce0f5a-37a0-4595-9341-6bd7b5569df2.mp4

00:02 Flash of gray before video poster displays and then video plays (Issue C)

# Fixes

**Issue A**

Not entirely sure why the gray is displayed on first load, possibly how Safari interprets the loading of the poster image to be "complete" or not, but I feel like adding a black background to the entire hero should force the background to be black, so the overlay doesn't create the gray effect on first load, only on the poster/video once they are loaded. 

**Issue B**
It's strange that Chrome doesn't have the same issue. The issue could be that the CSS needs to fully load to properly size the video so there is a slight delay and thats the jump we see. I would hypothesise that inlining the styling should eliminate the problem.

**Issue C**
I believe this is happening as the poster fades out over 500ms, but the overlay changes color without transition when changing from black to black 50% opacity. Added transition to overlay change. 

Need to push changes to server and test again as local testing media can be unreliable.

**Comment by cjyabraham** [comment]
Seems greatly improved by #568 👍 In browserstack I still seem some resizing going on but no more grey flash.

**Comment by cjyabraham** [comment]
deployed
