### ISSUE TITLE
Code block doesn't show colors for certain languages

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#545]
While it seems that setting the language to Javascript does change the coloring of code, setting it to Bash/Shell, Python or YAML does not change code colors.

**Comment by thetwopct** [comment]
Using [this page](https://www.cncf.io/blog/2022/01/20/how-to-monitor-endpoints-in-kubernetes-using-blackbox-exporter/) ([edit link](https://www.cncf.io/wp/wp-admin/post.php?post=66874&action=edit)) as an example.

The code blocks do not have a code language selected, so I have updated the first one to be YAML, but the text is still all white.

I'm seeing an error from Prism on the frontend:

![2022-05-17-140830@2x](https://user-images.githubusercontent.com/10615884/168750515-73cacb1f-9d6a-442c-bacc-008fc849bd7f.jpg)

Prism is two files, one library and one specific to the content the is dynamically loaded. The specific file (prism-yaml.min.js) is being loaded async, while the library is being deferred. Perhaps removing the defer would solve this error.

Additionally, in the editor there seems to be an issue with setting the Global Color Scheme. I doubt this is related but here is what happens:

https://user-images.githubusercontent.com/10615884/168751254-b55e8d52-c8af-4051-9f1e-2737c2ea9683.mp4
