### ISSUE TITLE
Add link to allow download of Japanese PDF of Annual Report 2021

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#547]
The team has translated the annual report into Japanese and created [a PDF](https://www.cncf.io/wp-content/uploads/2022/05/CNCF_Annual_Report_2021-ja.pdf). I've suggested that we include a link to the Japanese version under the top "Download" button. Perhaps just a link that says "(or get the Japanese version)"? I'm open to other options. 
<img width="1317" alt="Screen Shot 2022-05-19 at 5 23 12 PM" src="https://user-images.githubusercontent.com/463160/169272081-7031ae7f-9f18-4b62-8568-b1d6fc2542e9.png">

**Comment by thetwopct** [comment]
I'm not super happy with this implementation - this section is so tightly fit that it doesn't work very well in the original design at anything other than 1400px wide, and adding this hasn't helped, but I would like to think this is about as good it will get. 

![2022-05-20-221541](https://user-images.githubusercontent.com/10615884/169559181-d0235c5d-5bde-4559-a42e-9d0f0280c8d9.jpg)

![2022-05-20-221613](https://user-images.githubusercontent.com/10615884/169559302-d4142865-45e8-415b-b3a0-691ac77e1805.jpg)

**Comment by cjyabraham** [comment]
[I've added an underline](https://github.com/cncf/cncf.io/commit/231022354cc77401f51793da4a76edaa4eb72177) so that it looks clickable to people, otherwise it seems a bit confusing, like that the Japanese version can be obtained by clicking the "Download" button.
