### ISSUE TITLE
Migrate radar in to cncf.io

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#548]
There are many benefits to moving the radar posts in to the CNCF.io site where it could inherit our established design system and we could more easily cross-promote it on [project pages](https://www.cncf.io/projects/containerd/) and related content. 

That said we should note the automation the radar site currently provides:
- this [Database Storage radar](https://radar.cncf.io/2020-11-database-storage) is generated from just [this yml file](https://github.com/cncf/radar/blob/main/content/radars/2020-11-database-storage.yml). Links to projects and metadata for each are pulled from landscape as part of the template in addition to generating the radar “fan” image itself.
- [this overview page](https://radar.cncf.io/overview) which is an auto-generated listing of all projects and the date they were reviewed. It’s probably so out-of-date at this point, however, that it’s no longer useful.

Key steps:
- [ ] Design radar landing page and individual radar pages - @GarethAcidWorks 
- [ ] Create design assets for all [existing radars](https://radar.cncf.io/) so they can be migrated into the new site - @GarethAcidWorks 
- [ ] Implement backend architecture @cjyabraham 
- [ ] Implement designs @thetwopct 
- [ ] Migrate old radars over to site @cjyabraham 
- [ ] Launch @cjyabraham & @thetwopct 
- [ ] Shut down old site and redirect radar.cncf.io url to new page @cjyabraham 
- [ ] Train editors in how to add new radars @cjyabraham & @thetwopct

**Comment by KTan1226** [comment]
+1 - I'm in support of migrating this into our site. I'm not sure the timeline on the next Tech Radar report but we can add this into the workback plan as needed. FYI @onlydole

**Comment by onlydole** [comment]
Howdy, team! We will want to capture the same information in future CNCF Radars, though with more of a focus on workflows over the technology choices. @GarethAcidWorks - I think the next steps are you and I working together on the deliverable(s) and working backward from the design to the process.

**Comment by GarethAcidWorks** [comment]
Roger, sounds good

From: Taylor Dolezal ***@***.***>
Date: Tuesday, 27 September 2022 at 21:14
To: cncf/cncf.io ***@***.***>
Cc: Gareth Davies ***@***.***>, Mention ***@***.***>
Subject: Re: [cncf/cncf.io] Migrate radar in to cncf.io (Issue #548)

Howdy, team! We will want to capture the same information in future CNCF Radars, though with more of a focus on workflows over the technology choices. @GarethAcidWorks<https://github.com/GarethAcidWorks> - I think the next steps are you and I working together on the deliverable(s) and working backward from the design to the process.

**Comment by cjyabraham** [comment]
@onlydole are you interested in migrating all old radars in to the new site? I assumed so but wanted to check as some of them may have a shelf-life that has now passed?

**Comment by onlydole** [comment]
Howdy, @cjyabraham! That would be ideal to ensure this is archived appropriately (with 301 links on the older domain, too).

**Comment by KTan1226** [comment]
I know we are waiting on the new style for Tech Radars but can we move forward with moving this into the website in the interim?

**Comment by cjyabraham** [comment]
Not really. The content and design needs to inform the data structure we build.

**Comment by GarethAcidWorks** [comment]
Just to check in on this, there was an initial design done but I believe we’re waiting on a full session / alignment with Taylor for this. To ensure all content / features are on point. I’ll follow @Chris ***@***.***> and @Taylor ***@***.***> lead on this one.



From: Kristi Tan ***@***.***>
Date: Thursday, 20 October 2022 at 12:30
To: cncf/cncf.io ***@***.***>
Cc: Gareth Davies ***@***.***>, Mention ***@***.***>
Subject: Re: [cncf/cncf.io] Migrate radar in to cncf.io (Issue #548)

I know we are waiting on the new style for Tech Radars but can we move forward with moving this into the website in the interim?

**Comment by thetwopct** [comment]
@GarethAcidWorks I could only find this in Figma (Canvas 27), is this the initial design?

![2022-10-21-223739@2x](https://user-images.githubusercontent.com/10615884/197234633-d45f8d75-64ec-4f33-b789-9050d95cfbbd.jpg)

We need the following to move forward:

> * Design radar landing page and individual radar pages - @GarethAcidWorks
> * [ ]  Create design assets for all [existing radars](https://radar.cncf.io/) so they can be migrated into the new site - @GarethAcidWorks

**Comment by GarethAcidWorks** [comment]
I’m sure there’s more than that in another figma file, but yes we definitely paused due to wanting to fully align with Taylor D. Either way the page needs a lot of work and is nowhere near ready yet

From: James Hunt ***@***.***>
Date: Friday, 21 October 2022 at 11:40
To: cncf/cncf.io ***@***.***>
Cc: Gareth Davies ***@***.***>, Mention ***@***.***>
Subject: Re: [cncf/cncf.io] Migrate radar in to cncf.io (Issue #548)

@GarethAcidWorks<https://github.com/GarethAcidWorks> I could only find this in Figma (Canvas 27), is this the initial design?

***@***.***<https://user-images.githubusercontent.com/10615884/197234633-d45f8d75-64ec-4f33-b789-9050d95cfbbd.jpg>

We need the following to move forward:

  *   Design radar landing page and individual radar pages - @GarethAcidWorks<https://github.com/GarethAcidWorks>
  *   Create design assets for all existing radars<https://radar.cncf.io/> so they can be migrated into the new site - @GarethAcidWorks<https://github.com/GarethAcidWorks>

**Comment by KTan1226** [comment]
Howdy @onlydole! Will we have a new Tech Radar by EOY? Just trying to move this issue along :)

**Comment by cjyabraham** [comment]
This issue isn't about creating a new tech radar. The issue is about migrating [the current radar site](https://radar.cncf.io/) to the www.cncf.io site. The tasks needed are outlined in the description of the issue above.

**Comment by GarethAcidWorks** [comment]
Hi all,

Happy to get the page design moving on this again. I'd like some further clarity of what the core needs are.
Previously I was working on a more easy to understand & sharable version of the cone chart.
We paused on this and I believe were waiting on a call with Taylor to align with the new needs as we bring it into the main site.

@onlydole @cjyabraham can we pencil something in asap this week?

**Comment by KTan1226** [comment]
Hi all - I chatted with @onlydole today and we agreed to push this issue into Q1 of 2023. There will not be a TR this year and we'd like more time to discuss the design, as well as the content. @cjyabraham could you please update the issue timeline. 

Thanks! cc @GarethAcidWorks

**Comment by cjyabraham** [comment]
Looks like radars are now being [delivered in PDF format](https://www.cncf.io/reports/cncf-technology-landscape-radar/) so no need to pursue this issue anymore.
