### ISSUE TITLE
Swap out Custom Twitter Feeds Pro for Custom Twitter Feeds free version

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#551]
The Pro version no longer supports the shortcode method of displaying a feed (see email about this). All project feeds currently work because they are imported as legacy feeds, however, any new projects added will not work (I think), so, to get ahead of that issue, we should downgrade to the free version of the plugin in order to make sure all work via the shortcode method.

**Comment by thetwopct** [comment]
I believe only the pro version supports the multi-column masonry layout that we use (as per [free version description](https://wordpress.org/plugins/custom-twitter-feeds/))

**Comment by cjyabraham** [comment]
Author is recommending the PRO version 1.14.2 which still supports shortcode options.
