### ISSUE TITLE
Fine-tune spacing before headings

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#553]
See the [Kubernetes annual report](https://www.cncf.io/?post_type=lf_report&p=73004). h3, h4 and h5 headings have the same amount of space before them regardless of what level heading they are. I think the higher level headings should have less space than the lower level ones. This is the current style:
```
.page-content h3, .page-content h4, .page-content h5, .page-content h6 {
    margin-bottom: 20px;
    margin-top: 60px;
}
```

I think it should be something like this:
```
.page-content h3 {
    margin-bottom: 20px;
    margin-top: 60px;
}
.page-content h4 {
    margin-bottom: 20px;
    margin-top: 45px;
}
.page-content h5, .page-content h6 {
    margin-bottom: 20px;
    margin-top: 30px;
}
```

**Comment by cjyabraham** [comment]
@thetwopct do you agree with what I'm suggesting here?

**Comment by thetwopct** [comment]
Yes I agree to an extent, and have submitted my recommended approach including responsive changes where necessary. I also noticed in this report that H5 headings were smaller than the paragraph text below it, so I have update the font size of a few headings to better stagger the sizes as the reader progresses.

**Comment by cjyabraham** [comment]
deployed
