### ISSUE TITLE
Set up dual tagging of GA4 and UA to prep for UA shutdown

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#560]

**Comment by thetwopct** [comment]
We should look to do this sooner rather than later so we have a full year of comparison data in GA4 when UA is shutdown in July 2023.

https://support.google.com/analytics/answer/1109102
https://evolytics.com/blog/dual-tagging-with-google-analytics-4-and-universal-analytics/

**Comment by cjyabraham** [comment]
done
