### ISSUE TITLE
Glossary style tweaks

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#562]
- [ ] Add fade to top/bottom edges of the sidebar so that it's clear the sidebar can scroll
- [ ] Change out search, all tags, and category icons to be the same as on the main site (see figma glossary designs)
- [ ] Get search input design to exactly match figma

**Comment by thetwopct** [comment]
@cjyabraham PR notes and draft available to review and for checking here https://github.com/cncf/glossary/pull/1081

**Comment by thetwopct** [comment]
Closing as done
