### ISSUE TITLE
Featured Reads on About megamenu

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#564]
Currently it is showing this:
<img width="505" alt="Screen Shot 2022-06-27 at 1 04 33 PM" src="https://user-images.githubusercontent.com/463160/175870374-c4a58770-e3a4-4ad5-ad2f-dfa7eded8dea.png">

I think we should instead show the latest CNCF annual report and the most recent report of any type that is not the annual report.

@KTan1226 LMK if you have any objections to this change.

**Comment by cjyabraham** [comment]
@Charley-Mann agrees first slot should be CNCF Annual Report and 2nd slot should be configurable as she would like to set this.

**Comment by thetwopct** [comment]
Suggest we add a new menu to the Site Settings to control this. Can extract all the posts in reports as a select box to make selection of the the posts easier. As the "Annual Reports" category includes more than just CNCF annual reports, both slots will need to be configurable.

**Comment by cjyabraham** [comment]
I figured the first slot could be automated by searching the "annual reports" category for the latest report with string "CNCF" in the title. That would generate [this set of data](https://www.cncf.io/reports?_sf_s=cncf&_sft_lf-report-type=annual).

A dropdown of other reports for the second slot sounds ideal if that's not too hard to implement.

**Comment by cjyabraham** [comment]
Deployed
