### ISSUE TITLE
Reinstate LF Stats block

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#567]
Notice that some [project journey reports](https://www.cncf.io/wp/wp-admin/post.php?post=67248&action=edit) are using the custom `lf/stats` block, which was removed in the relaunch of the CNCF site.

![2022-07-04-141349@2x](https://user-images.githubusercontent.com/10615884/177101404-f6cda911-0bdd-4bfb-9c75-bd39dfc6f972.jpg)

![2022-07-04-141439@2x](https://user-images.githubusercontent.com/10615884/177101526-eabdd2ea-48a4-4426-9d04-bc36f88b166b.jpg)

**Comment by cjyabraham** [comment]
fixed in #568

**Comment by cjyabraham** [comment]
deployed
