### ISSUE TITLE
dapr-logos link is broken

### ISSUE THREAD

**Issue by bibryam** [cncf/cncf.io#574]
From URL: https://www.cncf.io/projects/dapr/

The logos link points to: https://github.com/cncf/artwork/blob/master/examples/incubationt.md#dapr-logos
It should be:                     https://github.com/cncf/artwork/blob/master/examples/incubating.md#dapr-logos

**Comment by cjyabraham** [comment]
Thanks for reporting. This value actually gets pulled from the landscape repo. I have submitted [the fix there](https://github.com/cncf/landscape/commit/e69eac252fe04d92477027dbd98b63de6d29cc9c) and updated the CNCF site, so should be good now.
