### ISSUE TITLE
Classify OpenTelemetry as Observability, not Tracing

### ISSUE THREAD

**Issue by cartermp** [cncf/cncf.io#575]
From URL: https://www.cncf.io/projects/

In this page, OpenTelemetry is classified as a tracing solution. However, OpenTelemetry encapsulates traces, metrics, and logs today with more signals in the pipeline. It's ultimate an Observability framework as per the tagline:

> High-quality, ubiquitous, and portable telemetry to enable effective observability

Could we classify it as Observability?

cc @chalin

**Comment by cjyabraham** [comment]
We pull the data for that page from [the CNCF Landscape](https://landscape.cncf.io/). The OpenTelemetry entry can be updated by opening a PR and editing it [here](https://github.com/cncf/landscape/blob/master/landscape.yml#L6750). I think you'll need to move it from the "tracing" subcategory to the "observability" one. I'll close this issue for now as there's no action we can do on this end.
