### ISSUE TITLE
Hide Recaptcha badge on SB profile page

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#58]
Is there a reason you commented [this line](https://github.com/cncf/cncf.io/blob/master/web/wp-content/themes/cncf-theme/source/scss/core/_forms.scss#L200) out?  The recaptcha badge is now showing on [the SB profile pages](https://dev-cncfci.pantheonsite.io/speaker/wolmi/).

**Comment by thetwopct** [comment]
I hadn't touched that forms.scss file, and it was jumbled in with gravity forms stuff which is just templating from my theme file. Have moved it away from that now and commented.
