### ISSUE TITLE
Update text to recategorize SPIFFE and SPIRE grad projects

### ISSUE THREAD

**Issue by anvega** [cncf/cncf.io#581]
The page https://www.cncf.io/projects/ lists SPIFFE and SPIRE as "Key Management". The project team would like this text to be updated to say "Identity and Key Management".

Thanks!

**Comment by thetwopct** [comment]
This text (category) is automatically pulled from the CNCF Landscape data. The category “Key Management” would need to be updated on the Landscape and also on the associated guide. You can open a pull request to implement this change or start discussion around this change in the Landscape repo https://github.com/cncf/landscape
