### ISSUE TITLE
Explore automatically generating PDFs of reports

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#583]
Currently for every web report we build, we also have to design a PDF. This creates additional/duplicated work and sometimes delays in the release process (a minor update still has to be cycled through creative team and a new PDF generated and uploaded).

We should explore the generation of PDF reports from the web version which could be done by any team member via WordPress.

Previously we have experimented with making CNCF Case Studies "printable" so if a page is printed or saved as a PDF then headers and footers etc are removed, backgrounds removed, etc using @print stylesheet. This proved difficult due to the different print engines per browser, and the limitations of print options (i.e. hyperlinks were not created). 

Other approaches we could explore:
- Use a headless Chrome approach so the PDF is created more like a screenshot rather than using the @print stylesheet - [there](https://github.com/daudmalik06/PhpChromeToPdf) are [quite](https://github.com/chrome-php/chrome) a [few](https://github.com/tesla-software/chrome2pdf) [different](https://github.com/rialto-php/puphpeteer) [packages](https://github.com/spiritix/php-chrome-html2pdf) to help do this
- Use an external [service](https://docraptor.com/html-to-pdf) (most seem use the headless Chrome approach)
- Use a WordPress plugin (often attached to a service) ([PDFCrowd](https://wordpress.org/plugins/save-as-pdf-by-pdfcrowd/), [RestPack](https://wordpress.org/plugins/save-as-pdf/), [Print My Blog](https://wordpress.org/plugins/print-my-blog/))

Potential problems with this approach:
A) Hidden areas will have to be unhidden (we have only used this report style on the KCCNC EU 22 report
B) Interactive / layered charts (chartJS) may not display properly or display at all (only used so far on Annual Report 21)

@cjyabraham what do you think?

**Comment by cjyabraham** [comment]
This idea feeds in to [the larger conversation we were having](https://cloud-native.slack.com/archives/G01J47SM3FH/p1659794954952539?thread_ts=1659551911.796159&cid=G01J47SM3FH) about producing PDFs. I think it's a good option to consider but will depend on the business reason for having PDFs at all. If they need to be pixel perfect, then we will just need to keep making them by hand. If they just need to offer a decent printable option for people, then I think the solutions you suggest above could be useful and are one step up from a print CSS. I will make a note to discuss with the wider team.

**Comment by cjyabraham** [comment]
Filing as nice-to-have for now

**Comment by thetwopct** [comment]
Closing as not currently part of our plan for reports.
