### ISSUE TITLE
Align landscape to new brand

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#586]
Update landscape social share, favicon, and [logo](https://landscape.cncf.io/images/left-logo.svg) to fit new brand. Current landscape assets are [here](https://github.com/cncf/artwork/blob/master/examples/other.md#cncf-landscape-logos).

**Comment by GarethAcidWorks** [comment]
![CNCF_User Icons_03gd copy-11](https://user-images.githubusercontent.com/91599545/188859327-bce9eb5b-f69d-431c-b6b3-c130e89f865c.svg)
![CNCF_User Icons_03gd copy-12](https://user-images.githubusercontent.com/91599545/188859339-9a8a9f7a-a4f3-4b9d-8fd0-882aeee7e8ad.svg)
![CNCF_User Icons_03gd copy-12](https://user-images.githubusercontent.com/91599545/188859346-524b3167-842e-4660-94ad-9f1ce4d11829.png)
![CNCF_User Icons_03gd copy-13](https://user-images.githubusercontent.com/91599545/188859351-939d7978-64c8-47f2-8a6a-d0fbc53e6739.svg)
![CNCF_User Icons_03gd copy-11](https://user-images.githubusercontent.com/91599545/188859356-cc3a69e5-c238-445c-9719-c3b644dbc6cc.png)
![CNCF_User Icons_03gd copy-13](https://user-images.githubusercontent.com/91599545/188859361-b55c7e4d-1fe8-4f1b-b01d-190b88dcc012.png)

**Comment by GarethAcidWorks** [comment]
Should be good to go, Taylor D has seen these and happy with the design

**Comment by cjyabraham** [comment]
@GarethAcidWorks can you also provide the social share image?

**Comment by cjyabraham** [comment]
@GarethAcidWorks a few comments:
- the PNG versions of the logos have quite a lot of space around them. Can you crop them so they comply with the format and quality of the others [here](https://github.com/cncf/artwork/blob/master/examples/other.md#cncf-landscape-logos)? If you want I could get Alex to do this as I think she prepares others regularly.
- can you also provide B&W versions like we have listed?
- can you also provide the social share image for the landscape site?

**Comment by GarethAcidWorks** [comment]
Sure, Alex might be able to get it done today so worth reaching out.

If not ping me on slack and we can sort it in the morning.



From: Chris Abraham ***@***.***>
Date: Thursday, 8 September 2022 at 11:47 PM
To: cncf/cncf.io ***@***.***>
Cc: Gareth Davies ***@***.***>, Mention ***@***.***>
Subject: Re: [cncf/cncf.io] Align landscape to new brand (Issue #586)

@GarethAcidWorks<https://github.com/GarethAcidWorks> a few comments:

  *   the PNG versions of the logos have quite a lot of space around them. Can you crop them so they comply with the format and quality of the others here<https://github.com/cncf/artwork/blob/master/examples/other.md#cncf-landscape-logos>? If you want I could get Alex to do this as I think she prepares others regularly.
  *   can you also provide B&W versions like we have listed?
  *   can you also provide the social share image for the landscape site?

**Comment by cjyabraham** [comment]
PRs have been submitted to the [landscape repo](https://github.com/cncf/landscape/pull/2744) and [artwork repo](https://github.com/cncf/artwork/pull/355) to include the new logos. We also wait on [work from the landscape devs](https://cloud-native.slack.com/archives/GM09QERF1/p1662745445987009) to incorporate the social share image.

**Comment by cjyabraham** [comment]
deployed
