### ISSUE TITLE
Turn off click functionality in desktop topnav

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#59]
When I click on a topnav menu it stays open even when I move away from it so you can potentially have this:
<img width="541" alt="Screen Shot 2020-05-09 at 2 59 51 PM" src="https://user-images.githubusercontent.com/463160/81466646-d092e100-9205-11ea-9886-69718a248553.png">

Would it be better to just not have a click behavior?

**Comment by thetwopct** [comment]
This was a problem in Chrome with some of the accessibility features I had prepared (keeping :focus). I will revisit some of the more advanced accessibility features after deployment.
