### ISSUE TITLE
Turn off pink hover color on top topnav elements

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#60]
What do you think of turning off the pink hover color on the top-level topnav:
<img width="355" alt="Screen Shot 2020-05-09 at 3 01 41 PM" src="https://user-images.githubusercontent.com/463160/81466690-18b20380-9206-11ea-945c-2530b73ca5a3.png">

I think it would look better staying white, as the current site does.

**Comment by thetwopct** [comment]
I feel like it needs *something* to indicate what's happening, it helps the user know where they are as the hover area for each option is larger than the link.

I experimented with dimming it off-white, but that didn't look good, so I went with the primary pink colour. Apart from About, where it clashes slightly with the gradient, it works pretty well.

Underline, perhaps?

**Comment by cjyabraham** [comment]
Could try underline, or bold.  Or just leave it.  I take it you don't like that animated arrow thing we have on the live site?

**Comment by thetwopct** [comment]
I don't like that animation for this particular menu type - I use that in the mobile menu as it clearly indicates a clicked/folded out menu. But the arrows may give us a solution - I can add a slight downward effect to them on hover, should look good and we can remove the clashing colour issue.

**Comment by thetwopct** [comment]
I played around with the menu a bit today. Tried a few different styles with arrows moving, colours changing, but they either didn't work or just made the menu code overly complicated. I've got some small fixes to make in the JS, but the current styling should be ready for your approval now.

**Comment by cjyabraham** [comment]
Looks great!
