### ISSUE TITLE
Link to webinar page is broken

### ISSUE THREAD

**Issue by techmaharaj** [cncf/cncf.io#602]
The link to webinar page on [this blog post](https://www.cncf.io/blog/2020/01/17/cncf-webinars-fresh-insights-for-the-cloud-native-community/) is broken _(anchor text: in-depth guidelines)_

![image](https://user-images.githubusercontent.com/10296271/191637836-c81435cf-2d69-49d2-a77f-1dc2972e6035.png)

Upon checking, the webinar-guidelines.md page was renamed to `online-programs-guidelines.md` as part of [this PR](https://github.com/cncf/foundation/pull/124)

_PS: I can fix this._

**Comment by thetwopct** [comment]
@techmaharaj Thanks for reporting this broken link. Webinars were renamed to Online Programs in late 2020 so posts before this are likely to be incorrect.

The data is stored inside WordPress which is not publicly accessible so you are not able to fix this. I have updated the link in the post. Thanks!
