### ISSUE TITLE
Homepage multi-event banner

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#604]
This follows on the work from #570. Implement a slider to display all qualifying events on the homepage. Slider will have arrows to allow user to go between events and may also possibly move automatically when there is no guiding user input. Qualifying events are those that are upcoming and have the desktop and mobile assets set. Here are the basic designs, however, there are some points that need discussing and finalizing:
<img width="906" alt="Screen Shot 2022-09-23 at 1 52 12 PM" src="https://user-images.githubusercontent.com/463160/192027828-ce9bb34a-3d45-48db-be48-ff30401d30c7.png">

Steps:
- [x] Finalize designs
- [x] Implement
- [ ] Train editors in how to add assets to events

Dimensions for Event banner images:
- Desktop - 2400px x 840px
- Mobile - 900px x 1100px

**Comment by thetwopct** [comment]
Lets get the designs finalised for the slider - personally I prefer arrows inside the container, and this also works better on mobile.

@GarethAcidWorks do we want to signify the number of sliders (typically this is done with dots under or over the bottom of the slider). If so we need an active and inactive state.

**Comment by GarethAcidWorks** [comment]
Yes it would be good to show the number of sliders

we should already have the design in Figma but we can triple check it now it’s going into production.

Will message you today



From: James Hunt ***@***.***>
Date: Monday, 26 September 2022 at 01:51
To: cncf/cncf.io ***@***.***>
Cc: Gareth Davies ***@***.***>, Assign ***@***.***>
Subject: Re: [cncf/cncf.io] Homepage multi-event banner (Issue #604)

Lets get the designs finalised for the slider - personally I prefer arrows inside the container, and this also works better on mobile.

@GarethAcidWorks<https://github.com/GarethAcidWorks> do we want to signify the number of sliders (typically this is done with dots under or over the bottom of the slider). If so we need an active and inactive state.

**Comment by thetwopct** [comment]
@GarethAcidWorks Just wondering if there is any progress on this slider design. From Figma:

<img width="710" alt="CleanShot 2022-10-17 at 15 43 47@2x" src="https://user-images.githubusercontent.com/10615884/196131970-88c22d42-485a-4956-baa8-54392a2fadaa.png">

- The arrow controls floating over the top of the banner look great, think that's much better than them sitting outside the container.
- It took me a while to see the lines that indicate the slider count - they are also easy to miss on artwork that's not Detroit (i.e. Valencia), so I wonder if this needs a rethink (they could sit below the banner maybe).
- If you can provide a mobile mockup too showing arrows and slide indicator that will make implementation easier.
- Lets confirm the text/heading style above the banner too - previously suggested "Upcoming Events & Other Activities" but I feel like we could drop "Other Activities" as this will be displaying only events.

Thanks

**Comment by GarethAcidWorks** [comment]
Hey James, great we’re getting to this. I will have a look at Figma asap today / this week

The immediate question is @Kristi ***@***.***> / @Thabang ***@***.***> can we get the next piece of content to show here, some recommendations could be:

• Next events happening, maybe a medium sized one? (featuring the smaller events supports our need to empower the community)

• Detroit highlights – linking to a the Flikr page or a blog page on the CNCF site

• A report perhaps. Even an older one such (CTO etc).

Ultimately we are presenting a range of CNCF content…. getting some content in here is beneficial so at least we can make a start.

From: James Hunt ***@***.***>
Date: Monday, 17 October 2022 at 03:50
To: cncf/cncf.io ***@***.***>
Cc: Gareth Davies ***@***.***>, Mention ***@***.***>
Subject: Re: [cncf/cncf.io] Homepage multi-event banner (Issue #604)

@GarethAcidWorks<https://github.com/GarethAcidWorks> Just wondering if there is any progress on this slider design. From Figma:

[CleanShot 2022-10-17 at 15 43 ***@***.***<https://user-images.githubusercontent.com/10615884/196131970-88c22d42-485a-4956-baa8-54392a2fadaa.png>

  *   The arrow controls floating over the top of the banner look great, think that's much better than them sitting outside the container.
  *   It took me a while to see the lines that indicate the slider count - they are also easy to miss on artwork that's not Detroit (i.e. Valencia), so I wonder if this needs a rethink (they could sit below the banner maybe).
  *   If you can provide a mobile mockup too showing arrows and slide indicator that will make implementation easier.
  *   Lets confirm the text/heading style above the banner too - previously suggested "Upcoming Events & Other Activities" but I feel like we could drop "Other Activities" as this will be displaying only events.

Thanks

**Comment by thetwopct** [comment]
@GarethAcidWorks No further thinking on content is required - the banner is for CNCF events has been built as discussed, signed off and implemented in [this issue](https://github.com/cncf/cncf.io/issues/570).

**Comment by cjyabraham** [comment]
Could we also get assets for the following events as @KTan1226 [has outlined](https://github.com/cncf/cncf.io/issues/570#issuecomment-1239811614):
- [KubeDay Japan](https://events.linuxfoundation.org/kubeday-japan/) (Dec 7)
- [KubeCon + CloudNativeCon Europe 2023](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/) (April 17-21)

Note that as soon as Kubecon NA has passed on the 28th the current event banner will disappear unless we've loaded up assets for future events.

As a reminder, dimensions for Event banner images need to be
Desktop - 2400px x 840px
Mobile - 900px x 1100px

**Comment by GarethAcidWorks** [comment]
Hi all, here are the banners for Kube Day Japan.
We do not have artwork for KCCNC Europe yet.
Perhaps we can implement Detroit + Japan for now as a test.

Regarding the interface:

• I do feel the title and the dividing lines helps us bring some context / purpose / engagement to the page after a couple of scrolls. Currently the title is improved to 'Events & more' but have to take another look at that when Charlie is free.

• Regarding the thin line counters, I tried them below the artwork and it's creating awkward space. So i would recommend either of the following:

a) Keep them within the image, they are only a gentle suggestion that there is more content
b) Don't use them at all.

For the actual behavior of the banner, having it switch itself every 3 seconds, and also the ability to click would keep the page feeling alive

![CNCF_Ad Canvas_01gd_D_2400 x 840](https://user-images.githubusercontent.com/91599545/197110445-c9d0d825-6d52-485f-8e5c-0f51e8900f0f.jpg)
![CNCF_Ad Canvas_01gd_M_900 x 1100](https://user-images.githubusercontent.com/91599545/197110447-f8c70e0c-a408-40d7-b770-5ad596758096.jpg)

**Comment by thetwopct** [comment]
@GarethAcidWorks Thanks.

- Can you provide a mobile mockup of the banner including thin line + text above the banner
- The text to use above the banner should probably be "Forthcoming Events" - as discussed this section will show events, so " & More" is not relevant. We can refine later with @Charley-Mann if needed.
- If the thin line slide indicators are hard to see over the banners, typically sliders use dots to signify the number of banners, this would be bolder and possibly easier to see - is that worth exploring?

**Comment by thetwopct** [comment]
@GarethAcidWorks 

- I've guessed on the mobile layout - I've had to drop down the arrow position to 55% from the top so they didn't cover the logo. 

![2022-10-23-204508](https://user-images.githubusercontent.com/10615884/197395860-f73288c1-7298-43d7-a06d-101636502d39.jpg)

- When there is only one event the text is "The next CNCF event"

![2022-10-23-204952](https://user-images.githubusercontent.com/10615884/197396010-e026a231-b85e-4dae-98c6-45ab73348e26.jpg)

- 3000ms was a bit too quick for the sliders to move, so I made it 5000ms
- The KubeDay Japan mobile banner provided is the wrong size, can you make it the same as the Kubecon banner, or adjust all banners in future to be a consistent size? As you can see the two sizes don't look good:

![2022-10-23-204709](https://user-images.githubusercontent.com/10615884/197395901-fdb5373c-e989-4cec-8a0f-bccd42b90a80.gif)

**Comment by thetwopct** [comment]
Switched the text above the banner(s) to "Upcoming Event" and "Upcoming Events" if multiple

![2022-10-24-113758@2x](https://user-images.githubusercontent.com/10615884/197449507-f8107a2a-2f9f-43c4-afce-4a24ec513adc.jpg)

![2022-10-24-113822](https://user-images.githubusercontent.com/10615884/197449551-6a837c5a-7700-4b01-9a71-7cef222b84e1.jpg)

**Comment by KTan1226** [comment]
Looks great, thank you!

**Comment by GarethAcidWorks** [comment]
Thanks for this, a couple of refinements on the live version please.

1) Arrows should be positioned in the centre. Currently they are too far down  (See below)
2) Let's just use a fade transition when you click the arrows. The swiping is too clunky / harsh.

Thanks!

<img width="959" alt="Screenshot 2022-10-24 at 23 51 46" src="https://user-images.githubusercontent.com/91599545/197678762-221fe9fc-a9eb-411e-b015-a160ecedef3d.png">

**Comment by thetwopct** [comment]
1. Ok no problems, I am moved it precisely in to the middle (see Figma for measurements using screenshot). I think that makes the Detroit banner look misaligned as the Detroit text is not centred... 

![2022-10-25-121759](https://user-images.githubusercontent.com/10615884/197688735-979c8c22-5abb-40fc-acd2-15eb9cebdc26.jpg)

![2022-10-25-121830@2x](https://user-images.githubusercontent.com/10615884/197688818-c385b4be-703a-468c-ad72-a859ffc379fa.jpg)

2. Added fade effect instead of swipe

![2022-10-25-122115](https://user-images.githubusercontent.com/10615884/197689348-458ba0a3-05c3-472e-a56f-249aa147479c.gif)

**Comment by GarethAcidWorks** [comment]
Thanks, yes we can fine tune the banner graphic a little more to make sure the visual typically works the same way and things feel well layed out.

To add, I noticed on the mobile we have 2 different sizes. (Appreciate Kubecon will be removed anyway now). But the smaller option works better.

From: James Hunt ***@***.***>
Date: Tuesday, 25 October 2022 at 01:24
To: cncf/cncf.io ***@***.***>
Cc: Gareth Davies ***@***.***>, Mention ***@***.***>
Subject: Re: [cncf/cncf.io] Homepage multi-event banner (Issue #604)

  1.  Ok no problems, I am moved it precisely in to the middle (see Figma for measurements using screenshot). I think that makes the Detroit banner look misaligned as the Detroit text is not centred...

[2022-10-25-121759]<https://user-images.githubusercontent.com/10615884/197688735-979c8c22-5abb-40fc-acd2-15eb9cebdc26.jpg>

***@***.***<https://user-images.githubusercontent.com/10615884/197688818-c385b4be-703a-468c-ad72-a859ffc379fa.jpg>

  1.  Added fade effect instead of swipe

[2022-10-25-122115]<https://user-images.githubusercontent.com/10615884/197689348-458ba0a3-05c3-472e-a56f-249aa147479c.gif>

**Comment by thetwopct** [comment]
@GarethAcidWorks Please see the thread above, I have left you a note on the sizing.

> The KubeDay Japan mobile banner provided is the wrong size, can you make it the same as the Kubecon banner, or adjust all banners in future to be a consistent size? As you can see the two sizes don't look good:

![](https://user-images.githubusercontent.com/10615884/197395901-fdb5373c-e989-4cec-8a0f-bccd42b90a80.gif)

**Comment by GarethAcidWorks** [comment]
To add, ‘More’ was to support that this banner can also be used to promote additional important / interesting things if needed. A new big report, promoting the new Instagram etc etc. Ultimately so we show there’s lot’s happening.

Let’s pick it up once we’re back to things this coming week

From: James Hunt ***@***.***>
Date: Sunday, 23 October 2022 at 03:51
To: cncf/cncf.io ***@***.***>
Cc: Gareth Davies ***@***.***>, Mention ***@***.***>
Subject: Re: [cncf/cncf.io] Homepage multi-event banner (Issue #604)

@GarethAcidWorks<https://github.com/GarethAcidWorks> Thanks.

  *   Can you provide a mobile mockup of the banner including thin line + text above the banner
  *   The text to use above the banner should probably be "Forthcoming Events" - as discussed this section will show events, so " & More" is not relevant. We can refine later with @Charley-Mann<https://github.com/Charley-Mann> if needed.
  *   If the thin line slide indicators are hard to see over the banners, typically sliders use dots to signify the number of banners, this would be bolder and possibly easier to see - is that worth exploring?

**Comment by thetwopct** [comment]
As already outlined several times to you, this has been signed off and developed as an event banner. We already have spaces in the mega menu (which is on every page) to highlight reports. The banner and development behind it will allow us to syndicate events across our sub-sites (at your request) and easily update and manage them all from one central place.
