### ISSUE TITLE
Please update the OpenCost GitHub URL to github.com/opencost/opencost

### ISSUE THREAD

**Issue by mattray** [cncf/cncf.io#610]
From URL: https://www.cncf.io/projects/opencost/

The OpenCost project moved out of Kubecost into the OpenCost organization. The main repository for the project is at https://github.com/opencost/opencost, https://github.com/opencost will eventually hold the https://opencost.io website and any other supporting repositories.

**Comment by thetwopct** [comment]
Hi @mattray, all CNCF project data is pulled from the CNCF Landscape, and the data is open source where anyone can contribute. Once the landscape data is updated, the website project data will auto-update within 12 hours or so. 

I have [opened a PR on the landscape](https://github.com/cncf/landscape/pull/2819) to update the Github URL for OpenCost. You can [submit any future updates or edits to the repo directly](https://github.com/cncf/landscape#corrections).

**Comment by thetwopct** [comment]
@mattray The PR was merged and the CNCF Project page information for OpenCost is updated 👍
