### ISSUE TITLE
Create ad banners for next 2 kubecons

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#614]
Could we get ad banners for the next 2 kubecons so we can start them rotating on the homepage?

Dimensions for Event banner images:

Desktop - 2400px x 840px
Mobile - 900px x 1100px

**Comment by GarethAcidWorks** [comment]
Sure will get onto this today.

If anyone has access to the same images used in the current / initial banner artwork that would be helpful.

To add, I know we have some size discrepancies on the mobile version recently. I will do a couple of on screen tests, but I believe the newer, smaller height size should be fine.

From: Chris Abraham ***@***.***>
Date: Thursday, 3 November 2022 at 10:57 PM
To: cncf/cncf.io ***@***.***>
Cc: Gareth Davies ***@***.***>, Assign ***@***.***>
Subject: [cncf/cncf.io] Create ad banners for next 2 kubecons (Issue #614)

Could we get ad banners for the next 2 kubecons so we can start them rotating on the homepage?

Dimensions for Event banner images:

Desktop - 2400px x 840px
Mobile - 900px x 1100px

**Comment by GarethAcidWorks** [comment]
Hi all, these are now done.

I have took a screenshot of the file to show the formatting. @thetwopct fyi on the desktop version the hrz central point (arrows and text) have been nudged upwards slightly, this is a trick to avoid the artwork feeling bottom heavy. Screen shot below. for reference

<img width="1840" alt="Screenshot 2022-11-04 at 6 48 31 PM" src="https://user-images.githubusercontent.com/91599545/200004315-5f3eca00-50b3-4adc-9059-ed15b91ec7af.png">

**Comment by GarethAcidWorks** [comment]
Files here. 

Desktop - 2400px x 840px
Mobile - 900px x 1100px

(Exported as 2x scale)
![CNCF_Banner Canvases_02gd_KCCNC Amsterdam_D_2400 x 840](https://user-images.githubusercontent.com/91599545/200005895-a2294be4-da3d-4fa5-88fe-d18db8ec202b.jpg)
![CNCF_Banner Canvases_02gd_KCCNC Amsterdam_M_900 x 1100](https://user-images.githubusercontent.com/91599545/200005915-d89a8e14-49eb-4db7-9014-7554b82d3320.jpg)
![CNCF_Banner Canvases_02gd_KCCNC Chicago_D_2400 x 840](https://user-images.githubusercontent.com/91599545/200005920-29a51b15-98f4-47d5-adf1-ad6a03573594.jpg)
![CNCF_Banner Canvases_02gd_KCCNC Chicago_M_900 x 1100](https://user-images.githubusercontent.com/91599545/200005927-327b06a6-9df3-43ca-8616-613be5a34605.jpg)

**Comment by thetwopct** [comment]
@GarethAcidWorks Can the NA banner be updated to Chicago, **Illinois**? 👍

**Comment by GarethAcidWorks** [comment]
The design uses 2 difference sizes and weights to emphasize the city, it’s not one line split into 2

From: James Hunt ***@***.***>
Date: Friday, 4 November 2022 at 19:23
To: cncf/cncf.io ***@***.***>
Cc: Gareth Davies ***@***.***>, Mention ***@***.***>
Subject: Re: [cncf/cncf.io] Create ad banners for next 2 kubecons (Issue #614)

@GarethAcidWorks<https://github.com/GarethAcidWorks> Can the NA banner be updated to Chicago, Illinois? 👍

**Comment by GarethAcidWorks** [comment]
@KTan1226 let me know if any other events need creating. For some additional content, I would suggest:

• Detroit photo gallery (link to Flickr)

Perhaps we can pick up an ongoing thread to keep requesting / suggesting content here

**Comment by thetwopct** [comment]
@GarethAcidWorks Thanks for fixing typo (that is what my comment was regarding). But you have now exported the desktop version including the arrows. Can you correct and provide again please. 

As mentioned several times now, this banner area is for events, and is intrinsically linked to the [Events](https://www.cncf.io/events/) category; this is so it can be updated by any staff member, automated, scheduled, and syndicated across multiple sites where event banners needs to be displayed.

**Comment by GarethAcidWorks** [comment]
Fixed. I'm not sure who has discussed this only being for events or what benefit that is. It's a place to push all flagship / engaging pieces of content and keep the page exciting and updated for the community. That's what it was always designed for.

Let's check in with Kristie, Thabang, Charlie etc when folk are back online this week

**Comment by thetwopct** [comment]
Probably from these issues you were an active participant in - https://github.com/cncf/cncf.io/issues/570 https://github.com/cncf/cncf.io/issues/604
