### ISSUE TITLE
Add 'CNCF Presentation Deck Template' to brand guidelines / assets page

### ISSUE THREAD

**Issue by GarethAcidWorks** [cncf/cncf.io#618]
Hi all,

We need to make the new CNCD pres deck easily available for folks.

I have created a small visual and added it to our brand assets / downloads section in Figma. Copy has been created, @Charley-Mann feel free to tweak if you wish.

* Thinking of the user flow, they will need to do a 'save as' rather then work directly on that link location. I'm sure there is an easy method for this.

![macbook_air_m2_chip_midnight_ios15_texture14 copy](https://user-images.githubusercontent.com/91599545/201598475-9847c31b-f434-4e5b-b12a-39097c20b2f3.jpg)

**Comment by GarethAcidWorks** [comment]
Correct copy:
CNCF primarily uses Google Slides as our presentation software. It provides a cloud based, collaborative platform for us to work on and present at speed. You can access the template from the link below. If you have any suggestions or requests for new page templates please contact us here.

**Comment by Charley-Mann** [comment]
Hey @GarethAcidWorks do we need all the text? I was thinking this could be even snappier: 

CNCF uses Google Slides as our presentation software. You can access the template from the link below. If you have any suggestions or requests for new page templates please contact us here.

**Comment by GarethAcidWorks** [comment]
Edits to the deck have been done and can be found here:
https://docs.google.com/presentation/d/19vrk_0WxPiMIO9sQFFi_xvs6s95KGvObiVQFhM3-Dbc/edit#slide=id.g1375398be20_1_10

@onlydole can you confirm if this is the best / most official place to host the deck?
@onlydole let's have that check in to review the template. Any future changes we can make in the cloud and will have zero requirement from the webteam

**Comment by cjyabraham** [comment]
This is done.

**Comment by cjyabraham** [comment]
Re-opening as @ThabangMash has asked for this to be removed from the site. Marking as blocked since it's not ready for the web team to act on. We'll wait for final approvals before pushing live.

**Comment by ThabangMash** [comment]
@cjyabraham please use this approved version https://docs.google.com/presentation/d/1UiSd20CrD3yxo92kKpb5o9g1GmiMjCGWF8ornQG3yzs/edit#slide=id.g187c232c297_0_512

**Comment by thetwopct** [comment]
Picking this up while @cjyabraham is on vacation.

@ThabangMash When I click on that link I get the following access denied message:

![2022-11-16-133643@2x](https://user-images.githubusercontent.com/10615884/202103217-51485230-332e-4f61-ba5d-f44a266a2983.jpg)

Does it need to be set up to be shared on the document?

**Comment by thetwopct** [comment]
Thanks @KTan1226 for the invite to the document. I'm a bit of a novice when it comes to Google Slides - if I choose Share > Share with anyone with link as Viewer, will this suffice? I guess the guest user would then need to make a copy of the document to edit/update as they want. Is this correct? Or is it better to download the slides as a PPTX and then offer that as a download?

**Comment by thetwopct** [comment]
OK thats [added](https://www.cncf.io/brand-guidelines/#downloads-and-fun-stuff)

![2022-11-17-005620@2x](https://user-images.githubusercontent.com/10615884/202256895-19d73ee6-4fc5-47c5-9bbb-711e2f399732.jpg)

**Comment by KTan1226** [comment]
TYSM!
