### ISSUE TITLE
ACF/Blocks should only load assets when the block is used in post

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#619]
Carried on from work on from issue [Theme Tidying WordPress 6.1](https://github.com/cncf/cncf.io/issues/615).

We have now pivoted to using ACF for custom gutenberg blocks (from React-based blocks) in preparation for new web agency joining the team and for quicker creation of custom blocks for site elements like Reports.

There is an issue that CSS/JS from any ACF custom block created is being loaded on _every_ page of the site. This is causing significant overhead on every page - so this needs to be fixed before many custom blocks can be properly implemented. The following filter can be used to stop them loading on every page:

`add_filter( 'should_load_separate_core_block_assets', '__return_true' );`

But this has knock on effects with theme.json styling and specificity. So some time is needed to update our theme and make sure all styles are still available and working as they should.

**Comment by cjyabraham** [comment]
This is deployed
