### ISSUE TITLE
Make link hover styles consistent in footer

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#62]
Currently the "Privacy Policy" under the newsletter form gets an underline on hover and the links in the Copyright blurb don't.  Maybe none of them should get an underline since, with the external icons, it's clear that they are links?  At least they should be consistent.

**Comment by thetwopct** [comment]
Have made consistent. Rule - header and footer (inc newsletter) no underline on hover. Body/content - underline on hover.
