### ISSUE TITLE
Add blog post about new brand

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#620]
[Figma blog post](https://www.figma.com/file/kCUoOKDAyPMp79eMILoYKi/CNCF's-new-brand-look?node-id=1%3A432&t=stN7hSG4ZnBtPoar-1)
[WIP blog post](https://www.cncf.io/wp/wp-admin/post.php?post=81383&action=edit)

- [ ] revisit/update content @GarethAcidWorks 
- [ ] update images to fit 900px blog formatting (blog posts not the same as pages) @GarethAcidWorks 
- [ ] finalise/sign off copy? Charley? TBD
- [ ] export images text and add to blog post - James? Chris? TBD

The blog talks about the merchandise store, which is almost finished, so we should launch the piece as soon as the store is relaunched, tracking under #589 
Part of the design layout calls for rounded style headshots, which is a custom block style also used on the revised Phippy page, currently blocked by #619

**Comment by cjyabraham** [comment]
The moment for this has now passed.
