### ISSUE TITLE
KCCNC NA 22 Transparency Report 

### ISSUE THREAD

**Issue by GarethAcidWorks** [cncf/cncf.io#621]
Linked from https://github.com/cncf/workflow/issues/503 

Getting this job into Github as design & content are now* working on it. 

Current status:

Charley is working on copy & the google doc
Gareth is flowing in Detroit theme and copying latest content into figma
Gareth & Emilia are copying data across to available charts

Will progress here as we get further on. Thanks!

### IMAGES
- [x] Upload images to production and pull in image ids
- [x] Check correct images being used
- [x] Lazy load images
- [x] Alt text is descriptive
- [x] Image dimensions w x h

### LINKS
- [x] Add all links where needed
- [x] Check anchor links
- [x] Broken links
- [x] Title text

### TEXT
- [x] Check max widths
- [x] Copy and paste text in spell checker
- [x] Check brand spelling, capitals, + not and/&

### CONFORMANCE
- [x] Run through accessibility checker
- [x] Run through W3C checker
- [x] Browser Testing - last 2 versions
- [x] Check Lighthouse score

### GO LIVE
- [x] Merge
- [x] Add Social Share image / report cover
- [x] Post preview link in Slack/here

### POST LIVE
- [ ] End user data has been hidden, with "coming soon" text in place, update once confirmed
- [x] Highlights video embed has been hidden, need to add YouTube video once done
- [ ] Sponsor logos are being pulled in from LFE, better to host them locally in CNCF and also update markup

**Comment by thetwopct** [comment]
Web team needs 4-7 working days to output a Tier 2 report. 

- Tue November 29th - Start coding.
- Wed December 7th - Finish coding. Gives 48 hours for review, feedback, changes (is this enough?)
- Fri December 9th - Launch

(Note: Fri December 2nd is 5 weeks since the event, isn't 5 weeks after the event the deadline? To launch on December 2nd, we would need design / content by Tuesday 22nd  November.)

**Comment by Charley-Mann** [comment]
@thetwopct - we have until Dec 9th, but we'd like to get it out earlier if we can!

@GarethAcidWorks – let's get as much as we can done this week

**Comment by thetwopct** [comment]
Anyone know the latest with the Detroit highlights video - can we get it on YouTube today?

**Comment by KTan1226** [comment]
Hi @thetwopct - here is the final video link for you  https://youtu.be/Oi4ckvfF0w0.

@GarethAcidWorks - just making sure you have all of the edits on the co-located event infographics. I'll post them here as well:

- WASM day demographics - fix percentages to be 48% men, 38% prefer not to answer
- BackstageCon - fix percentages to be 52% men, 18% women
- CloudNativeSecurityCon - let's leave as is
- Please change PromCon to PrometheusDay (https://events.linuxfoundation.org/prometheus-day-north-america/)
- Prometheus Day demographics - fix percentages to be 52% men, 10% women, 38% prefer not to answer
- EnvoyCon - Attendees per region doesn't add up to 100; update in comments
- Kubernetes Batch - updating the percentages in the attendee breakdown; update in comments
- Graphic is missing for Kubernetes on Edge Day

Once incorporated, these will be final

Please let me know if there is anything else that you need from me at this stage. Thanks!

**Comment by GarethAcidWorks** [comment]
I actually pinged Erik today. He has a 95% finished version there was some
minor polishes to make last time we spoke.

We can use that for now and replace with the final version in YT if needed
-- 

Gareth Davies

*Founder, Creative & Production*



+971 (0) 58 158 4876

www.acidworks.net

Instagram <https://www.instagram.com/acid_social>

LinkedIn <https://www.linkedin.com/company/acidworks>

**Comment by thetwopct** [comment]
Report has been deployed 
https://www.cncf.io/reports/kubecon-cloudnativecon-north-america-2022-transparency-report/
