### ISSUE TITLE
Google Search Page - Latest CNCF logo to be applied

### ISSUE THREAD

**Issue by GarethAcidWorks** [cncf/cncf.io#623]
Hi all, quick job for Chris / James.

I noticed the logo is old when you do a search for CNCF in google. See below. Just needs swapping out. As it's a square format we should probably use our square version. See below:
<img width="1115" alt="To Update" src="https://user-images.githubusercontent.com/91599545/202406502-84b4dfe9-1117-40ca-889f-a9ef044daccd.png">
<img width="384" alt="Screenshot 2022-11-17 at 1 23 10 PM" src="https://user-images.githubusercontent.com/91599545/202408068-25ec02ba-2304-4422-88b5-a3c01b555144.png">
![CNCF_Secondary Logo](https://user-images.githubusercontent.com/91599545/202408141-f493cbe8-ba0c-425d-a73b-3af4333bddb7.svg)

**Comment by thetwopct** [comment]
I've updated our Schema.org settings with the stacked logo. There was no logo previously set, so this may be a Google thing where we don't have much control over it. We will see.

![2022-11-17-163719@2x](https://user-images.githubusercontent.com/10615884/202410629-9ca5d258-4d8d-4c56-bfdd-b776650e84b5.jpg)
