### ISSUE TITLE
The two middle countup block items should not open in new tab

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#63]
Only open in new tabs links that go to an external site.  In the countup block currently, the middle two icons point to pages on cncf.io so we can keep them in the same tab.

**Comment by cjyabraham** [comment]
It seems now that all links open in the same tab.  Can you make it so that the internal links open in the same tab while the external links still open in a new tab?

**Comment by thetwopct** [comment]
Cannot reproduce
