### ISSUE TITLE
Hook up Contribute and Glossary feedback buttons to our GA4 property

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#632]
Follow [advice from here](https://github.com/google/docsy/issues/1302#issuecomment-1301550895)

**Comment by cjyabraham** [comment]
I've added an event modification for our GA4 property following [the instructions here](https://github.com/kubernetes/website/issues/37657#issuecomment-1301548361) and set up [a GA4 exploration](https://analytics.google.com/analytics/web/#/analysis/p321825497/edit/CVw1qCcTS4Kb7LINeJQ6XA) to watch incoming `page_helpful` events.

**Comment by cjyabraham** [comment]
Looks like this isn't working since we aren't using gtag.js. I will wait for an update on [the docsy issue](https://github.com/google/docsy/issues/1302).

**Comment by cjyabraham** [comment]
Looks like [this is now possible](https://github.com/google/docsy/issues/1302#issuecomment-1812833959).

**Comment by cjyabraham** [comment]
I've made the code change and this is now sending events properly. I should check back in 2 weeks to see the data and relate it to stakeholders.

**Comment by kumarankit999** [comment]
How are we achieving this solution for this issue!

**Comment by chalin** [comment]
@cjyabraham - [Docsy 0.8.0](https://github.com/google/docsy/releases/tag/v0.8.0) is out. It's the first official release with the changes highlighted. (FYI) /cc @nate-double-u
