### ISSUE TITLE
Unable to import NLTK.

### ISSUE THREAD

**Issue by Sandip-Ayush** [cncf/cncf.io#634]
Hi,
 When I have tried to tried to download stopword , getting below error in output in my personal laptop.
Please help me anyone to resolve the issue.
Code:
import nltk
nltk.download('stopwords')

Output: 

nltk.download('stopwords')
[nltk_data] Error loading stopwords: <urlopen error [WinError 10060] A
[nltk_data]     connection attempt failed because the connected party
[nltk_data]     did not properly respond after a period of time, or
[nltk_data]     established connection failed because connected host
[nltk_data]     has failed to respond>
Out[8]: False

**Comment by cjyabraham** [comment]
Looks like this was opened on the wrong repo. This repo is for [the CNCF website](https://www.cncf.io/).
