### ISSUE TITLE
Annual Report 2022 render issues on iPad

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#638]
Try and iPad with 810px width to get the following render issues: “Season of Docs” going outside the frame and column widths seem sub-optimal on the other:

<img width="480" alt="Screen Shot 2022-12-15 at 9 49 47 AM" src="https://user-images.githubusercontent.com/463160/207939420-50de2061-0f3a-4941-b2c9-d9e37100a2f5.png">
<img width="461" alt="Screen Shot 2022-12-15 at 9 44 37 AM" src="https://user-images.githubusercontent.com/463160/207939424-e34702cc-d175-4dc9-9ce2-2e06c9629d81.png">

**Comment by bhavyastar** [comment]
Are you still working on this issue? If not, Could you please assign this to me? @thetwopct

**Comment by thetwopct** [comment]
@bhavyastar you can open a PR on the repo if you wish to work on this or any other issue. Thank you.

**Comment by GarethAcidWorks** [comment]
Hi all, we have created a new style sheet for mobile I will extend this to tablet devices.

Tagging onto this specific screen, do LMK if there is any others to review.

I will of course also look through on my own ipad as well.

**Comment by cjyabraham** [comment]
Let's take this points as notes going in to future reports. There's little value at this point fixing them on past reports.
