### ISSUE TITLE
Compact mobile homepage view

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#64]
See how the current site compares with the new site:
<img width="326" alt="Screen Shot 2020-05-11 at 9 15 03 AM" src="https://user-images.githubusercontent.com/463160/81515719-f6d09200-9367-11ea-800f-4389a27efc4e.png">
<img width="343" alt="Screen Shot 2020-05-11 at 9 14 47 AM" src="https://user-images.githubusercontent.com/463160/81515725-fafcaf80-9367-11ea-88a8-8d1c2311aff9.png">

Can we reduce the height of the main image and make the hello bar text smaller?  The hello bar text currently looks like it's competing with the CNCF logo.

**Comment by thetwopct** [comment]
I've made the hello bar text smaller. 

I want to come back to the hero image when we re-look at the home page - this is just a placeholder and inserted using background image CSS. It needs to either be a new hero custom block or using the text on image block we already have (srcset, better mobile responsiveness etc).

**Comment by thetwopct** [comment]
I've made a new image hero block that is height adjustable in the editor, uses srcset, and on mobile reduces the height by 25%. I've set it up on home page of dev, let me know if this looks OK to you on mobile. There also should not be any image jank/"FOUC", so if you could look out for that too, thanks!

**Comment by cjyabraham** [comment]
looks great!
