### ISSUE TITLE
Missing SEO Framework meta tags

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#642]
Occasionally the cached homepage does not contain the SEO Framework meta tags. This is a problem in that social sites will not be able to get the data during these times. 

I've started [a convo with the plugin author here](https://wordpress.org/support/topic/meta-block-sometimes-not-inserted/). I also talked with Pantheon about it but they deny it could have anything to do with the Pantheon cache.

**Comment by cjyabraham** [comment]
I've been checking this regularly but haven't seen them missing for a while. I'll close but let's keep an eye on it.

**Comment by cjyabraham** [comment]
It seems sometimes PageSpeed tests the homepage and finds no meta Description so gives us lower SEO points. [I've asked the plugin author for another update on a fix](https://wordpress.org/support/topic/meta-block-sometimes-not-inserted/page/2/#post-16891662).

**Comment by thetwopct** [comment]
FYI, this is also [an issue on the LF Events site](https://pagespeed.web.dev/analysis/https-events-linuxfoundation-org/7fpnpmtaen?form_factor=mobile).

**Comment by cjyabraham** [comment]
We can try out [this snippet](https://wordpress.org/support/topic/meta-block-sometimes-not-inserted/page/2/#post-16907621) provided by the author or just wait for his next release of the plugin which will include the fix.

**Comment by cjyabraham** [comment]
I've deployed a temporary fix which we should revert once the new version of TSF is released. Let's see if it does fix the problem. If all looks good we could also deploy on LFEvents.

**Comment by cjyabraham** [comment]
Plugin upgraded and temp fix is reverted so I'll call this resolved.
