### ISSUE TITLE
Get head in order for online Store

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#647]

**Comment by thetwopct** [comment]
Before:

<img width="1262" alt="Screenshot-2023-03-14 --13 27 07@2x" src="https://user-images.githubusercontent.com/10615884/224914352-749a3645-1769-42ab-b7fd-277ca46c2a4b.png">

<img width="973" alt="Screenshot-2023-03-14 --13 37 12@2x" src="https://user-images.githubusercontent.com/10615884/224916206-323bde94-86db-4478-a2ff-fb38e47be6d0.png">

After:

<img width="1256" alt="Screenshot-2023-03-14 --14 23 14@2x" src="https://user-images.githubusercontent.com/10615884/224925462-b246192a-b043-4263-af44-75754152a7d2.png">

<img width="498" alt="Screenshot-2023-03-14 --14 22 31@2x" src="https://user-images.githubusercontent.com/10615884/224925343-260ddf22-dfc6-449b-aded-6c9f97681493.png">

The Shopify speed test I assume takes in to account customers real speeds - which are affected by all our tracking scripts (plus plugins tracking scripts). Will revisit this in the future to see if the percentage updates in time (there's doesn't seem to be a way to trigger a re-test)

I have started a new issue to check #687 which may also gives improvements (some of the Shopify Apps are super heavy on performance)
