### ISSUE TITLE
Links at the end of the article are shifted and do not correspond to the text shown

### ISSUE THREAD

**Issue by juangascon** [cncf/cncf.io#650]
From URL: https://www.cncf.io/telecom-user-group/
Each link sends to the page whose title is the next link:

- "CNCF Telecom User Group" sends to "https://github.com/cncf/cnf-testbed"
- "CNF Testbed on GitHub" to "https://docs.google.com/presentation/d/1Bci-rzXnVqlvT2hhSXCBawtsKf8HURC2K4kJSlnB43Q/"
- "Google slides on CNF conformance" to "https://github.com/cncf/telecom-user-group"

**Comment by thetwopct** [comment]
That's a good spot - thanks for the feedback! The page has now been updated.
