### ISSUE TITLE
Date widget is badly formatted in admin

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#651]
See date widget which pops up for an Event. This may actually be a question for [the plugin author](https://wordpress.org/support/plugin/post-meta-controls/).
<img width="437" alt="Screen Shot 2023-01-31 at 11 29 04 AM" src="https://user-images.githubusercontent.com/463160/215665619-291e5977-2ceb-4230-b029-ce063e8180ff.png">

**Comment by thetwopct** [comment]
I've inspected this and I can't see anything from our side that's causing this. I suspect the underlying DatePicker library has been updated in Gutenberg. It doesn't look like the author is working on this plugin anymore - the last update was now over 2 years ago. @cjyabraham do you want to open an issue as you have asked for the authors help before? 

As we rely on this plugin heavily access CNCF and LFE we may have to fix the issue ourselves. The complete plugin is on Github including build process, so we could fork it and update the WordPress modules it relies on.

**Comment by cjyabraham** [comment]
[I've opened an issue with the plugin author](https://wordpress.org/support/topic/date-widget-broken/).

We could fork and fix ourselves, or we could just avoid using the date widget. We don't use it on LFEvents and use just a text field for dates, which seems to work adequately:
<img width="288" alt="Screen Shot 2023-02-01 at 1 57 39 PM" src="https://user-images.githubusercontent.com/463160/215973121-d0c19ca2-878d-495f-84e7-4e8ddb0a34b7.png">

**Comment by cjyabraham** [comment]
I swapped in a text field instead to keep it consistent with the Events site.
