### ISSUE TITLE
RSS author name tidying

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#652]
The RSS feed currently displays like this in readers:

![2023-02-01-124354@2x](https://user-images.githubusercontent.com/10615884/215961432-99e5a199-c53f-49d4-b595-daba9223be99.jpg)

and within the post itself:

![2023-02-01-124424@2x](https://user-images.githubusercontent.com/10615884/215961481-0106761a-2ffc-4c19-bb94-54b18b060d8d.jpg)

I am pretty sure there is a WordPress filter to update the name of the author of the post within the RSS feed - we could make use of the guest author field to properly use that information and general posts should be perhaps published from "CNCF" user.

**Comment by cjyabraham** [comment]
@thetwopct LMK if this solves the problem in your reader in the coming days...
