### ISSUE TITLE
Tier 3 report page broken on mobile

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#654]
URL - https://www.cncf.io/reports/kubernetes-annual-report-2021/

Seems to be pushing page out of bounds. 

![image](https://user-images.githubusercontent.com/10615884/217617314-8e21d12c-90e4-4d75-bb2d-77880733be7c.png)

**Comment by cjyabraham** [comment]
It's this one line causing the problem:
<img width="402" alt="Screen Shot 2023-02-09 at 11 22 03 AM" src="https://user-images.githubusercontent.com/463160/217717210-538e12a9-a30d-49d5-9759-fe91bfa3f575.png">

**Comment by cjyabraham** [comment]
What's the correct way to deal with this? Just allow it to overflow outside the frame without horizontal scroll? Alternatively we could force a line break?

**Comment by thetwopct** [comment]
Not sure how the first option would work; I'd prefer the second option anyway. 

From memory something like this should do it.

```
white-space: pre-wrap;
word-wrap: break-word;

```
