### ISSUE TITLE
Upgrade site to PHP8

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#656]
- Our current version PHP 7.4. PHP 7.4 has reached its end of life on November 28th, 2022.
- Pantheon now support PHP8.
- PHP 8 receives security updates until 26 Nov 2023.
- WordPress does not officially support PHP8 yet, although they say they are "mostly compatible"
- Plugins have varied PHP8 support, we would need to test each one

Test and evaluate the ability to update.

**Comment by cjyabraham** [comment]
I may need to upgrade to PHP 8 in order to take advantage of php-yaml which seems installed on [the PHP 8 version](https://v82-php-info.pantheonsite.io/) of Pantheon but not [our current PHP 7.4 version](https://v74-php-info.pantheonsite.io/).

**Comment by cjyabraham** [comment]
I will try upgrading to php 8.1, as per the recommendation on [this page](https://make.wordpress.org/hosting/2023/05/15/is-wordpress-compatible-with-php-8/).

**Comment by cjyabraham** [comment]
All upgraded.
