### ISSUE TITLE
Make search form styles more consistent

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#66]
The mobile menu (on iPhone) search and desktop forms are subtly different in several ways: rounded edges on button, rounded search box, alignment of text in box etc.  Is there a reason for this?  If not can we make them more consistent.  I think both should have left-aligned text and buttons that are consistent with the rest of the site, so no rounded corners.  Note that on Android the edges don't appear rounded.
<img width="395" alt="Screen Shot 2020-05-11 at 9 27 44 AM" src="https://user-images.githubusercontent.com/463160/81516299-00f39000-936a-11ea-90c8-73ff70336684.png">
<img width="286" alt="Screen Shot 2020-05-11 at 9 27 52 AM" src="https://user-images.githubusercontent.com/463160/81516305-05b84400-936a-11ea-99db-8bc58ebe09d1.png">

**Comment by thetwopct** [comment]
Well that's strange. Seems like it's a Safari/iOS webkit thing. Never experienced that before. Have added an override that should fix it, but will want to keep an eye out for this when doing iOS testing later.
