### ISSUE TITLE
Launch CTO Summit NA 2022 Report

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#663]
[Workflow issue ](https://github.com/cncf/workflow/issues/572)

[Current PR](https://github.com/cncf/cncf.io/pull/670)

PR page for review https://pr-670-cncfci.pantheonsite.io/reports/cto-summit-na-2022/

Checklist:

### IMAGES
- [x] Upload images to production and pull in image ids
- [x] Check correct images being used
- [x] Lazy load images
- [x] Alt text is descriptive
- [x] Image dimensions w x h

### LINKS
- [x] Add all links where needed
- [x] Check anchor links
- [x] Check for broken links
- [x] Set title text on links

### TEXT
- [x] Check max widths against Figma
- [x] Copy and paste text in spell checker
- [x] Check brand spelling, capitals, + not and/&

### CONFORMANCE
- [x] Run through accessibility checker
- [x] Run through W3C checker
- [x] Browser Testing - last 2 versions
- [x] Check Lighthouse score

### GO LIVE
- [x] Merge
- [x] Add Social Share image / report cover

### GATED
- [x] Setup gate landing page with form
- [x] Setup hidden report page
- [x] Post report preview link in Slack/Workflow issue

### GA
- [x] Post final permalink link in Slack/Workflow issue

**Comment by thetwopct** [comment]
The PR has a few things to fix:

1) The event was in October 2022, so guessing the copyright notice might need to update?

![image](https://user-images.githubusercontent.com/10615884/221747226-b04d7ea8-da27-4b72-94c0-5505a20eaba3.png)

2) Badly capitalised words

![image](https://user-images.githubusercontent.com/10615884/221746830-70e018aa-e979-47e1-8753-46aa58c8e770.png)

3) On mobile lack of spacing here:

![image](https://user-images.githubusercontent.com/10615884/221746706-89872cf9-73e8-4804-80b6-bd95ecd5d52a.png)

4) Lack of spacing under See All:

![image](https://user-images.githubusercontent.com/10615884/221746911-9db152ab-1add-4a1d-a633-75718f8d7bb8.png)

5) Long word pushes out screen:

![image](https://user-images.githubusercontent.com/10615884/221747028-e9af7a91-b998-4062-b756-4f3a79ae74ea.png)

**Comment by cjyabraham** [comment]
A few more:
1. There should be no bottom line below Priyanka on the CTO SUMMIT COMMITTEE LIST
2. Spacing above quote mark is too large
3. Quote icons are smaller than they should be
4. Quotes should not have " around them in addition to the styling

**Comment by thetwopct** [comment]
OK have pushed updates: 

- Changed various company logos from PNG to SVGs
- Removed whitespace from CNCF logo
- Fixed long words pushing out screen on mobile 
- Fixed appendix text
- Fixed inconsistent spacing
- Fixed incorrect character encoding
- Added link to Uptycs
- Switched Creative Commons logo to better resolution file
- Fixed See More spacing on mobile
- Fixed Discussion Topics spacing on mobile
- Removed quote marks inside large quote mark container
- Fixed spacing in quote marks (retroactively applied to last CTO report too)
- Fixed mobile spacing on quote marks (retroactively applied to last CTO report too)
- Removed end dividing line in Committee List (retroactively applied to last CTO report too)
- Changed Copyright date from August 2022 (before event) to October 2022 (let me know if another date should be used)
