### ISSUE TITLE
Use placeholder person image for people with missing image

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#67]
Do you think it would look better to have a placeholder shadow person for this case:
<img width="791" alt="Screen Shot 2020-05-11 at 9 44 08 AM" src="https://user-images.githubusercontent.com/463160/81516891-0f42ab80-936c-11ea-919d-9797387aeda2.png">

**Comment by thetwopct** [comment]
I've already uploaded an optimised Speakers Bureau avatar as part of UM, and I was hoping to tap in to that to replicate here. But doesn't look like it's possible, so I've added a new upload for the Site Options where this can be set. But let's also aim to improve the data so there are no blanks.
