### ISSUE TITLE
Update End User Membership Details

### ISSUE THREAD

**Issue by onlydole** [cncf/cncf.io#673]
On the [End User](https://www.cncf.io/enduser/) page, in the "Pick a Membership Level" section, we would like the following items updated: 

- [ ] KubeCon should be fully spelled out to be, KubeCon + CloudNativeCon
- [ ] Add "per year" to the **Supporter** and **Silver** sections where the total of tickets is mentioned.
> 5 KubeCon + CloudNativeCon in-person tickets per year (2 tickets for organizations with <300 employees)
> A total of 10 KubeCon + Cloud NativeCon in-person tickets per year. 
- [ ] The last bullet point in the **Supporter** section needs to be updated (end user price is $8k & $21k silver price comparison is old pricing). Please update to say: 
> End User Recruiting Booth at KubeCon + CloudNative at Startup Level pricing. 

<img width="1248" alt="Screenshot 2023-03-06 at 8 14 39 AM" src="https://user-images.githubusercontent.com/117500/223170207-154664b3-1f5b-4b32-b12f-44d2697b00b4.png">

**Comment by thetwopct** [comment]
@onlydole I've updated the table - [here's a preview of the changed table on our dev instance](https://dev-cncfci.pantheonsite.io/enduser/#membership), let me know if its good and I put live.

**Comment by onlydole** [comment]
Thank you, @thetwopct! This looks great to me and can go live 🚀

**Comment by thetwopct** [comment]
Alrighty! Deployed and live
(p.s. I added an anchor link so you can jump direct to the membership table - https://www.cncf.io/enduser/#membership)
