### ISSUE TITLE
"View Profile" doesn't quite work on People views

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#68]
I'm not sure I like how only some of the [People](https://dev-cncfci.pantheonsite.io/people/technical-oversight-committee/) have "View Profile" buttons.  It makes the ones who don't have the button seem somewhat deficient or like there's missing data.  Here are a few alternate design options:
1. Have a button for all People and just show the short bio version in the case where a person doesn't have a long bio
2. Don't use a "View Profile" button.  Instead use a "Show more..." link at the end of the short bio for those that have a long bio

I think I like option 2 the best.

Separately, I don't think the whole person card should highlight on hover as you have done with [Webinars](https://dev-cncfci.pantheonsite.io/webinars/).  I think you should just not have a hover effect.

**Comment by thetwopct** [comment]
I though we discussed getting rid of that button anyway?

It doesn't seem like the excerpt and the content of each person is consistent, so their short bio could be completely different to their long bio. So 2) doesn't make sense to me.

1) also doesn't make sense to me as then we get scenarios like this where the click results in nothing new other than a tiny modal with repeated information. 
![20200511211612-Technical Oversight Committee | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/81607467-a5a6b980-93cc-11ea-9c8b-de1746ffe1d7.jpg)

The marketing part of my brain just says "Add the missing data" as it's only a few people needed to make it consistent, and it's better for the organisation to have decent data. 

Let's discuss and finalise tomorrow.

**Comment by thetwopct** [comment]
As discussed, let's add the missing data for 2x people it affects. There are also some TOC Contributors who have some errant data so possibly just earmark a data check and clean for People as part of site transfer. Should be 10 mins work.

**Comment by cjyabraham** [comment]
I have requested the missing data.  What's the "errant data" you are referring to?

**Comment by thetwopct** [comment]
![20200520012758-Technical Oversight Committee | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/82391418-24d56680-9a39-11ea-8ec5-812a0efd46dc.jpg)

Just need a quick bit of tidying to get rid of the duplicate company names here

**Comment by cjyabraham** [comment]
Cool.  I've just removed that extra data from the live site so it won't trouble us again.
