### ISSUE TITLE
CTO Summit NA Report: CC Edit

### ISSUE THREAD

**Issue by onlydole** [cncf/cncf.io#684]
Hello, team - 

I received a request to change the CC on this page to **March 2023** and **Copyright 2023**. Can I get your help with updating this?

> https://www.cncf.io/reports/cto-summit-na-2022

<img width="235" alt="CTOSummitNA22CC" src="https://user-images.githubusercontent.com/117500/223851981-89e53953-819e-4656-b46d-d2a3201bff08.png">

**Comment by cjyabraham** [comment]
That's done.
