### ISSUE TITLE
Update Intuit logo for CTO Summit 2022 Reports

### ISSUE THREAD

**Issue by onlydole** [cncf/cncf.io#685]
Hello, team - can you please update the Intuit logo with the most recent SVG version?

Pages that need updating: 

- https://www.cncf.io/reports/cto-summit-eu-2022/
- https://www.cncf.io/reports/cto-summit-na-2022/

![intuit-logo-super-blue Intuit_Logo_SuperBlue-2022](https://user-images.githubusercontent.com/117500/224748100-408bc1f4-bf44-430f-8909-222960a75f57.svg)

**Comment by cjyabraham** [comment]
this is done

**Comment by onlydole** [comment]
Thank you!
