### ISSUE TITLE
KCCN EU CTO Summit Copy and Logo Updates

### ISSUE THREAD

**Issue by onlydole** [cncf/cncf.io#688]
Howdy, team! This isn't directly for the CNCF site, but for the [KCCN EU 2023 site](https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/apply-cto-summit/). 

Can I get help with adding the CNCF and FinOps Foundation logos (FinOps SVG included) and have it link to our respective sites (via https://cncf.io and https://www.finops.org)

![logo-full-blue](https://user-images.githubusercontent.com/117500/225105589-19a7cd93-fb84-4932-bc30-ca6111764bf1.svg)

I'd also like help updating the copy to read as follows:

> CNCF's CTO Summit is a must-attend event for cloud native leaders looking to stay at the forefront of the industry. CNCF is partnering with FinOps Foundation on this summit's topic of **FinOps: Building a Culture of Cost Management**. FinOps is an evolving cloud financial management discipline and cultural practice that enables organizations to get maximum business value by helping engineering, finance, technology, and business teams to collaborate on data-driven spending decisions. 
> 
> Take advantage of this opportunity to join the conversation and connect with other technology leaders driving innovation and change in the industry. 
> 
> Please fill in the following form to reserve your spot:

**Comment by cjyabraham** [comment]
Sure. How does this look? https://events.linuxfoundation.org/kubecon-cloudnativecon-europe/apply-cto-summit/

**Comment by onlydole** [comment]
Thank you, @cjyabraham! 

One nit that I have - can you center-align the logos both horizontally and vertically? Otherwise, I think this looks great!

**Comment by onlydole** [comment]
This looks great! Thank you, @cjyabraham
