### ISSUE TITLE
Falco logo - old version of the logo (needs updating)

### ISSUE THREAD

**Issue by jsalinas29** [cncf/cncf.io#690]
From URL: https://www.cncf.io/projects/falco/

Can you please replace the old Falco logo? 

Here is the correct logo: https://github.com/cncf/artwork/blob/master/examples/incubating.md#falco-logos

**Comment by cjyabraham** [comment]
Thanks for reporting. Would you please submit a PR to [the CNCF landscape repo](https://github.com/cncf/landscape) with the new logo? The logos on the CNCF site get pulled from there.
