### ISSUE TITLE
Remove accounts from GA4 account after May 31

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#691]
Remove [okaforhilda1@gmail.com](mailto:okaforhilda1@gmail.com) and [andrea@buoyant.io](mailto:andrea@buoyant.io) from GA4 Analytics account when their term is over on May 31, 2023.

**Comment by nate-double-u** [comment]
Andrea may need access after this point if we do a second term of this project (and we are planning to). Will update closer to the date.

**Comment by cjyabraham** [comment]
Hi @nate-double-u, just pinging you here about this issue. Are there any accounts that could be removed from our GA4 property at this point?

**Comment by nate-double-u** [comment]
Yes, we can remove:
* andrea@buoyant.io
* okaforhilda1@gmail.com
* avantika2809@gmail.com

Thanks for following up!

**Comment by cjyabraham** [comment]
Ok, that's done.
