### ISSUE TITLE
New Ambassadors page

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#692]
We need to improve the content on the Ambassadors page to include the following:
- new logo to the right on top of page
- show the latest 3 blog posts tagged with "Ambassador" for the author category
- show latest tweets from ambassador twitter account
- a link to a  new page for requirements that is separate from ambassadors listing page
- a listing of the 152 new ambassadors; have filters for location, expertise type, projects
- the popup for each ambassador will have bio and reason why they want to be an ambassador
- we could use a Phippy headshot for those that don't provide headshot

Tasks:
- [x] Chris to get official list of projects to use for survey
- [x] Alex to update artwork repo with [new logo](https://github.com/cncf/artwork/blob/master/examples/other.md#cncf-ambassador-logos)
- [x] Katie/Charley to provide Google Doc of copy for pages
- [x] Katie to connect with Jessie about tagging blog posts with "Ambassador" author category so that we can do a "Show All" link to all of them

Apr 5 - Survey completed
Apr 17 - New page is live
Apr 19 - New Ambassadors announced at Kubecon keynote

**Comment by cjyabraham** [comment]
@thetwopct Currently the LF | Newsroom block can only filter posts by Category. I feel we need to also be able to filter by Author Category. We can then use it in the End User page in addition to here.
<img width="343" alt="Screen Shot 2023-04-03 at 12 42 11 PM" src="https://user-images.githubusercontent.com/463160/229421180-5e7bf7f5-a958-4718-992c-d177fd1feb51.png">

**Comment by k8tgreenley** [comment]
@cjyabraham here is the udpated copy for the page:

https://docs.google.com/document/d/1Q8PKVj_PBEoZtB6tHJARkmgASroMJhuTFjR8Oxfufi8/edit#

**Comment by cjyabraham** [comment]
Page is now live: https://www.cncf.io/people/ambassadors/
