### ISSUE TITLE
Create hub page and link from all footers

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#695]
Create new hub page on CNCF.io that lists all subsites in the CNCF web ecosystem. Link to it from all footers to promote discoverability among all sites.

Footer design assets needed:
- [x] Desktop footer on cncf.io site
- [ ] Mobile footer on cncf.io site
- [ ] Desktop footer on subsite like [glossary](https://glossary.cncf.io/)
- [ ] Mobile footer on subsite like [glossary](https://glossary.cncf.io/); note we need to accommodate the lang selector here

Hub design should show off the following sites, grouped by category (all TAG sites together, for example):
- [Main cncf.io site](https://www.cncf.io/)
- [Landscape](https://landscape.cncf.io/)
- [Community](https://community.cncf.io/)
- [Jobs](https://jobs.cncf.io/)
- [Store](https://store.cncf.io/)
- [Contribute](https://contribute.cncf.io/)
- [Glossary](https://glossary.cncf.io/)
- [AppDelivery](https://appdelivery.cncf.io/)
- [MaturityModel](https://maturitymodel.cncf.io/)
- [Sustainability](https://sustainability.cncf.io/)

Each site could have its logo, a short description, and a link to its repo (encouraging contributions or issues).

- [x] We need both a desktop and mobile design for this hub page.

**Comment by cjyabraham** [comment]
Design attached:
<img width="904" alt="Screenshot 2023-03-21 at 20 52 41" src="https://user-images.githubusercontent.com/463160/227645217-f75c5fd4-ede8-448a-9e8d-4f2c4eb2e87a.png">

**Comment by GarethAcidWorks** [comment]
Hi all, i have spent some time trying to figure out a neat and tidy solution for handling our hub links. We need multtiple links of course and also the option to scale and navigate as the site landscape grows.

I have made a [short video](https://www.loom.com/share/ec8e4b44e01549679e9992ce647ca168) to support the recommendation below:

Desktop - 'Micro arrows that cause minimal distraction from the page flow.
Mobile - Swipe to see more

<img width="1048" alt="Screenshot 2023-04-04 at 4 04 00 PM" src="https://user-images.githubusercontent.com/91599545/229785877-156d382f-a435-425a-80f1-f40a1a501082.png">

**Comment by cjyabraham** [comment]
Hub pages is live: 
Footer implementation split into [separate issue](https://github.com/cncf/cncf.io/issues/715).
