### ISSUE TITLE
CTO Summit - KubeCon + CloudNativeCon NA 2023 Copy

### ISSUE THREAD

**Issue by onlydole** [cncf/cncf.io#703]
Howdy, team! 

Can I get help with updating the [ KubeCon + CloudNativeCon NA 2023](https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/apply-cto-summit/) form copy to read: 

> Join us at the CNCF's CTO Summit, an exclusive end user event designed for cloud native leaders and innovators. This highly anticipated gathering provides a unique opportunity to network with industry experts, exchange ideas, and learn about the latest trends in cloud native technology. Don't miss your chance to be part of this prestigious event—register today by completing the form below and secure your spot, shaping the future of the cloud native ecosystem.

**Comment by cjyabraham** [comment]
Sure, that's done: https://events.linuxfoundation.org/kubecon-cloudnativecon-north-america/apply-cto-summit/
