### ISSUE TITLE
Update links for "CNCF Operator Framework" project

### ISSUE THREAD

**Issue by tlwu2013** [cncf/cncf.io#704]
From URL: https://www.cncf.io/projects/operator-framework/

Please help update the links in:

* “View Project Website” button links to project website to https://operatorframework.io/
* The github icon links to https://github.com/operator-framework

**Comment by cjyabraham** [comment]
Hi @tlwu2013 . Thanks for the issue. Would you please submit a PR to the landscape repo with these updated links? The CNCF site pulls from that repo. You'll need to edit [the landscape.yml file here](https://github.com/cncf/landscape/blob/master/landscape.yml#L5048).
