### ISSUE TITLE
Better website icon?

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#71]
Is there a better icon we can use for websites?  Isn't this the Safari logo?
<img width="263" alt="Screen Shot 2020-05-11 at 10 28 01 AM" src="https://user-images.githubusercontent.com/463160/81518958-3603e080-9372-11ea-86a1-7cf71b586cfa.png">

**Comment by dankohn** [comment]
https://www.google.com/search?q=link+icon&rlz=1C5CHFA_enUS857US857&oq=link+icon&aqs=chrome..69i57j0l7.1211j0j1&sourceid=chrome&ie=UTF-8
--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>

**Comment by thetwopct** [comment]
Had a mind blank on that one, was thinking spinning globes; link icon obvious now 👍

**Comment by thetwopct** [comment]
![20200511230416-Staff | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/81616627-bf9bc880-93db-11ea-85cf-dd8791245015.jpg)
