### ISSUE TITLE
is-style-no-margin class not successful at eliminating margins around an image

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#710]
It currently seems to be overridden by another style. You can inspect it on [this draft page on the live site](https://www.cncf.io/?page_id=86129). Here's what I'm seeing in the styles:
<img width="208" alt="Screen Shot 2023-04-09 at 4 19 21 PM" src="https://user-images.githubusercontent.com/463160/230764916-e27a4050-f676-42aa-b566-95457b168661.png">

**Comment by thetwopct** [comment]
The code has been updated and seems to have fixed the issue based on the page supplied

<img width="1302" alt="Screenshot-2023-04-16 --22 32 16@2x" src="https://user-images.githubusercontent.com/10615884/232320129-016c3201-af7a-48fe-a053-1cb111687d07.png">

**Comment by cjyabraham** [comment]
Yep, looks good. Thanks.
