### ISSUE TITLE
Embed products from Shopify store collections in to WordPress

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#713]
As used on revised Phippy page, could also be added to Project singular pages

<img width="730" alt="Screenshot-2023-04-16 --23 59 39@2x" src="https://user-images.githubusercontent.com/10615884/232325135-c7240ce5-c0e8-4a30-9d57-3f4c2f63ae7b.png">

Related to [S5/O2/Init 4](https://github.com/cncf/workflow/issues/793)

**Comment by thetwopct** [comment]
This has now been put live on all projects who have matching URL slugs in the CNCF Store, and [Phippy page](https://www.cncf.io/phippy/) has been updated to include 6 products from the store on the page

**Comment by cjyabraham** [comment]
Sweet!
