### ISSUE TITLE
Implement hub button on main site footer and subsite footers

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#715]
@thetwopct Could you implement the new "All CNCF Sites" button on the CNCF main site and one subsite, say, the Glossary? I can then propagate it to the other subsites. [The design is in figma](https://www.figma.com/file/zF4U8kpTeexkFdAAA2j9X0/Hub?node-id=0%3A1&t=C3qPUT4PNp1Y70VL-1). The hub page it should link to [is here](https://www.cncf.io/all-cncf/).

Reminder for myself: implement that language dropdown consistently across all subsite mobile footers.

- [x] www.cncf.io
- [x] glossary [PR](https://github.com/cncf/glossary/pull/1979)
- [x] contribute [PR](https://github.com/cncf/tag-contributor-strategy/pull/390)
- [x] maturitymodel [PR](https://github.com/cncf/cartografos/pull/59)
- [x] app-delivery [PR](https://github.com/cncf/tag-app-delivery/pull/384)
- [x] sustainability [PR](https://github.com/cncf/tag-env-sustainability/pull/82)
- [x] runtime [PR](https://github.com/cncf/tag-runtime/pull/65)
- [x] security [PR](https://github.com/cncf/tag-security/pull/1064)
- [x] jobs
- [x] community [request](https://help.bevy.com/hc/en-us/requests/8506)
- [x] store

**Comment by cjyabraham** [comment]
Main site button is deployed.

**Comment by thetwopct** [comment]
Store now has the hub button, and with that, let's close! 👍 🎉
