### ISSUE TITLE
Your issue

### ISSUE THREAD

**Issue by katsuoz** [cncf/cncf.io#718]
From URL: https://www.cncf.io/announcements/2023/04/17/new-gold-member-hitachi-joins-the-cloud-native-computing-foundation/

The year is incorrectly indicated. I think the correct year is "April 17, 2023".
![image](https://user-images.githubusercontent.com/1970831/232670729-9b3914b6-e8ed-45d1-9e6b-6630f39e93c9.png)

**Comment by cjyabraham** [comment]
That's fixed. Thank you.
