### ISSUE TITLE
Tweak outline of tiles across site

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#719]
Audit outline of tiles across the site and update all to option 2 below.

As per @GarethAcidWorks :

The below has 3 tests:

1. 20% opacity black outline (Too heavy, not needed)
2. 10% opacity black outline (Im ok with this)
3.  No outline (im ok with this)

<img width="890" alt="Screenshot 2023-04-19 at 10 45 22" src="https://user-images.githubusercontent.com/91599545/233036518-86c9d65e-f2a4-4c62-b217-dd254bb12429.png">

**Comment by thetwopct** [comment]
We have a lot of outlines (a sample below) - do they all need a consistent treatment? Certainly some are darker than others. @GarethAcidWorks 
  
Home

<img width="1275" alt="Screenshot-2023-04-21 --17 33 10@2x" src="https://user-images.githubusercontent.com/10615884/233614891-c6613fef-36b2-4d3f-a373-670f96419a13.png">

<img width="432" alt="Screenshot-2023-04-21 --17 33 35@2x" src="https://user-images.githubusercontent.com/10615884/233614956-9e739083-06a4-45fd-af7f-3abf5925d0ff.png">

Menu

<img width="430" alt="Screenshot-2023-04-21 --17 37 01@2x" src="https://user-images.githubusercontent.com/10615884/233615659-79f758fd-b8eb-46f9-89a7-ea5b697ae193.png">

<img width="431" alt="Screenshot-2023-04-21 --17 37 23@2x" src="https://user-images.githubusercontent.com/10615884/233615711-e768be38-3703-40f7-84ae-a4050761e61a.png">

Who We Are

<img width="648" alt="Screenshot-2023-04-21 --17 33 59@2x" src="https://user-images.githubusercontent.com/10615884/233615026-7adff9be-c2fd-49d9-bccc-65facbfb0a7d.png">

Training (CKA + others)

<img width="1278" alt="Screenshot-2023-04-21 --17 38 41@2x" src="https://user-images.githubusercontent.com/10615884/233615975-1d8beb32-a224-48ef-bbc0-af7edfc524d0.png">

<img width="1284" alt="Screenshot-2023-04-21 --17 39 29@2x" src="https://user-images.githubusercontent.com/10615884/233616102-4e24c822-0a58-450b-a929-10377ba4bbde.png">

End Users / Pricing

<img width="1270" alt="Screenshot-2023-04-21 --17 40 40@2x" src="https://user-images.githubusercontent.com/10615884/233616326-db921da7-6be4-4d45-915c-17efbc6d7a1b.png">

Case Study Single

<img width="481" alt="Screenshot-2023-04-21 --17 41 43@2x" src="https://user-images.githubusercontent.com/10615884/233616524-a22943f2-36f4-4fd4-94c6-2c8de16f174e.png">

<img width="1254" alt="Screenshot-2023-04-21 --17 42 01@2x" src="https://user-images.githubusercontent.com/10615884/233616567-39c700e1-65cd-40fc-aee3-b081d7d75287.png">

Webinars

<img width="844" alt="Screenshot-2023-04-21 --17 42 41@2x" src="https://user-images.githubusercontent.com/10615884/233616713-60c92889-ceb5-4603-9d08-1b28a136f9d7.png">

<img width="1255" alt="Screenshot-2023-04-21 --17 43 01@2x" src="https://user-images.githubusercontent.com/10615884/233616767-0770a146-73f5-4940-a22b-f143f985f66a.png">

KubeWeekly

<img width="614" alt="Screenshot-2023-04-21 --17 43 15@2x" src="https://user-images.githubusercontent.com/10615884/233616825-639348de-f94a-43ab-b181-0abd45b84f10.png">

<img width="854" alt="Screenshot-2023-04-21 --17 43 30@2x" src="https://user-images.githubusercontent.com/10615884/233616863-2e653a18-d2a8-46c3-89d2-7ee4f8a7c894.png">

Phippy

<img width="1278" alt="Screenshot-2023-04-21 --17 44 00@2x" src="https://user-images.githubusercontent.com/10615884/233616983-8d00d152-28ed-4625-8981-946a26c1f8aa.png">

Reports

<img width="847" alt="Screenshot-2023-04-21 --17 44 45@2x" src="https://user-images.githubusercontent.com/10615884/233617105-aea8e2d4-f383-4d54-9dc4-4cc3464260d7.png">

In the News

<img width="370" alt="Screenshot-2023-04-21 --17 45 32@2x" src="https://user-images.githubusercontent.com/10615884/233617240-43560cdf-071d-4318-9ee2-ec80884930eb.png">

**Comment by GarethAcidWorks** [comment]
Thanks for pulling all of these together, testing and removing as many variations as possible today, be right back

**Comment by GarethAcidWorks** [comment]
Hi all, i have compared all of the settings for our boxes for the following:

• Outlines
• Drop Shadows
• Corner Radius

With different size and functionality for different modules... indeed not all should follow 1 rule.
With that said there is some styles that can be merged and our stylesheet lists generally polished up.
[Here is a link](https://www.figma.com/file/FARMrOYHOfrFRi9iakYRDA/CNCF_Website-Files?node-id=8425%3A16349&t=jogCsRGt7kUs8FLO-1) to the comparison if you need to see it.

Screen shot below:
![Outline Review](https://user-images.githubusercontent.com/91599545/234206482-251d7151-2945-44b2-b2f0-bdfdd37326c7.jpg)

**Comment by GarethAcidWorks** [comment]
But in the short term... this middle option for the hub is fine.

<img width="608" alt="Screenshot 2023-04-25 at 11 34 36 AM" src="https://user-images.githubusercontent.com/91599545/234206873-029f4436-d9ac-4764-91d6-c2506c5b81b5.png">

**Comment by cjyabraham** [comment]
For your test in figma, could you change the background color to the color we use on the site #fdfdfd ? So that we can see what the shadows/borders will actually look like in practice?

**Comment by cjyabraham** [comment]
Drawing from Gareth's design analysis and other inconsistencies I see, I suggest the following:

All tiles that go 3 across the desktop screen could be standardized. Currently, some have 3px border radius, some 5px. All have box shadow `0px 2px 5px rgba(0, 0, 0, 0.1)`. Some have border `1px solid #eaeaea` others have no border. **Suggest we give them all the same 5px border radius and no border lines.**

For tiles that go 2 across the desktop screen, some have 5px border radius, some 10px. Some have `has-animation-scale-2` some have no animation. **Suggest we give them all the same 10px border radius and animation.**

We currently have `is-style-box-shadow` that can be applied to Group blocks to make them stand out. It uses border `1px solid #d0d0d0` which is fairly dark. **Gareth recommends dropping the drop-shadow on these.**

**I suggest we introduce another style `is-style-box-shadow-light` with a lighter border `1px solid #eaeaea` but keep the normal drop shadow. This can be used on the [All CNCF page](https://www.cncf.io/all-cncf/) where we are listing multiple items in group blocks and don't want such a pronounced border.** This style is currently used in the case studies highlights blocks on [a case study](https://www.cncf.io/case-studies/form3/) so we'd be keeping consistent with that.

**Suggest we change the Charter box on [Who We Are](https://www.cncf.io/about/who-we-are/) to use `is-style-box-shadow`.** That current grey box style isn't used anywhere else.

**Suggest we dim the black border around [news logos](https://www.cncf.io/news/) to something like #d0d0d0**

**Comment by cjyabraham** [comment]
Most of these ideas and more have been deployed.
