### ISSUE TITLE
Remove Upcoming webinars hover effect

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#72]
I think [this hover effect](https://dev-cncfci.pantheonsite.io/webinars/) isn't necessary and we should just drop it and just make the webinar title clickable?

**Comment by thetwopct** [comment]
There are 2 elements at play here - a block link which makes the whole element a link, and the hover effect. I quite like the hover effect, and I thought we discussed on the call last week about putting that in more places. Let's discuss tomorrow to confirm.

**Comment by cjyabraham** [comment]
looks like this is done
