### ISSUE TITLE
Add Tai (new Phippy character)

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#722]

**Comment by thetwopct** [comment]
Waiting for a revised Phippy family photo from @GarethAcidWorks to revise issues with shadows on https://www.cncf.io/phippy/

**Comment by GarethAcidWorks** [comment]
Just needs the latest Phippy asset dropping into Phippy page to avoid the shadow issue.

I would also recommend adding a cover image for this video as it's a bit odd with out saying anything on the cover. This is super rough to get the idea over 

<img width="1076" alt="Screenshot 2023-04-28 at 9 08 31 PM 2" src="https://user-images.githubusercontent.com/91599545/235212681-e20e8287-ff52-44de-81b8-3c50e5cee4c5.png">

**Comment by thetwopct** [comment]
The family image is now updated. 

To update the YouTube cover I think it has to be sent to Libby @GarethAcidWorks then it will update on the site automatically. Happy for you to take care of this.
