### ISSUE TITLE
Live streams section in "Join" and "End User" pages is outdated

### ISSUE THREAD

**Issue by aliok** [cncf/cncf.io#727]
https://www.cncf.io/about/join/

Latest in "Live streams" section is from January 20, 2022.

I would remove the "Live streams" section in the "Join" page anyway :)

**Comment by cjyabraham** [comment]
Thanks for the suggestion. I've forwarded it on to our Dir of Marketing for consideration.

**Comment by cjyabraham** [comment]
A decision has been made to switch to using [this Members playlist](https://www.youtube.com/playlist?list=PLj6h78yzYM2Mh0PGvD6jcn_MSNlvg4cWn) for the LiveStream section. When I switch to use that playlist it pulls in some private videos, so we will need to have the shortcode ignore any private vids:

<img width="1297" alt="Screen Shot 2023-05-10 at 10 12 10 AM" src="https://github.com/cncf/cncf.io/assets/463160/8100141f-d610-400a-a4af-106f0e7c5f00">
