### ISSUE TITLE
Consistent date tags

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#73]
On [Webinars](https://dev-cncfci.pantheonsite.io/webinars/data-services-for-cloud-native-workloads/) you use this for a date:
<img width="343" alt="Screen Shot 2020-05-11 at 11 11 07 AM" src="https://user-images.githubusercontent.com/463160/81520902-2f786780-9378-11ea-8ad9-4e6b66ab057a.png">

For all upcoming dates I think we should make consistent use of that tag and color.  So we could use it for [Events](https://dev-cncfci.pantheonsite.io/events/microsoft-build-2020/) too and use some other color for the Host tag.

**Comment by thetwopct** [comment]
I wasn't really thinking of those skew boxes like that, rather they are highlighting important information on a page. But to be consistent as above, we would also need to use them on [News posts](https://dev-cncfci.pantheonsite.io/announcements/2020/04/30/cloud-native-computing-foundation-announces-helm-graduation/) so we'd need to lose the "Posted on" text, if that's OK?

**Comment by cjyabraham** [comment]
I actually prefer to leave the "Posted on" style for news and any content that is in the past.  The date on these items is less important.

Here, I was thinking of just webinars/events coming up in the future could use this date style.  That was the reasoning behind the style we used on the current site.  It highlights upcoming dates as if they are calendar sticky notes.  Does that work for you?

**Comment by thetwopct** [comment]
I've added the skew box to the singular events page. I did try adding it inside the event box we generate using the logo and custom event colours, but it just didn't work that well and clashes with some colours. Let me know if you want me to revisit that, or it's consistent enough without this.

**Comment by cjyabraham** [comment]
I think it's good enough.
