### ISSUE TITLE
CSS bug in the Subscribe for Updates section

### ISSUE THREAD

**Issue by Abhinavxox** [cncf/cncf.io#732]
### Description

In the home page, in the `Subscribe for updates` section. The language selection box has a CSS bug. Languages in the options are not visible.

#### How to reproduce

In the `Subscribe for updates, event info, webinars, and the latest community news` section, If we go to choose the langauge for subscription mails. We wont be able to see the languages available as the `text color` as well as the `background color` is `white`.

#### Screenshots

[CNCF.webm](https://github.com/cncf/cncf.io/assets/72064600/6b1d97bd-f0e8-4c24-ad16-0cad62fcb38a)

**Comment by cjyabraham** [comment]
Thanks for the report. What OS are you on?

**Comment by Abhinavxox** [comment]
> Thanks for the report. What OS are you on?

I am on Ubuntu 22.04. Can i fix this?

**Comment by cjyabraham** [comment]
Sure. Go for it. Thanks.

**Comment by cjyabraham** [comment]
This is deployed. Thanks for your help @Abhinavxox.
