### ISSUE TITLE
Spin up Glossary for TODO group

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#736]
Adapt the CNCF Glossary and reskin it for TODO group.

Some notes:
- TODO GROUP isn't affiliate with CNCF and has its own brand, however, CNCF uses TODO Group all the time as a place to recommend new members learn about open source best practices
- We don't need a custom design for this, just adapt the CNCF Glossary skin to the TODO brand as best as possible while keeping the colors accessible (see #735)
- url can be [ospoglossary.todogroup.org](http://ospoglossary.todogroup.org/) and [glossary.todogroup.org](http://glossary.todogroup.org/)
- i18n support is needed
- Site can be stored in https://github.com/todogroup/glossary
- Initial content [can be found here](https://github.com/todogroup/ospology/blob/main/ospo-book/chapters/glossary.md)

(cc @caniszczyk)

**Comment by GarethAcidWorks** [comment]
First draft done, [working file is here](https://www.figma.com/file/aOgcKnW06V7y6vklqvMcWE/TODO_Glossary?type=design&node-id=0%3A1&t=RdoZfsYzzxIGnwBe-1)

**Comment by cjyabraham** [comment]
First pass at this is done and team knows to reach out for additional support.
