### ISSUE TITLE
The floating go to top Button partially covers the submit an issue with this page.

### ISSUE THREAD

**Issue by parmishh** [cncf/cncf.io#746]
The floating go to top Button partially covers the submit an issue with this page. That makes it sometimes click on go to top rather than submit an issue with this page link.

https://github.com/cncf/ambassadors/assets/91942072/d96406f4-a2b6-47c4-96c5-c5bc15c412cb

I have made some changes now it doesn't overlap:

https://github.com/cncf/ambassadors/assets/91942072/20bf5283-cf97-42b2-98d8-b266f6d2e7cd

If this issue needs to be addressed please assign it to me.

**Comment by thetwopct** [comment]
Thanks for the great spot @parmishh !

A simple solution - on the spacer we added to allow for the back to top button change the size from [70px to 90px](https://github.com/cncf/cncf.io/blob/d5a3061e9b6e54a7d68a014a5a4957e9ef8320a8/web/wp-content/themes/cncf-twenty-two/components/footer.php#L171).

You can submit a PR for this, or we can update it in our next update (probably in a few hours) - thanks!
