### ISSUE TITLE
CNCF Presentations Subsite

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#752]
As discussed with @castrojo and @caniszczyk we want to create a new subsite to hold community-submitted presentations to provide this as a resource to the community.

### Data Storage

We can store these in the https://github.com/cncf/presentations repo but re-organize the repo to have a main `presentations.json` file (similar to our [people.json file in the people repo](https://github.com/cncf/people/blob/main/people.json)) that stores the full listing and all metadata for each presentation. 

Metadata could include the following:
- Presenter's name
- Presenter's GitHub
- Presenter's Twitter
- Description
- Date of presentation
- Video url
- Slide deck filename (to be stored in the repo) or external url
- Relevant CNCF projects covered in the presentation

Community members could submit their presentations themselves via PR or we can have someone who submits presentations in batches, say, after a Kubecon has passed, so we have the most useful set of presentations possible. If needed, we could create a web-based form for accepting submissions, to make the process as easy as possible.

We could also possibly import past online programs presented on [the Community site](https://community.cncf.io/). We currently feature those on [the CNCF Online Programs page](https://www.cncf.io/online-programs/).

### Subsite

We can set up a subsite presentations.cncf.io with a main page that lists presentations in reverse chronological order with filters for project, date, free-text search, language, similar to [how we list reports here](https://www.cncf.io/reports/). Clicking on a presentation will show the video, metadata and allow for download of the slides, similar to how our past [online programs are presented](https://www.cncf.io/online-programs/cloud-native-live-building-serverless-applications-using-spin-and-webassembly/).

We can link the presenter to any person we have in our [people repo](https://github.com/cncf/people/blob/main/people.json) by keying off the GitHub account. So Ambassadors and CNCF Staff could automatically have their presentations listed on [their profiles](https://www.cncf.io/people/ambassadors/?p=adriana-villela), for example. And we can link to their profile from a presentation page.

### Promotion

We can promote this service to speakers at Kubecon and other conferences after the conference has completed and encourage them to upload their presentation.

We can also provide instruction and other info on the presentations.cncf.io site itself.

**Comment by cjyabraham** [comment]
Thinking more about this, I'm concerned that this json format of storing the presentations won't scale well past a couple thousand entries. If it becomes very successful, we could be in trouble.

Instead, we could just store the whole thing in a WordPress database. We wouldn't be able to leverage the GitHub workflow for submissions but we could stand up a user-friendly form instead. Submissions could be moderated before publishing live. I think this would serve us better long term. We could provide other forms for people who want to update their presentation entry or request it be removed.

**Comment by thetwopct** [comment]
To reduce initial friction of the idea, would it be an idea to start with JSON/static site and then move to WordPress/other if/when the site has issues with scale?

**Comment by cjyabraham** [comment]
What initial friction are you referring to? Why wouldn't we just do it the scalable way from the start? I'd also be concerned with community reaction if we were up and running on GitHub and then told everyone we're moving to a closed database...

**Comment by cjyabraham** [comment]
Closing in favor of [a clean and revised issue](https://github.com/cncf/cncf.io/issues/757).
