### ISSUE TITLE
Osano Cookie Banner low-contrast issue on mobile

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#753]
[Lighthouse](https://pagespeed.web.dev/analysis/https-www-cncf-io/pew8fg8vqu?form_factor=mobile) is flagging a link and text in the cookie banner as having poor contrast on mobile devices. [WebAims](https://webaim.org/resources/contrastchecker/?fcolor=000000&bcolor=BFF3FF) checker says the combination passes (as does AXE).

Should we ignore this warning from Google?

This [version](https://pagespeed.web.dev/analysis/https-www-cncf-io-projects/5s7ljehukv?form_factor=mobile) of the report shows a screenshot:

![Screenshot-2023-06-30 --22 07 58](https://github.com/cncf/cncf.io/assets/10615884/bfda506c-14a2-42b4-96ec-727db19fd2e7)

If we wanted to try and solve:

- Up its size to 18px (from 16px)
- Make the link black/another color instead of pink
- make the body font slightly bigger (14px instead of 13px) and removing the condensed letter spacing (f the body text continues to be flagged, or if the link being in that text is causing it to be flagged)

**Comment by cjyabraham** [comment]
It seems like Lighthouse is right in this case and the others missed it. Like you suggest, maybe we just keep font sizes the same as on desktop, which passes?

**Comment by cjyabraham** [comment]
I don't understand why the body text is flagged. Black on blue should have a contrast ratio of 17. The pink on blue does need fixing. I can up the size of the text to 19px which is the minimum I think.

**Comment by cjyabraham** [comment]
This is deployed and appears to have moved [our Accessibility score back to 100](https://pagespeed.web.dev/analysis/https-www-cncf-io/69z30v2cof?form_factor=mobile).
