### ISSUE TITLE
Add role to People listings

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#754]
The TOC and Governing Board have special designations for certain people. We should create separate fields for each since there are some people who are on both the TOC and GB. The current set of special roles needs validating and is below:

**GB Roles**
- Arun Gupta - Chairperson
- Christoph Blecker - Kubernetes Rep
- Jeremy Garcia - Silver Member Rep
- Justin Dustzadeh - Gold Member Rep
- Liz Rice - Silver Member Rep
- Mohammad Zebetian - Gold Member Rep
- Stephen Chin - Gold Member Rep
- Thomas Di Giacomo - Silver Member Rep

**TOC Roles**
- Emily Fox - TOC Chair
- Richard Hartmann - Developer Seat Rep

The role needs displaying somewhere on the people tile and on the popup:
<img width="292" alt="Screen Shot 2023-07-01 at 10 48 34 AM" src="https://github.com/cncf/cncf.io/assets/463160/207e98d4-272b-43e9-ba09-1bd17ccc9baa">

**Comment by cjyabraham** [comment]
@taylorwaggoner @poconnor1 would you please validate the roles and wording of the roles above?

**Comment by poconnor1** [comment]
confirmed. The above is correct. Thank you!
