### ISSUE TITLE
Try to make form styles consistent

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#76]
We have several forms affected by different style sheets:
- [bulk message speakers](https://dev-cncfci.pantheonsite.io/speakers/email-matching-speakers/?sf_action=get_data&sf_data=all&_sft_cncf-language=arabic) - gravity forms css
- [individual speakers contact form](https://dev-cncfci.pantheonsite.io/speaker/meddchiheb/) - gravity forms and UM css
- [contact form](https://dev-cncfci.pantheonsite.io/about/contact/) - our own css
- [SB register form](https://dev-cncfci.pantheonsite.io/speakers/register/) - UM css

Is it possible to make these form styles more consistent.  I don't think it needs to be perfect.

Note: It's possible to [turn off the gravity forms css](https://dev-cncfci.pantheonsite.io/wp/wp-admin/admin.php?page=gf_settings) if it is getting in the way.

**Comment by thetwopct** [comment]
I've updated them, the main difference I can see is the Label style. I like the boldness of [bulk message speakers](https://dev-cncfci.pantheonsite.io/speakers/email-matching-speakers/?sf_action=get_data&sf_data=all&_sft_cncf-language=arabic) - if you agree I can copy across to the others?
If there is anything else let me know.

**Comment by cjyabraham** [comment]
I like the labels on the [contact form](https://dev-cncfci.pantheonsite.io/about/contact/) best.  They seem a bit more elegant than the bold on [email matching speakers](https://dev-cncfci.pantheonsite.io/speakers/email-matching-speakers/?sf_action=get_data&sf_data=all&_sft_cncf-language=arabic).  What do you think?  Could you also match the color of the text inside the input boxes on the contact form?

**Comment by cjyabraham** [comment]
Also, can you make the input boxes stretch to the full width of the container on the [matching speakers](https://dev-cncfci.pantheonsite.io/speakers/email-matching-speakers/?sf_action=get_data&sf_data=all&_sft_cncf-language=arabic) form, the way it is on the other forms?

**Comment by thetwopct** [comment]
- Fixed input box colour (UM styles aren't autoprefixed and also override GF 🙄)
- Made label styles consistent - including required star
- Date field forced 100% width - we need to test that, GF don't offer sizing options for this field so there could be a reason for that (date picker)
- Padding around input elements made more consistent.

The Funding select box width is controlled by Gravity Forms (just style it to be large). I'd rather not force GF in case we need the control later.

**Comment by cjyabraham** [comment]
I tweaked a couple of things and increased the width of the funding box.  I think we can close this for now.
