### ISSUE TITLE
CNCF Graduated Projects by timeline 

### ISSUE THREAD

**Issue by sysnet4admin** [cncf/cncf.io#766]
Hi CNCF team, 

I hope you are doing well.
One of my colleague (@Saim-Safdar and Katie) recomend to put this image in [CNCF page - 
Our graduated projects](https://www.cncf.io/projects/)
If you do not mind, please look at it. This proposal better for the CNCF webpage?

**[ Normal Version ]**

![CNCF Graduated Projects (July 23, 2023)-wo-me](https://github.com/cncf/cncf.io/assets/29163931/20ab0ac1-a103-45b1-8ad4-f6102f884d8d)

**[For Black Theme ]**

![CNCF Graduated Projects (July 23, 2023)-wo-me-bg](https://github.com/cncf/cncf.io/assets/29163931/e65e42c1-737f-4127-b64a-7302c561944b)

In my personal view, after `Our graduated projects` or before `Our incubating projects` or any place is good for me. 
And I appreciate that you provide really valuable docs and information all the times. . :) Have a nice day and week. 

**FYR** **RAW info Sheet**: https://docs.google.com/spreadsheets/d/1PCAARw1Sy1kmnQcpTHTuHDSBl_PU9P6MjMy3NLmgkwE

**Comment by Saim-Safdar** [comment]
Thanks for leading this effort @sysnet4admin, while a discussion with @onlydole on Slack, we are thinking to have this to be visible [here](https://www.cncf.io/projects/), also is there any new project needed to be added or become a part of it soon, we are looking forward to hearing opinions of other contributors.

**Comment by sysnet4admin** [comment]
@thetwopct Sometimes I use Figma but it doesn't heavy job. So I use just PowerPoint.  
`Self-update` sounds perfect :) Due to I've experienced many liars who are GPT friends. 
If you need any files or information, feel free to let me know.

**Comment by cjyabraham** [comment]
We have [a similar and larger idea here](https://github.com/cncf/cncf.io/issues/790) so I will close this issue.
