### ISSUE TITLE
Twitter's logo has been changed to X

### ISSUE THREAD

**Issue by parmishh** [cncf/cncf.io#769]
Change all instances of the Twitter logo to the X logo using [their new brand toolkit](https://about.twitter.com/en/who-we-are/brand-toolkit).

- [x] CNCF
- [ ] Subsites, all 378 of them

-------

## Status of subsites

- [Glossary](https://github.com/cncf/glossary/pull/2566) 
- [Contributors](https://github.com/cncf/tag-contributor-strategy/pull/550)
- [Maturity Model](https://github.com/cncf/cartografos/pull/62)
- CNCF Store - the Theme we use (Dawn) does not have the X logo within it yet. I would prefer to [wait for an update](https://github.com/Shopify/dawn/issues/3087) to the theme rather than customise the theme just for this logo.

**Comment by parmishh** [comment]
Hi @cjyabraham 
I did a little try it looks like this as in the video on changing: If its required to change let me know , I would like to make a PR.


https://github.com/cncf/cncf.io/assets/91942072/b19dc16d-9836-4149-a66e-34ae2dea675a

**Comment by cjyabraham** [comment]
Sounds good. Please go ahead and submit a PR. Thanks.

**Comment by cjyabraham** [comment]
Looks like [the brand toolkit is out](https://about.twitter.com/en/who-we-are/brand-toolkit).

**Comment by cjyabraham** [comment]
@thetwopct can you get me a "boxed-twitter" version of the X logo to replace [this one](https://github.com/cncf/cncf.io/blob/main/web/wp-content/themes/cncf-twenty-two/images/social/boxed-twitter.svg)?

**Comment by cjyabraham** [comment]
Deployed to CNCF and have opened [a new issue for the subsites](https://github.com/cncf/cncf.io/issues/804)
