### ISSUE TITLE
Style the gravity forms success message

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#77]
You can test sending forms on [my speaker](https://dev-cncfci.pantheonsite.io/speaker/cabraham/).  Can we style this message:
<img width="554" alt="Screen Shot 2020-05-12 at 11 24 36 AM" src="https://user-images.githubusercontent.com/463160/81635216-49cb4780-9443-11ea-83b2-46f25ba43eee.png">

**Comment by thetwopct** [comment]
Quick round up of success messages: 

Speakers Bureau
Success message inline with Contact Form success message

![20200516204437-Chris Abraham | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/82128827-0f9cd580-97b6-11ea-98bc-7a08d72115d9.jpg)

Speakers Bureau
Error message feedback is inline

![20200516205604-Chris Abraham | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/82129012-a918b700-97b7-11ea-8d50-69d010fd56a9.jpg)

Speakers Bureau Bulk Email 
Success
![20200516211205-Email Matching Speakers | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/82129351-e5e5ad80-97b9-11ea-8779-6f111095771e.jpg)

Contact Form
Success Message

![20200516205801-Contact | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/82129053-ef6e1600-97b7-11ea-92b1-f5be61a6d30e.jpg)
(This message is inside the form block, so adopts the coloured container)

Contact Form
Error message is using HTML required for feedback

![20200516205708-Contact | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/82129036-d06f8400-97b7-11ea-8c12-b194ebd6f707.jpg)

Newsletter
Success

![20200516210008-Contact | Cloud Native Computing Foundation](https://user-images.githubusercontent.com/10615884/82129095-3a882900-97b8-11ea-9677-f41071b4016a.jpg)

**Comment by cjyabraham** [comment]
One final suggestion, could you bold the Newsletter and Contact form messages so they stand out a bit more?  And/or make the green border a bit thicker?

**Comment by thetwopct** [comment]
I've made the frame 2px and increased font-weight. Not sure if really needed, as the forms are replaced by the message, but users aren't going to miss it now 🤓
