### ISSUE TITLE
Create jump button style

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#780]
I think we could benefit from a "jump" button style for pages like [this events page](https://www.cncf.io/events). Perhaps we just need a white-background-style button, similar to the jump buttons at the top of [this report](https://www.cncf.io/reports/kubecon-cloudnativecon-europe-2023/). Other ideas welcome.

**Comment by cjyabraham** [comment]
Can we apply to [the events page](https://www.cncf.io/events/) button?

**Comment by thetwopct** [comment]
> Can we apply to [the events page](https://www.cncf.io/events/) button?

Done https://www.cncf.io/events/#upcoming-events
