### ISSUE TITLE
Update the Training landing Page with missing trainings

### ISSUE THREAD

**Issue by huats** [cncf/cncf.io#782]
Some training are missing from the https://www.cncf.io/certification/training/

Thanks for adding them

- Kubernetes and Cloud Native Essentials (LFS250) (to be inserted after Kubernetes Fundamentals)

Description:
Calling all Kubernetes and cloud native beginners! Are you interested in the world of Kubernetes and You look to better understand the world of  cloud native?

This course will dive into cloud native technologies, as well as share how it is driven by innovation. 

This course aligns with the requirements for the [Kubernetes and Cloud Native Associate](https://www.cncf.io/certification/kcna/) exam from the Cloud Native Computing Foundation.

Difficulty:  Beginner
Length: Online Self-Paced
Who It's For: Developers, system administrators, architects or managers  who want to get started with Kubernetes and the Cloud Native ecosystem and gain more skills
Cost: $ 99
Link to register: https://training.linuxfoundation.org/training/kubernetes-and-cloud-native-essentials-lfs250/

- GitOps: Continuous Delivery on Kubernetes with Flux (LFS269) (To be inserted after Managing Kubernetes Applications with Helm)

Description:
What is GitOps? Join us for this course as it will deep dive into GitOps principles and practices. You’ll also learn how to implement them on Kubernetes using Flux, including some integration with CI!

Difficulty: Intermediate
Length: Online Self-Paced
Who It's For: Developers and system administrators who want to be able to start deploying cloud native applications using GitOps practices and Flux.
Cost: $ 299
Link to register: https://training.linuxfoundation.org/training/gitops-continuous-delivery-on-kubernetes-with-flux-lfs269/

- Container Fundamentals (LFS253) (To be inserted after the GitOps one)

Description:
Containers have invaded the IT world over the last few years, mainly thanks to the growth in Kubernetes adoption. Understanding how they work, how they interact with the network and storage and how to build them is therefore essential.This course will explore container fundamentals and guide you through various container runtimes.

Difficulty: Intermediate
Length: Online Self-Paced
Who It's For: Developers, system administrators, architects or managers  who want to get started with containers and learn how to containerize applications.
Cost: $ 299
Link to register: https://training.linuxfoundation.org/training/containers-fundamentals/

**Comment by cjyabraham** [comment]
This is now updated: https://www.cncf.io/certification/training

**Comment by huats** [comment]
Amazing ! Thanks !
