### ISSUE TITLE
Add container around forms

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#79]
See how [the forms on the events site have a shaded container around them](https://events.linuxfoundation.org/about/sponsor/).  Can we do something like that?  I think it looks good.

I'm thinking of for the [Speakers contact form](https://dev-cncfci.pantheonsite.io/speaker/zparnold/), the [bulk email form](https://dev-cncfci.pantheonsite.io/speakers/email-matching-speakers/?sf_action=get_data&sf_data=all&_sft_cncf-speaker-expertise=identity), and the [contact form](https://dev-cncfci.pantheonsite.io/about/contact/).  The forms also may look better all centered, as you've done with the contact form.

**Comment by thetwopct** [comment]
It does look better!

**Comment by cjyabraham** [comment]
Cool.  Could you round the corners and give the container a bit of height?  Maybe just [copy this](https://events.linuxfoundation.org/about/sponsor/) exactly?

**Comment by cjyabraham** [comment]
[I applied this to the register form and added a box shadow](https://github.com/cncf/cncf.io/commit/7ff8edcaa5d93fa06d47251e97c221ae70d41e18).  LMK if you don't like the shadow.  I think it looks good.
