### ISSUE TITLE
Project Timeline page

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#790]
Show full chronological history of project maturity levels for all CNCF projects. As you scroll the page from top to bottom you pass through years from 2006 to the present and see all project movements, from accepted, moving through sandbox, incubating and graduated (and archived) levels. Anyone at a glance can review all movements in any given year. Work with LF Design on something that looks good.

This will list 173 accepted activities, 57 incubating activities (minus 23 that were accepted at this level so are already counted), 23 graduated activities, so there will be approximately 230 activities to list to-date.

Ideally this should be done for Kubecon NA on Nov 6.

cc @amye

**Comment by cjyabraham** [comment]
I've submitted a request with LF Design for help with this.

**Comment by GarethAcidWorks** [comment]
Hey Chris, we have been assigned this by Melissa. I have an idea in my head of that this could look like but i will send a quick sync via slack to get some layout / interaction thoughts out quickly.

**Comment by cjyabraham** [comment]
Here's [the current dataset of all project maturity level moves](https://gist.github.com/cjyabraham/7170818d61e21673afb0bfd979098e62).

**Comment by cjyabraham** [comment]
The person who originally requested this is no longer at CNCF
