### ISSUE TITLE
DevStats metrics getting 400 Bad Request

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#798]
No code has changed on our side (AFAIK), maybe something has changed on DevStats, or maybe its not reproducible for you @cjyabraham 

![Screenshot-2023-10-06 --22 19 55](https://github.com/cncf/cncf.io/assets/10615884/8fb6542b-3dcf-4c34-a79e-d4b8010c2ea2)

Note: The API endpoint message seems like there is something wrong but there isn't https://devstats.cncf.io/api/v1 

![Screenshot-2023-10-06 --22 21 26](https://github.com/cncf/cncf.io/assets/10615884/c2d2c9ec-be94-4bd2-815d-ec634192e633)

**Comment by lukaszgryglicki** [comment]
Can you create an exact issue on cncf/devstats or cncf/devstatscode specifying what exactly you call, which request type and body
[5:49](https://cloud-native.slack.com/archives/C060F5N86AD/p1696607367483219)
like 1) Request URL, 2) Request type (GET/PUT/POST), 3) Request body
[5:49](https://cloud-native.slack.com/archives/C060F5N86AD/p1696607373455219)
I will investigate on Monday.
[5:49](https://cloud-native.slack.com/archives/C060F5N86AD/p1696607381837709)
or during the weekend if this is very urgent.
[5:50](https://cloud-native.slack.com/archives/C060F5N86AD/p1696607424884289)
Just LMK if there is any action item for me and how urgent it is (is Monday OK, or you need it tomorrow, or even ASAP).

**Comment by thetwopct** [comment]
Thanks Lukas, as per issue, we will investigate our side and open an issue on /devstats if needed. All our code is public, [you can see the relevant code here](https://github.com/cncf/cncf.io/blob/cceb816ffc9234dc6df0cbdc5baaacfcbd358886/web/wp-content/themes/cncf-twenty-two/classes/class-lf-utils.php#L419).

**Comment by cjyabraham** [comment]
I can reproduce the error. Perhaps it has been occurring for a long time. I've [filed a bug on devstats](https://github.com/cncf/devstats/issues/38) with some debug info.

**Comment by lukaszgryglicki** [comment]
Fixed: https://github.com/cncf/devstats/issues/38#issuecomment-1751624278
