### ISSUE TITLE
Migrate kubernetes.io Bing custom search to Microsoft Bing API’s on Azure Marketplace by Oct. 31

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#802]
### The backstory

The kubernetes.io Hugo site [uses Google Custom Search for its search](https://kubernetes.io/search/?q=cloud) except when the user is in China. It detects the user's location using ipinfo.io. If the user is in China, Google Custom Search won't work, so, instead, it uses Bing Custom Search.

### The situation

Our current Bing Custom Search will stop working on Oct. 31. This is because [Bing Search APIs will transition from Azure Cognitive Services to Azure Marketplace on that date](https://azure.microsoft.com/en-us/updates/bing-search-apis-will-transition-from-azure-cognitive-services-to-azure-marketplace-on-31-october-2023/). So, before then, we need to migrate our Bing Custom Search object from Azure Cog Services to Azure Marketplace and then make sure that kubernetes.io can use it correctly.

### Bonus points

This geoswitching of custom search engine could come in handy for all CNCF Hugo sites. Currently, they only use Google Custom Search and so the search doesn't work in China. Perhaps there's a way to abstract this functionality out into some kind of module which we can then use on all of our other Hugo sites. If so, then we can create a new issue for that work so it doesn't hold up closing out this issue.

**Comment by thetwopct** [comment]
PR opened - https://github.com/kubernetes/website/pull/43731

**Comment by sftim** [comment]
Does this change need backporting to https://v1-27.docs.kubernetes.io/ etc?

**Comment by sftim** [comment]
> This geoswitching of custom search engine could come in handy for all CNCF Hugo sites.

Alternative: use an open-source search.

Some options / partial solutions:
- [BloomySearch](https://github.com/Phyks/BloomySearch)
- [hugo-lunr](https://www.npmjs.com/package/hugo-lunr)
- [Pagefind](https://pagefind.app/)

**Comment by thetwopct** [comment]
> Does this change need backporting to https://v1-27.docs.kubernetes.io/ etc?

Yes, I wasn't aware of their existence. I think we could also improve the search - if searching on https://v1-27.docs.kubernetes.io results are returned across all of kubernetes.io which I guess isn't that useful, the search should be on the versioned site. 

Happy to switch to open source search if you prefer @sftim

**Comment by sftim** [comment]
Switching to open source feels like a long term thing.

> if searching on https://v1-27.docs.kubernetes.io/ results are returned across all of kubernetes.io which I guess isn't that useful, the search should be on the versioned site.

If we can do that, let's. It's not vital to have working search for the older versions by the switchover deadline, but it'd be nice to have. Otherwise, readers affected by state level censorship won't have an easy way to search older docs versions.

**Comment by cjyabraham** [comment]
Currently these older versions appear to redirect to the kubernetes.io search, so they're not exactly in working order. It seems that that needs to be fixed in addition to setting them up with the Bing search option for Chinese users. I'll close out this issue for now as its immediate scope has been accomplished. Please feel free to open new issues on [the kubernetes repo](https://github.com/kubernetes/website) for the old versions' search and exploring open source options. I don't have permissions to open issues on that repo.
