### ISSUE TITLE
Is there an RSS feed for KubeWeekly?

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#806]
https://www.cncf.io/kubeweekly/

We have users looking for the RSS feed of KubeWeekly

![Screenshot-2023-11-03 --13 16 29](https://github.com/cncf/cncf.io/assets/10615884/9683a1ac-9a01-47f8-be62-7279a39ba9ee)
![Screenshot-2023-11-03 --13 16 38](https://github.com/cncf/cncf.io/assets/10615884/c0b943f0-1fe0-4691-bace-0f8292de4f88)

If its available as an RSS we should include the feed on the page, as (I presume) some users prefer an RSS feed of a newsletter rather than a mailing list.

**Comment by cjyabraham** [comment]
There's no RSS feed. These are just a series of HubSpot emails. We'd need to load them in to WordPress and compile them into an RSS feed (or use some other service) if we were to produce one.

**Comment by thetwopct** [comment]
Lets close this off as it was just an idea

**Comment by cjyabraham** [comment]
KubeWeekly is now being published on the site and we've exposed a link to the RSS feed on [the KubeWeekly page](https://www.cncf.io/kubeweekly/)
