### ISSUE TITLE
Cert and Training pages, phase 2

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#811]
Make courses into a CPT with a filterable directory with the following meta:
- Projects
- Level: Beginner, Intermediate, Advanced
- Role: Security, Developer, Administrator, Engineers
- Status: Available, Coming Soon
- Cost: Free, Not-free

Make certifications into a CPT with directory (no filters).

Open questions:
1. Do we need single-post pages for courses? Or are we happy to just pop the user on to the LF course page?
_my feeling is that we should just pop them in to the LF course page so that we are DRY and the info doesn't drift out of sync; we do this for the same reason on [the upcoming online programs](https://www.cncf.io/online-programs/)_
2. Should we go with a tiled display for listing courses and certifications, similar to [case studies](https://www.cncf.io/case-studies/) (2 per row) or [humans](https://www.cncf.io/humans-of-cloud-native/) (3 per row); if so, we'd need to reduce the amount of info in the listing from what we have now
3. I feel "Overview" in the Training megamenu should read "Training Overview" or "Cloud Native Training" or just "Training". "Overview" by itself doesn't mean anything at a glance. Any thoughts?

**Comment by cjyabraham** [comment]
Waiting for feedback from stakeholders [on slack](https://cloud-native.slack.com/archives/C0669P57X9A/p1700213713781029)

**Comment by cjyabraham** [comment]
New content outlined in [this doc](https://docs.google.com/document/d/1yzwe33EDx8y5oK9TLcdMMfOpoimkHuRmv3VhplntSng/edit#heading=h.ykt7i8pf9fnt)

**Comment by Charley-Mann** [comment]
@cjyabraham will review post-KubeCon!

We'd also like to add a new "community" page to the trainings mega menu. Flagging now so we can add it to the discussion

**Comment by cjyabraham** [comment]
I've created the Courses CPT and [search/filter listing](https://www.cncf.io/training/courses/).

I've updated the "Overview" menu item to say "Training Overview" on both megamenu and footer.

I don't see an immediate need to create a Certifications CPT but we can do that if/when that need arises.
