### ISSUE TITLE
Migration to landscape2 API

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#827]
The current CNCF site imports data from the CNCF Landscape in the following places. Each will need an equivalent connection to landscape2.

We import all projects for showing on the projects carousel on [homepage](https://www.cncf.io/) and various [Projects listings](https://www.cncf.io/projects/). We use these calls:
- https://landscape.cncf.io/api/items?project=hosted
- https://landscape.cncf.io/data/items.json

Member count on [Who We Are page](https://www.cncf.io/about/who-we-are/) generated with this call:
- https://landscape.cncf.io/data/exports/cncf-members.json

We display the latest end users on the [End User page](https://www.cncf.io/enduser/) with this call:
- https://landscape.cncf.io/data/exports/end-users-reverse-chronological.json

We display the platinum members on the [Join page](https://www.cncf.io/about/join/) with this call:
- https://landscape.cncf.io/data/exports/cncf-platinum-members.json

We import and list KTPs on the [KTP listing](https://www.cncf.io/training/kubernetes-training-partners/) with these calls
- https://landscape.cncf.io/api/items?category=kubernetes-training-partner&grouping=no

**Comment by cjyabraham** [comment]
API calls needed:

`get_projects()` - returns all CNCF projects with all their metadata from landscape for all Project listings and charts

`get_member_count()` - returns total number of CNCF members for use on the Member count on [Who We Are page](https://www.cncf.io/about/who-we-are/)

`get_ktps()` - returns all KTPs with all their metadata from landscape for [the KTP listing page](https://www.cncf.io/training/kubernetes-training-partners/)

To display the latest x end users on the [End User page](https://www.cncf.io/enduser/) and the platinum members on the [Join page](https://www.cncf.io/about/join/), we could possibly use an embed code? Otherwise we would need functions to get at these values.

**Comment by tegioz** [comment]
Hi Chris!

- **get_projects() / get_members()**: sounds good! It'd be great if you could define the metadata needed, to include only what you need for now.
- **get_ktps()**: to do this in a generic way, we'd generate data files for each category and category/subcategory combination (something similar to what we do for the embed code).
- **end users**: do you mean items in the `Members / End User Supporter` subcategory or Members with `enduser: true`? I think we can handle this generically as well either way, as the member concept is generic across landscapes.
- **platinum members**: the embed code is an option, but you'd also have the raw data for this subcategory based on the solution mentioned above for *get_ktps()*.

Given that all of this can be expressed in a generic -not CNCF specific- way, it can be a good opportunity to start building *"the landscape API"*. This API would be just a bunch of pre-generated data files, similar to the ones we already serve on `/data/…` to power the web application and the embeddable views, but served from `/api/…`. Having them separate will provide a stable interface for consumers to build upon, and will leave us freedom to keep evolving the landscape as needed without having to worry about breaking integrations.

We can discuss this a bit more on Monday during our chat and if it looks good we should be able to get it done next week 🙂

**Comment by cjyabraham** [comment]
The generic solution sounds great if it works here and can apply to other landscapes. Below are the metadata we use for each of the calls, but, of course, it's fine to include additional fields.

Metadata for `get_projects()`:
- name
- hompage_url
- twitter 
- logo
- project
- repo_url
- path (that is, what categories the project is nested in like "Provisioning/Security & Compliance")
- description
- extra->dev_stats_url
- extra->artwork_url
- extra->stack_overflow_url
- extra->accepted
- extra->incubating
- extra->graduated
- extra->archived
- extra->blog_url
- extra->mailing_list_url
- extra->slack_url
- extra->youtube_url
- extra->gitter_url

Metadata for `get_members()`:
- name (I just need name here since we just use this call to count the members)

For `get_ktps()` I'm not sure what you mean by "generate data files for each category and category/subcategory combination". Could you list them all in one file? For this set we need this metadata:
- name
- hompage_url
- logo
- description
- country (I think this needs to come from the Crunchbase data)
- extra->training_certifications
- extra->training_type

For end users, I think this is when `enduser: true`

**Comment by tegioz** [comment]
Cool, thanks 👍

**Comment by tegioz** [comment]
Hi!

We've just deployed a first version of the landscape2 API. The following endpoints should cover what you need:

- <http://landscape.cncf.io/api/categories/special/kubernetes-training-partner/all.json>
- <http://landscape.cncf.io/api/members/count.json>
- <http://landscape.cncf.io/api/members/end-users.json>
- <http://landscape.cncf.io/api/projects/all.json>

There are some more, like one for getting all members, or specific endpoints for each category and subcategories.

Some notes:

- Endpoints that return landscape items (i.e. `all.json`) can potentially return the same set of fields, but this will vary depending on the information available for each of the items. You can see a full list of fields [here](https://github.com/cncf/landscape2/blob/f18d74bab44eac4b6eb4e166c8874a80c7294117/src/build/api.rs#L194-L299).
- All the information you requested should be included, but names may be slightly different. One example would be the repository url. The endpoints return a list of repositories for each item (when available), and the primary one is marked with a special `primary` flag.
- Items are sorted alphabetically by name in all endpoints returning items, for consistency reasons. Hope it's not a problem to sort the end users on your end (the joined field is included).

Please let me know if you have any question 🙂

**Comment by cjyabraham** [comment]
The CNCF site has been updated to use this new API.
