### ISSUE TITLE
In The News listing implementation

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#83]
For the migration:
- on automated migration I could strip out the news source from the title of each post and turn those into tags
- on manual migration we could take the url from the READ MORE links and assign to the SEO Framework "301 Redirect" setting

For [the news listings](https://dev-cncfci.pantheonsite.io/news/):
- don't truncate the post content on the listing page
- show the news source from the tag
- link the title to the news post itself with url stored in the "301 Redirect" setting; link out to a new tab with the external link icon; if the this value isn't set, then just link to the post
- the image shown in the listing could be obtained first by checking the featured image for the post; if none is set (which will usually be the case), check for an image in the Media Library that has the same name as the slug of the first tag assigned to the post; if none, then use a default news image

What do you think?

**Comment by thetwopct** [comment]
I've done a basic styling of this page with what I had, in-conjunction with an improved layout of newsroom that gives better spacing and alignment. Have added a new image size for media coverage logos that does not crop, but I think you will need to regenerate or re-upload logos to see that in action for the non-SVG images.

**Comment by cjyabraham** [comment]
Logos look good!

Revision 2 of this issue:
- the title of the post links to a meta value url "External URL", if it exists (link out to a new tab with the external link icon), otherwise links to the usual single post page
- the featured image is set manually to populate the news icons in the listing; if not present, we could fallback to some news-oriented image
- news icons, when uploaded, can be suffixed with "-newsicon" so they can be easily found in the media library
- on migration, we can set the first couple pages of posts up so that they employ the correct icons and "External URLs" and show the editors how to do this going forward

What do you think?

**Comment by thetwopct** [comment]
Agree.
Featured image - I think we should use a plain CNCF logo and hardcore that as a replacement. Using the generic override image (although this can / should be changed) doesn't look good.
We can certainly do point 3, but this may not be done by editors!

**Comment by cjyabraham** [comment]
As discussed, I'll work on this and try and extract the external url from the read me.

**Comment by cjyabraham** [comment]
@thetwopct Could you add an external link icon to only those news links that link externally?

**Comment by thetwopct** [comment]
OK that's done. I don't know if its possible to pull out the read more links and delete them at the same time? Maybe going forward editors won't add them to the end of posts.

**Comment by cjyabraham** [comment]
Good idea.  [Done](https://dev-cncfci.pantheonsite.io/news/) and [noted in the Editor Instructions](https://docs.google.com/document/d/1TmjvB4MAFEFtYKLhMPuWl_J1guaXdHZh5d2BTQhe4wE/edit#heading=h.olffp1nlfcsg).
