### ISSUE TITLE
Add support for filtering ambassadors on language

### ISSUE THREAD

**Issue by JonZeolla** [cncf/cncf.io#848]
I saw autogenerated links on people's profiles under language but the filtering doesn't seem to work

Example:

https://www.cncf.io/people/ambassadors/?p=jon-zeolla

Has a link to

https://www.cncf.io/people/ambassadors/?_sft_lf-language=american-sign-language

**Comment by cjyabraham** [comment]
Thanks for reporting this. The language filters should work now.
