### ISSUE TITLE
Remove "Company" metadata from case studies sidebar

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#85]
I don't think we need company here:
<img width="683" alt="Screen Shot 2020-05-16 at 11 01 26 AM" src="https://user-images.githubusercontent.com/463160/82108895-aa6cc400-9764-11ea-8ef3-d3036f5d50de.png">

**Comment by thetwopct** [comment]
Inspired by https://kubernetes.io/case-studies/booking-com/ it allows for more freedom in the title of the case study; perhaps the title of the company is not always mentioned or is not overly obvious (due to overuse of capitalisation).

**Comment by cjyabraham** [comment]
ok
