### ISSUE TITLE
Deadlink on FAQ page for TOC proposal process

### ISSUE THREAD

**Issue by rocketnova** [cncf/cncf.io#850]
From URL: https://www.cncf.io/about/faq/

> CNCF and each of its projects have their own website. What is the relationship and why multiple sites?
>
> CNCF hosts many [projects](https://www.cncf.io/projects/) in the cloud native ecosystem. New projects are added as approved by the TOC (proposal process [here](https://github.com/cncf/toc/blob/master/process/project_proposals.md)).
> 
> CNCF provides many [resources to the projects](https://www.cncf.io/services-for-projects/) to support their adoption and assist with project velocity. But each project continues to operate independently under its pre-existing governance structure and with its existing maintainers. The project websites are the best place to learn about and work with each individual project. The CNCF website is a source for cross-project efforts like events and other initiatives.

The link "proposal process here" results in 404. Possibly it should instead link to https://github.com/cncf/toc/blob/main/process/README.md?

**Comment by thetwopct** [comment]
I've updated the page for this, thanks for reporting!
