### ISSUE TITLE
In Call For Proposals page the link to end and non-end users is not displaying the right information.

### ISSUE THREAD

**Issue by chaltenio** [cncf/cncf.io#853]
In the section "End User Companies" there is an issue with the link that should be displaying "end" and "non-end users" on the CNCF Landscape site. The link https://landscape.cncf.io/card-mode?enduser= is not showing the correct information.

![cfp_users_cncf-io](https://github.com/cncf/cncf.io/assets/54964683/0652aae9-55f6-41a5-b2c8-a236e023e240)
![cfp_users_cncf-io-2](https://github.com/cncf/cncf.io/assets/54964683/95adc63e-3959-4b6a-928f-2f66380e72c9)

**Comment by cjyabraham** [comment]
Thanks. This is now fixed.
