### ISSUE TITLE
Add Company Logos for End User TAB Members on CNCF End User Technical Advisory Board Page

### ISSUE THREAD

**Issue by onlydole** [cncf/cncf.io#855]
@pritianka and I would like the CNCF website page [End User Technical Advisory Board] (https://cncf.io/people/end-user-technical-advisory-board/) to include company logos for each member of the End User Technical Advisory Board (TAB). The logos will help visitors quickly identify the companies each member represents.

Ideally, we could have the company logos linked to their respective CNCF Landscape Member cards (ex. https://landscape.cncf.io/?item=cncf-members--platinum--apple-member)

**Comment by cjyabraham** [comment]
Ok, sounds fine. Do you want the logos added to the respective profile cards for each of the members? Or were you thinking we'd list all the logos in a separate section below the member profiles?

**Comment by onlydole** [comment]
Excellent! Under the individual folks would be great.

**Comment by cjyabraham** [comment]
Hi @onlydole , Ricardo Rocha has CERN listed as his company, however, CERN doesn't seem to be on the landscape. Do you want us to include the CERN logo anyway and link to the CERN website?

**Comment by onlydole** [comment]
That would be great, @cjyabraham!

**Comment by thetwopct** [comment]
@onlydole we've got a draft of this together - can [preview it here](https://pr-857-cncfci.pantheonsite.io/people/end-user-technical-advisory-board/).

- Each persons card is a little inconsistent, some with pronouns, some with a TAB position, some logos big, some small. I'm not super happy with the layout, but without adding more data or removing data, not sure how it could be improved. 
- A couple of logos have white space around them which misaligns them or makes them look too small - I submitted a [PR](https://github.com/cncf/landscape/pull/3918) to landscape to fix this

Feedback from you:
- Do you want the logos in the persons modal window when that opens? If so, we think just below the name is probably best; or any other feedback?

![Screenshot-2024-06-14 --00 06 09](https://github.com/cncf/cncf.io/assets/10615884/c72145af-e052-468d-8975-343ff8613c1d)

Still to do:
- Handle the missing CERN logo

**Comment by onlydole** [comment]
Thank you so much, @thetwopct. I like where those logos are positioned. If there's any way to force block formatting inside the "people containers" for folks who haven't yet set their preferred pronouns so it lays out more uniformly, that would be preferred.

**Comment by cjyabraham** [comment]
I've added [the CERN logo and link](https://github.com/cncf/people/pull/506)

**Comment by thetwopct** [comment]
@onlydole Great idea on the pronoun spacing, looks so much better ✅ CERN logo now included, a couple of other logos updated, so I think ready for final approval now. If happy I can get it live. 

https://pr-857-cncfci.pantheonsite.io/people/end-user-technical-advisory-board/

**Comment by onlydole** [comment]
This looks GREAT, @thetwopct! You've got my approval - thank you both for making this look excellent and for adding in the CERN logo/link!

**Comment by cjyabraham** [comment]
The logos are now live: https://www.cncf.io/people/end-user-technical-advisory-board/

I'll close this issue for now but let us know @onlydole if you need any further tweaks to this.
