### ISSUE TITLE
Post preview expiry can't be extended

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#856]
Currently the Post Preview plugin seems to expire preview links after 2 days. I've inserted [this snippet](https://github.com/cncf/cncf.io/commit/2ea71edca9a975df9cb0c1663e2f229e61cc6767) to try and extend that. It turns out that that snippet no longer seems to work even though it's recommended on [the plugin page](https://wordpress.org/plugins/public-post-preview/). See issues [here](https://wordpress.org/support/topic/in-what-way-is-expiration-calculated/) and [here](https://wordpress.org/support/topic/expiration-snippet-not-working/). It'd be nice to figure out how to extend it at some point since 2 days is just not long enough.

**Comment by cjyabraham** [comment]
Also, @thetwopct reported that the plugin also now doesn't work with some data in ACF or templates. The preview link for the report doesn't show the header info but the logged in normal preview does.

**Comment by thetwopct** [comment]
This seems to have started working again with ACF fields - for example [this preview](https://www.cncf.io/?p=118671&post_type=lf_report&preview=1&_ppp=f1fc944f03) works fine. I found [this thread about nonce lifetime](https://github.com/ocean90/public-post-preview/issues/26), but the v3 mentioned was never released. Should we try to fix the nonce issue ourselves as this plugin is pretty useful and I can't find a decent alternative.

**Comment by thetwopct** [comment]
> Ya, why not fork it into the CNCF repo, fix it, and release it as a new plugin, giving credit to the original? Is this what you were thinking?

I'll fork it to make the changes, maybe I'll try to push the updates to wordpress.org too, currently the plugin seems to be abandoned so will be nicer for all if its doing the basics.

**Comment by cjyabraham** [comment]
[Version 3 of the plugin](https://wordpress.org/plugins/public-post-preview/) has been released so I have deployed it. Let's hope this solves the issue.
