### ISSUE TITLE
How to force syncs

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#858]
We need a way (there could already be one, if so let's document) to force sync KCDS, people, etc.

**Comment by cjyabraham** [comment]
We can trigger cron jobs via terminus like this:
```
lando terminus wp cncfci.live -- cron event run lf_sync_kcds
lando terminus wp cncfci.dev -- cron event run --all
lando terminus wp cncfci.dev transient delete cncf_homepage_metrics
```

The people repo, however, doesn't sync via a cron job. When a PR is merged on that repo it triggers a web hook which causes the live CNCF instance to sync with it. This web hook can be triggered manually within the people GH repo settings but you need admin permissions.
