### ISSUE TITLE
Quote block should default to "default" styles

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#87]
When I insert a quote block it defaults to a black bar style like this:
<img width="1191" alt="Screen Shot 2020-05-16 at 11 12 41 AM" src="https://user-images.githubusercontent.com/463160/82109115-3af7d400-9766-11ea-836d-a4a746489c85.png">

It's strange since the editor shows "Default" is selected with the pink bar.  The user has to deliberately click "Default" in order for the pink bar to show.  Can this correctly show the "Default" styles from the beginning?

**Comment by thetwopct** [comment]
The way default styles work in Gutenberg don't make a lot of sense, so this is something I need to override. The is_default flag also doesn't activate the default style on insert 🤷‍♂️ 

Once this style is confirmed will set it all up.

**Comment by cjyabraham** [comment]
If it's a consistent UX issue that's part of Gutenberg, perhaps they'll fix it in a later release, in which case I'd suggest not doing anything.  If it's something that we caused, then we should fix.
