### ISSUE TITLE
Broken link to project proposal process at the bottom of https://www.cncf.io/project-metrics/

### ISSUE THREAD

**Issue by krook** [cncf/cncf.io#870]
With the reorganization of the TOC repo and its docs, the updated link for the "PROJECT PROPOSAL PROCESS" button at the bottom should now point to https://github.com/cncf/toc/blob/main/process/README.md#cncf-project-lifecycle--process (or similar link to the README)

**Comment by cjyabraham** [comment]
Thanks. That's updated.
