### ISSUE TITLE
 The company name is missing in KubeWeekly 395

### ISSUE THREAD

**Issue by riteshsonawane1372** [cncf/cncf.io#876]
From URL: https://www.cncf.io/kubeweekly/kubeweekly-395/
Thank you for featuring our blog on `Scaling Prometheus with Thanos`. I greatly appreciate the recognition and the opportunity to reach a larger audience. However, while the author’s name was mentioned, the company name, `CloudRaft`, was not included. I request you to add the name of our company `CloudRaft` on which the original blog was published, you can check [here](https://www.cloudraft.io/blog/scaling-prometheus-with-thanos). I'm attaching an SS for more info.  

![image](https://github.com/user-attachments/assets/57bc19d3-3ee8-48cf-be40-fab10934c883)

**Comment by cjyabraham** [comment]
Ok, I've added the company name. Thanks.
