### ISSUE TITLE
menu is going outside browser

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#88]
Maybe the screen height calculation isn't accounting for the hello bar here?
<img width="666" alt="Screen Shot 2020-05-16 at 1 29 10 PM" src="https://user-images.githubusercontent.com/463160/82111693-7e0f7280-9779-11ea-8e89-98a9d6c6da69.png">

**Comment by thetwopct** [comment]
I've added a few workarounds for this and it should keep that bottom menu inside screen content. Would be good to revisit this once we have full content in to the menus for a final check.
