### ISSUE TITLE
Support X handle parsing

### ISSUE THREAD

**Issue by SD-13** [cncf/cncf.io#881]
In CNCF job board manage profile page, under twitter section, if we give link e.g. `twitter.com/...` it parses it properly and replace with username but if we give `x.com/...` it shows error and doesn't parse the username.

![image](https://github.com/user-attachments/assets/477ce5c7-1ff9-45e0-a609-bf41fd8cc3aa)

**Comment by SD-13** [comment]
Hey @cjyabraham, I raised it to the jobboard.io team, and it's in their backlog.

**Comment by cjyabraham** [comment]
Great. Thanks for helping to improve this!
