### ISSUE TITLE
Grainy images on Watts Water Technologies Case Study

### ISSUE THREAD

**Issue by mcupito** [cncf/cncf.io#882]
From URL: https://www.cncf.io/case-studies/wattswatertechnologies/

The images are grainy and the text is aligned incorrectly in the powerpoint slide. Looks like the Comfortaa font was not installed where the images were captured as well. It should look similar to below

![image](https://github.com/user-attachments/assets/3254992f-a0f1-4781-bdb4-68fcd6d6169c)

**Comment by thetwopct** [comment]
Hi @mcupito 
If this was supplied to us as a Powerpoint then these often do not include fonts installed on your personal system. If you can Export the original powerpoint as a PDF and add here then this should ensure that fonts are rasterised and when we export the screenshots required for this case study they should be higher resolution.

**Comment by mcupito** [comment]
[Watts_Dapr_CaseStudy_v2.pdf](https://github.com/user-attachments/files/16900662/Watts_Dapr_CaseStudy_v2.pdf)

@thetwopct done - thank you!

**Comment by thetwopct** [comment]
The images have been updated using exports from the PDF, thanks!
https://www.cncf.io/case-studies/wattswatertechnologies/
