### ISSUE TITLE
People import can't handle people with same name

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#883]
There are currently [two people called Daniel Dias](https://github.com/cncf/people/blob/main/people.json#L3784-L3823) in people.json and the sync routine only imports the last one since it's not set up to handle two people with the same name.

**Comment by satrox28** [comment]
Thanks for submitting the issue @cjyabraham

**Comment by satrox28** [comment]
Awesome @cjyabraham. Thanks a lot for the quick turnaround in fixing this issue 😊.
