### ISSUE TITLE
English needed!

### ISSUE THREAD

**Issue by stocrkc** [cncf/cncf.io#885]
From URL: https://www.cncf.io/projects/carina/

In the English version of the website, the link in the picture below is the Chinese version. Clicking on the link will also jump to the [relevant page in Chinese.](https://www.cncf.io/case-studies-cn/)
![image](https://github.com/user-attachments/assets/63346624-25f4-48d3-ab0e-6b5f005fac8d)

**Comment by cjyabraham** [comment]
That's correct. Those are Chinese translations of our case studies. The English ones are listed in [the normal Case Studies page](https://www.cncf.io/case-studies/).
