### ISSUE TITLE
Event buttons visited colour

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#89]
I think they should always remain white, [at least here](https://dev-cncfci.pantheonsite.io/events/):
<img width="1115" alt="Screen Shot 2020-05-16 at 6 30 18 PM" src="https://user-images.githubusercontent.com/463160/82117567-6baa2e80-97a3-11ea-9291-08939584ee1d.png">

**Comment by thetwopct** [comment]
Updated for Events, generally they are set to white, but some button style / Gutenberg may overwrite, so please let me know if you spot anymore.

**Comment by cjyabraham** [comment]
This does not appear fixed on dev.  Did you deploy?

**Comment by cjyabraham** [comment]
This looks fixed
