### ISSUE TITLE
Add filterable display for blog posts

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#891]
Add filters at the top of blog listing:
- Free-text search
- Post Author Type
- Project

Maintain our current functionality of having a sticky/featured post at the top of the listing when set. Probably this needs to go above the filters.

It was proposed to also have a "Year" filter, however, we're investigating whether that is needed and if the pagination controls will satisfy the same use-case. We may also have an "Industry" filter at a later point.

For now we don't need these filters at the top of News or Announcements.

On the single-post page for a blog post, list Projects logos in a way similar to on case studies.

Turn off indexing of project pages and other taxonomy pages. Check if this is necessary.

**Comment by thetwopct** [comment]
Whats the status of adding the project logos to single blog posts?

**Comment by cjyabraham** [comment]
Deployed
