### ISSUE TITLE
Posts in menu have lost spacing

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#892]
![Image](https://github.com/user-attachments/assets/50e23b89-62de-4996-8ce4-b0a084101fb5)

**Comment by thetwopct** [comment]
I also now cannot reproduce. Weird. These styles are related to singular post style changes we deployed yesterday so I thought I might have broken it... Closing unless we see again...

**Comment by thetwopct** [comment]
Spoke to soon, there _is_ an issue, but it only happens on the search page - https://www.cncf.io/?s=test then open the menu.

**Comment by cjyabraham** [comment]
Wow! So weird!
