### ISSUE TITLE
External media usage on blog

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#900]
Issue: Blog posts are embedding external images from third party sites. This is bad for multiple reasons, but mostly:

- Performance - the external images are not lazy loaded, do not have srcset, require extra connections for our users, do not take advantage of our CDN
- Longevity - we do not control the source, and this could disappear, leaving broken images links throughout the site
- Privacy - this creates issues for privacy, GDPR, etc.

Examples:

**From Medium**
https://www.cncf.io/blog/2024/10/30/how-to-ace-the-certified-gitops-associate-cgoa-exam/

**From Company blogs**
https://www.cncf.io/blog/2024/10/29/the-business-value-of-a-kubernetes-based-platform/
https://www.cncf.io/blog/2024/10/25/what-is-zero-trust-authorization/

**From Google Drive**
https://www.cncf.io/blog/2024/10/24/dont-miss-the-project-pavillion-at-kubecon-cloudnativecon-north-america-2024/
https://www.cncf.io/blog/2024/10/22/how-to-transform-telemetry-data-from-ingest-to-actionable-insights/

Can we discuss how to prevent this from happening and how to solve old posts?

## Prevention

1) Make sure the blog team know to fix this or look for this when copy pasting an article
2) We could use some CSS in the admin area, so whenever an image is included with a src that is not cncf.io, we highlight the image in bold red so its clear to the admin that something is wrong.
3) We use/activate Pre-publish checklists which gives a warning about external images (believe this part of core)

![Image](https://github.com/user-attachments/assets/17c09bac-c522-4fe8-89b9-cb110dc0f4a0)

## Fixing old posts

4) Can we find an old plugin to auto-update old posts or get someone to do it manually (the CSS could make spotting the images easier)

**Comment by cjyabraham** [comment]
We have Selly doing this import of external images manually currently (the CNCF editors don't have time.) Selly may be a week or two behind on her work, which is acceptable, so the posts you linked to probably have not been processed by her yet. I took a quick look but couldn't find any older posts with images not hosted by the cncf site. LMK if you see any.

Even though we're doing this manually, if you think there's a technological solution that could help with or entirely replace the manual work, then we could try that.

**Comment by thetwopct** [comment]
They don't have time? It's literally a one button click to upload them? Are they using Pre-Publish Checklists? This is default behaviour and a default option. Seems truly bizarre we are manually updating images after the fact at extra cost when WordPress already makes it extremely easy to deal with at the point of publishing...

![Image](https://github.com/user-attachments/assets/eb6f76c0-d8db-4aab-aad0-facd4435b56f)

If pressing one button is too much hassle for them (😆),  I can automate the uploading?

**Comment by cjyabraham** [comment]
Ah. I was not aware we already had that functionality available. Is it possible to **require** all images be uploaded prior to "Publishing"? That would be ideal. Then I'll connect with Jessie and Selly to shift to using this mechanism and relieve Selly of her role.

**Comment by cjyabraham** [comment]
With deploying the upgraded WP that fixes this upload mechanism, I've communicated it to Jessie so she can upload these images going forward and relieve Selly of her task. Let's see if that sticks. Will close this out for now.
