### ISSUE TITLE
Stop the FOUC on the various background images

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#91]
Can you stop [this background image from flashing in a squished format](https://drive.google.com/file/d/17h8Xxo2dRs__8ijI269h4E83l89Cg2_u/view?usp=sharing)?  It likely has something to do with the order the CSS is loaded.

**Comment by thetwopct** [comment]
I did mention this section was just a placeholder for now

**Comment by cjyabraham** [comment]
I'll keep an eye out for this and close when all looks good.

**Comment by thetwopct** [comment]
As you haven't closed, can you let me know where the issue persists?

**Comment by cjyabraham** [comment]
I see it occasionally on hero images, as in the video.  I only rarely see it and it's not such a big deal so I'd say don't worry about it for now.  I'll demote to nice-to-have.

**Comment by cjyabraham** [comment]
[Here's another vid showing the issue on both hero images and post images](https://drive.google.com/file/d/1H6GKbZc57P6vYEjf4-Hm6aV3T9nF0HQS/view?usp=sharing).  I'm not sure there's anything we can do about it and it may just be noticeable to me due to bandwidth issues.  I believe the resize takes place because there's a delay in downloading and applying the css.  The css file is at the top of the html source so not sure there's anything we can do further to mitigate this.  We could try using images that already fit the box correctly, however, the box aspect ration responds to different devices and so there is no one size that's a perfect fit.  

@dankohn would you like us to pursue this further?  If not, I say let's keep this issue on the backburner.

**Comment by dankohn** [comment]
You can leave open and focus on other stuff first.

**Comment by cjyabraham** [comment]
This is from two designs ago. Will start a new issue if it is a problem with the new design.
