### ISSUE TITLE
The mobile image is squished on homepage event banner

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#912]
![Image](https://github.com/user-attachments/assets/ec2121a1-7397-4533-9f46-fdfa954d2126)

**Comment by cjyabraham** [comment]
The markup for the image is includes `sizes="auto, (max-width: 1200px) 100vw, 1200px"`
the `auto` didn't used to be there in previous version of WordPress and seems to be what is messing up the mobile image dimensions.

**Comment by thetwopct** [comment]
I find it strange that the KCCNC Europe banner displays fine, but the India one doesn't.

**Comment by cjyabraham** [comment]
I'm seeing both as squished. Are you not?

![Image](https://github.com/user-attachments/assets/7f3b7220-1fb3-4286-a3b5-27a6118739fa)

**Comment by thetwopct** [comment]
Strange. On Firefox neither is squished. On Chrome it's not consistent. I checked the source files but they seem accurate.

**Comment by cjyabraham** [comment]
This old instance of our site doesn't insert `auto` in the `sizes` attribute and it always renders correctly: https://pr-906-cncfci.pantheonsite.io
Perhaps we need to create the element by hand rather than relying on the WP convenience functions for srcset. Actually that is why I built [the banner-ad markup by hand](https://github.com/cncf/cncf.io/blob/main/web/wp-content/themes/cncf-twenty-two/includes/shortcodes/banner-ad.php#L42-L49) as I had the same issue.

**Comment by cjyabraham** [comment]
I've implemented by hand for now to fix the issue. If you can think of a downside to this or a better way to do it, then we could explore that, both for the event banner and the banner ad shortcodes.

**Comment by thetwopct** [comment]
OK, well srcset is there for a reason. I guess acceptable as a quick fix. Maybe a longer term fix is removing the "auto" that us being added to our already valid markup - I think the code outlined here in trac does that https://core.trac.wordpress.org/ticket/61847#comment:23

**Comment by cjyabraham** [comment]
Ya, it seems this filter achieves that:
`add_filter('wp_img_tag_add_auto_sizes', '__return_false');`

Just reading up on if there are downsides to this...

**Comment by cjyabraham** [comment]
Ya, it seems this filter achieves that:
`add_filter('wp_img_tag_add_auto_sizes', '__return_false');`

It's not clear to me right now, however, what adding this filter will do across the site and if it's desirable. There are a few threads of discussion relevant to this on [the WP trac](https://core.trac.wordpress.org/ticket/62413) and more info may come to light in the near future since it seems to be affecting a lot of people. I'll reopen this issue and set it as nice-to-have so we can investigate further.

**Comment by cjyabraham** [comment]
Here's [the best explanation](https://make.wordpress.org/core/2024/10/18/auto-sizes-for-lazy-loaded-images-in-wordpress-6-7/) of this new `auto` sizes word added by WP 6.7. It's only applied to "lazy" loaded images.

With that in mind, [I turned off "lazy" on the banner ads](https://github.com/cncf/cncf.io/commit/dfcad58658f7db470893debaf401a529625cf5b1) since, at least right now, we have those loaded first thing on a page.

For the event banners, "lazy" is useful since those normally appear part-way down pages, so I don't want to turn that off. I could set this filter `add_filter( 'wp_img_tag_add_auto_sizes', '__return_false' );` for the whole site, however, that seems heavy-handed to address just one image on the site. I can't say I fully understand what `auto` does but, if that's the way browsers are going, I'd rather not interfere. So that leaves the solution I already have implemented, not using srcset for these event banners fully and keeping them implemented by hand. I don't think this will have any material disadvantages since most browsers will use the images stated in the `<source>` tags anyway, if my understanding is correct.

Will close this then for now assuming my reasoning is sound.
