### ISSUE TITLE
Make space larger after image in mobile blog listing

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#94]
Could you give the image a bit more space below it before the title of the blog post in the mobile view of the blog listing?
<img width="335" alt="Screen Shot 2020-05-19 at 9 01 10 PM" src="https://user-images.githubusercontent.com/463160/82332028-7836bd00-9a17-11ea-8e38-682341d74668.png">

**Comment by thetwopct** [comment]
With the rejigged design of this page I have added extra margin on mobile.
Also got rid of that weird gap under the image.
