### ISSUE TITLE
Make countup block countup as soon as it enters the viewport

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#95]
It seems like the countup block doesn't start counting until it reaches almost the half-way point when scrolling up the viewport.  It can results in the user stopping before then and seeing this:
<img width="1427" alt="Screen Shot 2020-05-20 at 9 35 42 AM" src="https://user-images.githubusercontent.com/463160/82395073-4b1cf580-9a7d-11ea-8575-467d8c342d88.png">

Can we make the counting start as soon as it's visible in the viewport?

**Comment by thetwopct** [comment]
The animation is triggered by Waypoints when the data-element "count-up-block" comes in to view. As the numbers are the bottom part of this section, I have set the trigger to start the animation when the top of the section hits 25% of screen. This triggers them as they come in to view.

**Comment by cjyabraham** [comment]
LGTM
