### ISSUE TITLE
Weird underlined hover state on countup block

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#97]
Click on one of the countup block links, then go back to the page with the countup block.  The link you clicked on now shows an underline when you hover over its background:
<img width="661" alt="Screen Shot 2020-05-20 at 5 29 32 PM" src="https://user-images.githubusercontent.com/463160/82430179-95bf6180-9abf-11ea-8fa0-8abb7fb0c346.png">

**Comment by thetwopct** [comment]
Think I've fixed this, but having issues reproducing in first place, can you check for me?

**Comment by cjyabraham** [comment]
Looks fixed.  Thanks.
