### ISSUE TITLE
Restrict search filter CSS to pages using Search Filters

### ISSUE THREAD

**Issue by thetwopct** [cncf/cncf.io#98]
The search filter plugins CSS is loading on every page - "search-filter-plugin-styles-css"

Would like to restrict it to be loaded on only the pages using Search Filter.

wp_dequeue_style( 'search-filter-plugin-styles' );

Didn't know if something you had done previously for LFE / you could take a look?

**Comment by cjyabraham** [comment]
We haven't done this on LFE—we just load it on every page.  It's only 8K so I'm ambivalent on whether we do this.  I'll tag as nice-to-have for now.

**Comment by thetwopct** [comment]
Dequeued via `is_front_page()`

If we want to kill it on other pages too, we could dequeue it globally, and then enqueue it via the search-filter template files. 

For now, I'll close this off
