### ISSUE TITLE
Blog listing should show the author and author category

### ISSUE THREAD

**Issue by cjyabraham** [cncf/cncf.io#99]
When the blog post is by some specific I think we should show the author in the [blog listing](https://dev-cncfci.pantheonsite.io/blog/).  We should also have the author category slash thing.

**Comment by thetwopct** [comment]
I've added the author category to the archive, but adding the guest author text frankly looks messy. The guest author text is very inconsistent and often seems to be long. I would recommend - unless we/editors can come up with a more elegant solution - that it should be only added to the singular post.

Some random examples from the last few blog posts:

- Guest Post by Alon Berger, Technical Marketing Engineer, Alcide
- Guest Post originally published on Medium by Saurabh Gupta, Sr. Developer Advocate @DigitalOcean
- Guest post originally published on the OOVO blog
- Guest post originally published on the Rookout blog by Or Weis
- Originally published on goharbor.io by Alex Xu Harbor Contributor and Senior Product Manager, VMware

So the guest author byline is oft longer than the post title itself.

**Comment by cjyabraham** [comment]
I did not intend to suggest you add the guest author blurb.  I was thinking more that when a blog has an author set that is not "CNCF", such as [this one by Kim](https://dev-cncfci.pantheonsite.io/blog/2020/05/14/call-to-participate-1h-2020-cncf-cloud-native-survey/), that we surface that on the blog listing.  If "CNCF" is the author then just omit it.  Would that work?

**Comment by thetwopct** [comment]
Ah OK. I would just see adding Guest Author as a natural progression of this though, but we can cross that bridge when the request comes...

I've added any non-CNCF author names to the same line as the date. Formatting looked a bit funky when mixing date styling and normal text, so currently its all in date format style. 
https://cncfci.lndo.site/blog/
